### ISSUE TITLE
openCyto / flowStats error

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/openCyto#100]
I used openCyto a few months ago well.
Recently, I updated a few packages like 'flowStats'. 
Then, suddenly 'openCyto' do not work well and error sign is popped up.

> library(openCyto) # error
Error : objects ‘dfltCounts’, ‘drvkde’ are not exported by 'namespace:ks'
Error: package or namespace load failed for ‘openCyto’

**Comment by gfinak** [comment]
Ks is a dependent package that changed its api. You should update all the
flow infrastructure as we had to make changes across the board to account
for this. Mike Jiang may have more information on the specifics..

Greg Finak

**Comment by kdh4win4** [comment]
Mr. Finak,
Do you mean updating all the packages for openCyto ?
What are 'flow infrastructures" ?

**Comment by mikejiang** [comment]
Please install the latest `openCyto` and `flowStats` release version. See details in https://github.com/RGLab/flowStats/issues/16

**Comment by kdh4win4** [comment]
Yes. I installed the last version of flowStats, openCyto, flowWorkspace, flowCore. 
I think I missed something, however, I could not get it yet. 

> library("flowStats", lib.loc="~/Library/R/3.2/library")
Loading required package: flowWorkspace
Error: package ‘flowCore’ 1.34.11 is loaded, but >= 1.36.3 is required by ‘flowWorkspace’
In addition: Warning messages:
1: package ‘flowStats’ was built under R version 3.3.0 
2: package ‘flowWorkspace’ was built under R version 3.2.3 
> library("openCyto", lib.loc="~/Library/R/3.2/library")
Loading required package: flowWorkspace
Error: package ‘flowCore’ 1.34.11 is loaded, but >= 1.36.3 is required by ‘flowWorkspace’
In addition: Warning message:
package ‘flowWorkspace’ was built under R version 3.2.3 
> install.packages("~/Downloads/flowCore_1.36.3.tgz", repos = NULL, type = .Platform$pkgType)
Installing package into ‘/Users/dkim/Library/R/3.2/library’
(as ‘lib’ is unspecified)
> library(flowCore);
> library(flowStats); # error
Loading required package: flowWorkspace
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘flowUtils’
In addition: Warning messages:
1: package ‘flowStats’ was built under R version 3.3.0 
2: package ‘flowWorkspace’ was built under R version 3.2.3 
Error: package ‘flowWorkspace’ could not be loaded

**Comment by mikejiang** [comment]
Did you follow Bioconductor's installation procedure?
```r
source("https://bioconductor.org/biocLite.R")
biocLite("openCyto")
```
It should install `openCyto 1.8.4` and take care all the dependencies automatically.

**Comment by kdh4win4** [comment]
Sure I did it. Mike.
My R version is 3.2.3
the package 'rms' is not installed properly. is this an issue ?
last version flowStats are built in R 3.3.0
Do I have to install R 3.3.x ?

> source("http://bioconductor.org/biocLite.R")  
Bioconductor version 3.1 (BiocInstaller 1.18.5), ?biocLite for help
A newer version of Bioconductor is available for this version of R, ?BiocUpgrade for help
> library(flowStats); # error
Warning message:
package ‘flowStats’ was built under R version 3.3.0 


> source("http://bioconductor.org/biocLite.R")
Bioconductor version 3.1 (BiocInstaller 1.18.5), ?biocLite for help
A newer version of Bioconductor is available for this version of R, ?BiocUpgrade for help
> biocLite("openCyto") # nbiocLite("COMPASS") # not
BioC_mirror: http://bioconductor.org
Using Bioconductor version 3.1 (BiocInstaller 1.18.5), R version 3.2.2.
Installing package(s) ‘openCyto’
trying URL 'http://bioconductor.org/packages/3.1/bioc/bin/macosx/mavericks/contrib/3.2/openCyto_1.6.0.tgz'
Content type 'application/x-gzip' length 1222962 bytes (1.2 MB)
==================================================
downloaded 1.2 MB


The downloaded binary packages are in
	/var/folders/vq/q_7n5l9x7t57wgx2vxvv_sl00000gn/T//RtmpwfJXhm/downloaded_packages
Old packages: 'rms'
Update all/some/none? [a/s/n]: 
a

  There is a binary version available but the source version is later:
    binary source needs_compilation
rms  4.4-0  4.4-1              TRUE

Do you want to install from sources the package which needs compilation?
y/n: n
trying URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.2/rms_4.4-0.tgz'
Content type 'application/x-gzip' length 1058175 bytes (1.0 MB)
==================================================
downloaded 1.0 MB


The downloaded binary packages are in
	/var/folders/vq/q_7n5l9x7t57wgx2vxvv_sl00000gn/T//RtmpwfJXhm/downloaded_packages
>

**Comment by mikejiang** [comment]
Your `BiocInstaller` is too old and your `flowStats` is from development branch. 
First, remove all the related packages. and update `BiocInstaller` (`biocLite("BiocUpgrade")`) ) and then re-install `openCyto`

**Comment by kdh4win4** [comment]
I see. I will do that.

**Comment by kdh4win4** [comment]
It works. Thank you, Mike
