### ISSUE TITLE
clustering region between two peak area in flow cytometry data

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/openCyto#101]
I would like to sort middle area between two peak area(bright and dark).
In below manual gating plot;
CD56 bright and CD16 dim region. (8%)
How can I sort that using template(csv) file? 
I could not find any good way to sort this region yet. 
[Rplot03.pdf](https://github.com/RGLab/openCyto/files/70171/Rplot03.pdf)

**Comment by gfinak** [comment]
I'd suggest to come up with a data driven strategy using the basic
components of 1d or 2d mixture models (flowClust) and/or density based
gating and even ( if necessary) , fixed thresholds to define the region of
interest computationally, then wrap that strategy in a custom gating
routine that you plug in to openCyto, so you have a custom gate, that's
data driven, and returns the gate for a given sample.
Best,

Greg

**Comment by kdh4win4** [comment]
Do you mean that I need to use manual gating strategy a bit ? 
I have tried to use that strategy, however, I couldn't. 
Could you give me a hint how to "wrap the strategy in a custom gating routine that I previously plugged in to openCyto"  Mr. Finak ?

**Comment by gfinak** [comment]
Please have a look at the documentation for writing plugin gating routines
for openCyto. There are examples online from the BioConductor seminars last
year as well as on openCyto.org and on guthub.com/gfinak .
In a nutshell, you'll write a function that receives a flowFrame, it would
then extract the two markers you're interested in, you'd gate it in 1d or
2d to identify peaks, valleys, or clusters of cells and orient yourself
relative to those features, and use their locations to define the
boundaries of your region of interest, and return a gate object for that
sample.
That function gets registered with openCyto using the registerPlugins API,
so it can be used in the template.

Greg Finak

**Comment by kdh4win4** [comment]
I have read it and tried it during last two weeks. 
The goal is to catch the CD56 bright and CD16 dim

Some results I got so far are below. 
the template is;
[alias.docx](https://github.com/RGLab/openCyto/files/70260/alias.docx)

the previous manual gating is ;
[Rplot04_1.pdf](https://github.com/RGLab/openCyto/files/70261/Rplot04_1.pdf)

the autogating result with the template is;
[Rplot04_auto_1.pdf](https://github.com/RGLab/openCyto/files/70263/Rplot04_auto_1.pdf)

Any comment on my template is truly welcomed !. 
Thank you for your time. Mr. Finak

**Comment by gfinak** [comment]
Thanks, this is helpful to make it more concrete. I'll have a look when I
get a few minutes and see if I can come up with some suggestions.

Greg Finak

**Comment by kdh4win4** [comment]
Thank you. Mr. Finak

**Comment by kdh4win4** [comment]
Can I have any suggestion ?

**Comment by gfinak** [comment]
You could write a custom gating plugin that gates the CD16 and CD56 dimensions, and then condition on different subsets to identify precisely where to cut in order to draw that gate around the 8% population. 
For example after identifying CD56+ and CD56- using `mindensity`, you would further process the data within the gating routine to apply a `tailgate` to the right side of the CD56+ population, that should get you the left boundary, then you could process the CD56- subset and apply a `tailgate` to the left side of CD56- cells to get the right boundary. For the upper and lower boundaries, you could look at the CD56+/CD16+ cells and find the mode, then take the mode+/- 2 or 3 sds of the population to get the upper and lower boundary. Then construct a gate from those four sets of coordinates.
 
This would be a pretty special-purpose and specific gating routine, but depending on how your data looks  (if there isn't massive variability from sample to sample, for examples populations disappearing) then it might be sufficient.

**Comment by SamGG** [comment]
Thanks Greg for this nice tip. I am wondering if the right and left boundaries should apply to CD16 instead of CD56.

**Comment by kdh4win4** [comment]
Thank you so much, Mr. Greg Finak

Sincerely,
Dohoon Kim

2016. 1. 5. 오후 4:43 Greg Finak <notifications@github.com> 작성:

**Comment by SamGG** [comment]
Greg and Mike helped me solving a related question #102

**Comment by kdh4win4** [comment]
How do I set +/- 2 or 3 sd ?
I am afraid to say that I cound not find that in opencyto vignette.

**Comment by gfinak** [comment]
Can you clarify your question?

**Comment by kdh4win4** [comment]
[Rplot07_github.pdf](https://github.com/RGLab/openCyto/files/230311/Rplot07_github.pdf)
Hi, Dr. Finak
In the 5th figure, CD3-(parent), the 8% area is in "CD56_positive & CD16_**dim"** region . 
The target region is located in between CD16+ and CD16- area. 
After getting CD56+ region by mindensity method(I have done this), however, how to tailgating for CD16dim region is not that much clear to me.

**Comment by gfinak** [comment]
As I said before you will have to write a custom gating routine for this.  You cannot do this through the openCyto template directly without writing a gating plugin. There is no gating routine in openCyto that lets you say "threshold 2 SDs below the peak". You need to write this code.

**Comment by kdh4win4** [comment]
where can I get that information ?

**Comment by gfinak** [comment]
A very basic example is here: 
https://rstudio-pubs-static.s3.amazonaws.com/65921_14da9c6acdfd4966b43f8e02e8d67b94.html

You need to write a wrapper around your custom routine. The wrapper has to match the expected function signature (see the example in the link above). The output would be a gate. The routine would munge and process the data as needed to identify all the relevant cutpoints. In the example above, it's just using simple tailgate applied to a control sample that then gets used to gate non-control samples. For your use case, you replace the tailgate in the wrapper with your own routine.

**Comment by kdh4win4** [comment]
Dear Greg
I will do that right now. 
I appreciate it.
