### ISSUE TITLE
3 peaks, another flavor of "between two peaks"

### ISSUE THREAD

**Issue by SamGG** [RGLab/openCyto#102]
Hi,
I got three nice peaks on the same axis. I solved their delineation using the following gating strategy. Let me know for alternative/better solutions.
Currently I can't display the intermediate gate because it is a boolean gate.

```
alias	pop	parent	dims	gating_method	gating_args	collapseDataForGating	groupBy	preprocessing_method	preprocessing_args
*	CD56+/-CD16+/-	root	CD56,CD16	mindensity					
*	CD33+/-	CD56-CD16-	CD33	mindensity	gate_range=c(3,6)				
*	CD33+/-	CD56-CD16-/CD33-	CD33	mindensity	gate_range=c(0,2)				
CD33hi	CD33+	CD56-CD16-	CD33	refGate	CD56-CD16-/CD33+				
CD33lo	CD33-	CD56-CD16-	CD33	refGate	CD56-CD16-/CD33-/CD33-				
CD33int	CD33	CD56-CD16-	CD33	boolGate	!CD33lo&!CD33hi				
```

![cd33lo](https://cloud.githubusercontent.com/assets/3333348/12435266/bd3e8f30-bf0c-11e5-8abb-388cbed6bccb.png)
![cd33hi](https://cloud.githubusercontent.com/assets/3333348/12435267/c1940934-bf0c-11e5-98ae-ba6a5e21971f.png)

**Comment by gfinak** [comment]
`plotGate` should plot boolean gates, you may need to pass `bool=TRUE` to `plotGate`.

**Comment by SamGG** [comment]
Thanks for the tip. It applies also to the gating set.
To be noticed, the plotGate takes place in the dimensions of the parent, ie (CD56, CD16), whereas for the hi and lo gates, the plotGate takes place in the gating dimensions, ie (CD33, SSC-A). Thus, I end up with xyplot to verifiy the result. Although I set CD33 as the dimension when specifying the boolean gate in the CSV file, this seems to have no effect on the plot.

**Comment by gfinak** [comment]
I believe the `projection` argument may be used to change that.

**Comment by mikejiang** [comment]
`projections` argument is currently dedicated to `plotGate` method for `GatingHierarchy`, if you want to overwrite the default `x,y` display for `GatingSet`, use `formula` argument. (which is what `projections` are eventually converted to)

**Comment by SamGG** [comment]
In fact, both calls lead to a similar result. It depends on the object that is selected to be displayed. But projections works with GatingHierarchy, and formula works with GatingSet. With GatingSet, the parent population disappears as many flow frames will be displayed (I guess; here my flowset is made of only one flowframe).

```r
plotGate(gs[[1]], "CD33lo", margin=F)
plotGate(gs[[1]], "CD33hi", margin=F)
plotGate(gs[[1]], "CD33int", bool = TRUE, margin=F, projections = list("CD33int" = c(x = "CD33", y = "SSC-A")))
class(gs[[1]])
[1] "GatingHierarchy"
attr(,"package")
[1] "flowWorkspace"
```
![cd33_gh_proj](https://cloud.githubusercontent.com/assets/3333348/12461927/cb38b1e2-bfbb-11e5-81b1-957622f4527f.png)

```r
plotGate(gs, "CD33lo", margin=F)
plotGate(gs, "CD33hi", margin=F)
plotGate(gs, "CD33int", bool = TRUE, margin=F, formula = `SSC-A` ~ CD33)
class(gs)
[1] "GatingSet"
attr(,"package")
[1] "flowWorkspace"
```
![cd33int_gs](https://cloud.githubusercontent.com/assets/3333348/12461999/2479492e-bfbc-11e5-835a-2c96fb1e3b9f.png)

**Comment by SamGG** [comment]
For me, it's perfect. Hope the figures could help someone else.

Unless you think of a better way to split those 3 populations on that CD33 dimension, you can close the issue. Thanks.
