### ISSUE TITLE
getPopStats: any difference between statistic="count" vs statistic="freq"

### ISSUE THREAD

**Issue by SamGG** [RGLab/openCyto#103]
Hi,
I got the exact same output in both cases.

By the way, as a non-native english, I still don't understand what frequency really means: percentage, count... For example, here is an extract from the hist function:

> freq  logical; if TRUE, the histogram graphic is a representation of frequencies, the counts component of the result; if FALSE, probability densities, component density, are plotted (so that the histogram has a total area of one). Defaults to TRUE if and only if breaks are equidistant (and probability is not specified).

IMHO, percentage is clear... although the top could be 100 or 1.

```
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

openCyto_1.8.4
```

**Comment by mikejiang** [comment]
This argument is only relevant to `GatingSet` object, for `GatingHierarchy`, both `count` and `freq` are returned always. `freq` is the proportion of the current cell population in the parent population.

**Comment by SamGG** [comment]
Thanks for your answer. In my hand, it does not work.
```r
> class(gs)
[1] "GatingSet"
attr(,"package")
[1] "flowWorkspace"
> getPopStats(gs)
          name       Population           Parent Count ParentCount
 1: Cell_A.fcs            CD16+             root 45836      101597
 2: Cell_A.fcs            CD56+             root 44860      101597
 3: Cell_A.fcs       CD56-CD16-             root 50175      101597
 4: Cell_A.fcs CD56-CD16-/CD33+       CD56-CD16- 27483       50175
...
27: Cell_A.fcs       CD14+CD33+       CD56-CD16+  2319        6562
28: Cell_A.fcs       CD56+CD16+             root 39274      101597
          name       Population           Parent Count ParentCount
> getPopStats(gs,statistic="count")
          name       Population           Parent Count ParentCount
 1: Cell_A.fcs            CD16+             root 45836      101597
 2: Cell_A.fcs            CD56+             root 44860      101597
 3: Cell_A.fcs       CD56-CD16-             root 50175      101597
 4: Cell_A.fcs CD56-CD16-/CD33+       CD56-CD16- 27483       50175
...
27: Cell_A.fcs       CD14+CD33+       CD56-CD16+  2319        6562
28: Cell_A.fcs       CD56+CD16+             root 39274      101597
          name       Population           Parent Count ParentCount
> getPopStats(gs,statistic="freq")
          name       Population           Parent Count ParentCount
 1: Cell_A.fcs            CD16+             root 45836      101597
 2: Cell_A.fcs            CD56+             root 44860      101597
 3: Cell_A.fcs       CD56-CD16-             root 50175      101597
 4: Cell_A.fcs CD56-CD16-/CD33+       CD56-CD16- 27483       50175
...
27: Cell_A.fcs       CD14+CD33+       CD56-CD16+  2319        6562
28: Cell_A.fcs       CD56+CD16+             root 39274      101597
          name       Population           Parent Count ParentCount
```

**Comment by mikejiang** [comment]
Sorry,  it is only valid when `format` is "wide" according to the [doc](https://github.com/RGLab/flowWorkspace/blob/trunk/man/getPopStats.Rd#L39). 
`wide` is the legacy format and exists for the backward-compatible purpose. Maybe I should deprecate these to avoid confusion, @gfinak ?

**Comment by gfinak** [comment]
I think that’s a good idea.

**Comment by SamGG** [comment]
Sorry, there a crucial point I overlooked. My gs object is a GatingSet. So, with a GatingSet, the doc is OK concerning the use of freq and count. The format might be misleadig when there is only one flowframe as in my case, but it is correct: flow frames are organized in columns leading to a "wide" format.
```r
> getPopStats(gs, statistic="freq", format = "wide")
                   Cell_A.fcs
BDCA1+           1.0000000000
CD123+           0.3601488692
CD123+BDCA1+     0.3601488692
...
CD56-CD16-/CD33+ 0.5477428999
CD56-CD16-/CD33- 0.4522571001
root             1.0000000000
> getPopStats(gs, statistic="count", format = "wide")
                 Cell_A.fcs
BDCA1+                 3493
CD123+                 1258
CD123+BDCA1+           1258
...
CD56-CD16-/CD14+      24578
CD56-CD16-/CD33+      27483
CD56-CD16-/CD33-      22692
root                 101597
```
The order of the populations is not the same as in the previous/default format, that seems to be the "long" format. Moreover the frequencies refer to the parent population, as stated in the doc. As this may be surprising (there are more than one 1.00, ie 100%), I think it should be warned.

When getPropStats is called with a GatingHierarchy object, gs[[1]], whatever the statistic and format options are set, the output is always a data frame with the following columns: flowCore.freq flowJo.freq flowJo.count flowCore.count node. I am not sure this case is stated in the doc.

```r
 getPopStats(gs[[1]], statistic="count", format = "wide")
    flowCore.freq flowJo.freq flowJo.count flowCore.count             node
 1:  1.0000000000          NA           NA         101597             root
 2:  0.4511550538          NA           NA          45836            CD16+
 3:  0.4415484709          NA           NA          44860            CD56+
 4:  0.4938630078          NA           NA          50175       CD56-CD16-
...
29:  0.3865665325          NA           NA          39274       CD56+CD16+
    flowCore.freq flowJo.freq flowJo.count flowCore.count             node
```
I don't know what you really expected, but make your own trials before changing anything. IMHO, it's finally OK. I will stay finally on the raw counts given by the simple call `r getPopStats(gs)`, but the wide format using count is also nice. May be the most important points would be to make the doc clearer and to forbid the use of options when they have no effect.

**Comment by anaraserikbek** [comment]
I was wondering if there is a way to get population statistics but not in the format of % of negative/positive cells (the same percentages that are displayed when plotGate()) ?
