### ISSUE TITLE
Can't register native flowDensity function

### ISSUE THREAD

**Issue by SamGG** [RGLab/openCyto#104]
Hi,
I didn't succeed in registering the default .flowDensity function.
```r
> registerPlugins(fun = .flowDensity, methodName = "flowDensity", dep = "flowDensity", "gating")
Formals of function don't match expected template: 
function(fr, pp_res, channels, ...)
[1] FALSE
Warning message:
In registerPlugins(fun = .flowDensity, methodName = "flowDensity",  :
  Can't register function
```
It seems that the arguments changed. My patch is the following, although I didn't succeed in making it run.
```r
.flowDensitY = function(fr, pp_res, channels=NA, filterId="",...) { .flowDensity(fr, pp_res, xChannel = channels[1], yChannel = channels[2], filterId=filterId, ...) }
registerPlugins(fun = .flowDensitY, methodName = "flowDensitY", dep = "flowDensity", "gating")
```
Let me know if there is a better solution, please, could you give me an example of use.

```
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
other attached packages:
 [1] IDPmisc_1.1.17            flowDensity_1.4.0        
 [3] Rgraphviz_2.14.0          graph_1.48.0             
 [5] openCyto_1.8.4 
```

**Comment by mikejiang** [comment]
The wrapper function in `flowDensity` package is out of date. try [this patch](https://github.com/RGLab/openCyto/files/96790/patch.diff.zip) to your local copy of `flowDensity`

**Comment by gfinak** [comment]
I've forwarded the patch to the maintainer of flowDensity as well.

**Comment by SamGG** [comment]
Thanks for your attention. Under Windows, I don't know how to apply your patch, but I think my current workaround should work. I will try to use flowDensity thru openCyto.
Best.

**Comment by mikejiang** [comment]
Right, basically you load the patched `.flowDensity` wrapper function into your global environment and register it.

**Comment by SamGG** [comment]
Not possible, because the wrapper calls .flowDensity.2d that is not exported. Never mind, I hope to give the right parameter to test flowDensity.

**Comment by mikejiang** [comment]
Prefix by `flowDensity:::` will do

```r
.flowDensity <- function(fr, pp_res, channels = NA, ...){
  
  if(length(channels)==2)
    flowWorkspace:::.flowDensity.2d(fr, channels = channels, ...)
  else
    flowWorkspace:::.flowDensity.1d(fr, channel = channels, ...)
  
}
```

**Comment by SamGG** [comment]
Thanks. The wrapper is now registered. But I have got another error, that seems to be related to the gating of single channels that have been expanded from the CSV file
```
alias	pop	parent	dims	gating_method	gating_args	collapseDataForGating	groupBy	preprocessing_method	preprocessing_args
CD56+CD16-	CD56+CD16-	root	CD56,CD16	flowDensity	position=c(TRUE,FALSE),upper = TRUE				
```
But that definition involves only one population in a bi-plot.
```r
> .flowDensity <- function(fr, pp_res, channels = NA, ...){
+   
+   if(length(channels)==2)
+     flowDensity:::.flowDensity.2d(fr, channels = channels, ...)
+   else
+     flowDensity:::.flowDensity.1d(fr, channel = channels, ...)
+   
+ }
> registerPlugins(fun = .flowDensity, methodName = "flowDensity", dep = "flowDensity", "gating")
Registered flowDensity
[1] TRUE
> gt <- gatingTemplate("gs1_4_flowdensity.csv")
Adding population:CD56+
Adding population:CD16+
Adding population:CD56+CD16-
> plot(gt)
Warning message:
In brewer.pal(nMethods, name = "Dark2") :
  minimal value for n is 3, returning requested palette with 3 different levels

> gs <- GatingSet(fs4)
.done!
> gg <- gating(gt, gs)
Gating for 'CD16+'
Error in (function (fs, pp_res, gFunc, popAlias, channels, gFunc_args)  : 
  failed at Cell_A.fcs
Error in flowDensity::deGate(flow.frame = fr, channel = channel, ...) : 
  unused argument (position = c(TRUE, FALSE))
>
```

**Comment by mikejiang** [comment]
According to your template, you are trying to do `1d` gate with `flowDensity` on both `CD56` and `CD16` and then construct a `rectangleGate` (the`+-` quadrant) based on these `1d` gates. 

So the `openCyto` automatically dispatches to `.flowDensity.1d`. But you are passing `position` argument that is dedicated for `flowDensity.2d` function. 

Try to read `?flowDensity` to understand how it works.

**Comment by SamGG** [comment]
First I used flowDensity in order to determine the arguments, position and upper. Then I tried to inject them into opebCyto. Could you tell me please why openCyto think about two 1d instead of a 2d? The number of channels is 2 (dims columns), so the wrapper should call the 2d function. What did I do wrong?

**Comment by mikejiang** [comment]
That's because of the `pop` pattern you specified. Again, please read docs carefully, I think it is pretty clearly described in the package vignette. http://www.bioconductor.org/packages/2.14/bioc/vignettes/openCyto/inst/doc/HowToWriteCSVTemplate.html

**Comment by SamGG** [comment]
Thanks for the pointer. You are right, it is an invaluable resource. I think the current release http://www.bioconductor.org/packages/release/bioc/vignettes/openCyto/inst/doc/HowToWriteCSVTemplate.html is better formatted.

I started by the opencyto.org site in which this link is not indexed. I think this link should appear in the Getting started section of the opencyto.org site and in the template section of the opencyto vignette. These were the two places I look at until now, so I didn't see that clear information.

I modified the CSV therefore:
```
alias,pop,parent,dims,gating_method,gating_args,collapseDataForGating,groupBy,preprocessing_method,preprocessing_args
a,*,root,"CD56,CD16",flowDensity,"position=c(TRUE,FALSE),upper = TRUE",,,,
myCD56-CD16-,*,root,"CD56,CD16",flowDensity,"position=c(FALSE,FALSE)",,,,
```
But I still get this error now, whatever I put in the alias field.
```r
> gt <- gatingTemplate("gs1_4_flowdensity.csv")
Error in .preprocess_csv(dt, strict = strict) : ais duplicated!
```

**Comment by SamGG** [comment]
If I am right, I should fill alias with the name of the population resulting from the gate and pop with *. From the code, when pop is * and alias is not *, then .gen_dummy_ref_gate is called in order to generate a dummy row that has the same alias as the original. Because alias is then checked for duplicated alias, an error is raised.

**Comment by mikejiang** [comment]
If you want to use `flowDensity` to automatically gate out a `2d` rectangleGate, `pop` should be in the format of `A+` or simply `A`

|    alias   | pop | parent | dims      | gating_method | gating_args                         |
|:----------:|-----|--------|-----------|---------------|-------------------------------------|
| 56-16- | A+  | root   | 56,16 | flowDensity   | position=c(TRUE,FALSE),upper = TRUE |

If you want to use `flowDensity`for `1d` gating and construct a `2d` rectangleGate by combining these two `1d` gate, then you should set `pop` in the format of `A-B-`


|    alias   | pop | parent | dims      | gating_method | gating_args                         |
|:----------:|-----|--------|-----------|---------------|-------------------------------------|
| 56-16- | 56-16-  | root   | 56,16 | flowDensity   | positive = TRUE |
