### ISSUE TITLE
write a separate vignette to demonstrate the usages of the different gating methods

### ISSUE THREAD

**Issue by mikejiang** [RGLab/openCyto#107]
requested by @anaraserikbek at  https://github.com/RGLab/openCyto/issues/67#issuecomment-217880995

**Comment by mikejiang** [comment]
@anaraserikbek, check [this](https://github.com/RGLab/openCyto/blob/trunk/vignettes/HowToAutoGating.md) out. And I will be adding more gating examples to it.

**Comment by anaraserikbek** [comment]
Thank you Mike for the following vignette! it's very helpful!
