### ISSUE TITLE
Using one flowJo workspace to gate many .FCS files 

### ISSUE THREAD

**Issue by anaraserikbek** [RGLab/openCyto#108]
Hello everyone,
I am trying to use one flowJo workspace .XML file to apply it to many .FCS files (that were acquired with the same parameters). However, R (I'm using openCyto package) seems to need more a separate workspace for each .FCS file to do the gating. So, I was wondering wehn R reads the workspace, what parameters exactly does it extract for gating and can we possible use the same workspace to gate several .fcs data that was acaquired with exact same parameters? 
Thank you in advance,

**Comment by mikejiang** [comment]
If your FCS files have the same parameters and you want to simply apply the same static gates to all the files:
```r
library(flowWorkspace)
dataDir <- system.file("extdata",package="flowWorkspaceData")
#parse the workspace for one example as the template
ws <- openWorkspace(file.path(dataDir, "manual.xml"))
gs_tmp <- parseWorkspace(ws, name = 4, subset = 1)
#get the GatingHierarchy object
gh <- gs_tmp[[1]]

#select fcs filenames
fcsfiles <- basename(list.files(pattern = "Cyto.*.fcs", dataDir, full = T))

#apply the gates defined in gh to fcs files
gs <- GatingSet(gh, fcsfiles, path = dataDir, isNcdf = TRUE)
```
If you are talking about extracting the gating scheme from the workspace and generate the `csv` gating template with the appropriate `automated` gating algorithm automatically determined for each gate/population, then it is different from [what you previously mentioned](https://github.com/RGLab/flowWorkspace/issues/197), and it is not yet available.

**Comment by anaraserikbek** [comment]
Thank you. Yes, I did really mean that -- "... extracting the gating scheme from the workspace and generate the csv gating template with the appropriate automated gating algorithm automatically determined for each gate/population..." 
However, by "simply apply the same **static gates** to all the files", you mean by static gates that the location of the gates will be the same in all the .fcs files where i would apply the gating derived from 1 wflowJo workspace?

**Comment by gfinak** [comment]
> "... extracting the gating scheme from the workspace and generate the csv gating template with the 
> appropriate automated gating algorithm automatically determined for each gate/population..." 

@anaraserikbek  This is on our radar.  Not implemented yet.

**Comment by mikejiang** [comment]
@anaraserikbek , yes, that's what I meant.
