### ISSUE TITLE
importing the gating workspace from flowJo as .xml file in order to work in flowSOM

### ISSUE THREAD

**Issue by anaraserikbek** [RGLab/openCyto#109]
i need to export/read a gatign template from my .xml file. 
However, each time I get the following error: 
**Error in parseGatingML(xmlRoot(smartTreeParse(file, ...)), flowEnv) : 
  Not a supported Gating-ML XML format**
I've tried several ways:
- get the XML code from flowJo & saving it through a text document as .xml file 
- importing it as .wsp file and opening it through R 

I would appreciate any help. 
Thank you 
I've attached a .txt version of my file in here. 
[fullgate.txt](https://github.com/RGLab/openCyto/files/274656/fullgate.txt)

**Comment by mikejiang** [comment]
I can't tell what you were trying to do without seeing the complete error messages from `traceback()`.
However your attached workspace does seem to miss some `namespace definition` that is necessary for parsing. See RGLab/flowWorkspace#194 for the details and solution
