### ISSUE TITLE
Using nonDebris+ & DebrisGate+ 

### ISSUE THREAD

**Issue by anaraserikbek** [RGLab/openCyto#111]
Hi, 
While using the nonDebris+ gate, I have the following error for both. 
**Error: number of cluster centres must lie between 1 and nrow(x)** 
when traceback() this error: 

> traceback()
> 17: stop("number of cluster centres must lie between 1 and nrow(x)", 
>          call. = FALSE)
> 16: do_one(nmeth)
> 15: kmeans(x = peaks_collapsed, centers = K, nstart = 10)
> 14: .prior_flowClust1d(flow_set = flow_set, channel = channels, K = K, 
>                        nu0 = nu0, w0 = w0[1], ...)
> 13: prior_flowClust(flow_set = prior_data, channels = c(xChannel, 
>                                                         yChannel), K = K, ...)
> 12: FUN(X[[i]], ...)
> 11: lapply(X = fslist, FUN = .prior_flowClust, channel = "FSC-A", 
>            gs = <S4 object of class "GatingSet">, gm = <S4 object of class "gtMethod">, 
>            groupBy = "", isCollapse = FALSE, K = 2)
> 10: lapply(X = fslist, FUN = .prior_flowClust, channel = "FSC-A", 
>            gs = <S4 object of class "GatingSet">, gm = <S4 object of class "gtMethod">, 
>            groupBy = "", isCollapse = FALSE, K = 2)
> 9: eval(expr, envir, enclos)
> 8: eval(thisCall)
> 7: .preprocessing(x, y, ...)
> 6: preprocessing(x = this_ppm, y, parent = parent, gtPop = gt_node_pop, 
>                  gm = this_gate, ...)
> 5: preprocessing(x = this_ppm, y, parent = parent, gtPop = gt_node_pop, 
>                  gm = this_gate, ...)
> 4: .gating_gatingTemplate(x, y, env_fct, ...)
> 3: .local(x, y, ...)
> 2: gating(gt_tcell, gs)
> 1: gating(gt_tcell, gs)

**Comment by gfinak** [comment]
Could you post code please

**Comment by anaraserikbek** [comment]
The gating template I used was as follows (from my created .csv file):

**alias	pop	parent	dims	gating_method	gating_args	collapseDataForGating	groupBy	preprocessing_method	preprocessing_args
nonDebris	nonDebris+	viable	FSC-A	DebrisGate**

And the code that i've used:
**template=system.file("extdata/gating_template/template.csv",package="openCyto")
template=fread(template)
tregMAIT=gatingTemplate(template, autostart = 1L)

gating(tregMAIT,gs)
plotGate(gs[[1]])****

**Comment by mikejiang** [comment]
What is the your definition of `DebrisGate`? And I don't think `openCyto` package has `template.csv` as you posted.
