### ISSUE TITLE
possibility of importing polygon gates

### ISSUE THREAD

**Issue by anaraserikbek** [RGLab/openCyto#112]
Hi, 
I have a gating issue to reproduce the following several flowJo manual gates on 2D plot. I have included the image of the flowJo gates to this post. I've tried flowClust & flowDensity 2D, however the I receive an error that says too many clusters centers are on the spot. Which makes sense, looking at the Treq gate (representing 10% gate), which cannot be specified in the pop field by defining marker intensity. 
Is there a way/algorithm to reproduce those manual gates in such case? 
(a Plugin function is also an option, if there's a need)
![polygon_gate_question](https://cloud.githubusercontent.com/assets/19268148/15648976/3ab66e7e-266e-11e6-81b0-645836fd6d3c.png)
Thank you

**Comment by gfinak** [comment]
Yes the best option here would be a plugin custom gating routine.

Greg Finak

**Comment by anaraserikbek** [comment]
I've found that it's possible to make polygonGate through flowCore package, specifying the vertices of the polygon through coordinates as a matrix. However, in this case, the gate location would be fixed, which makes it to use for automated analysis to apply to many .fcs files. Is there other algorithms? Would flowClust be able to find those 3 clusters as the 3 biggest populations?
