### ISSUE TITLE
algorithm incorporated in openCyto that would identify several clusters in 2D data 

### ISSUE THREAD

**Issue by anaraserikbek** [RGLab/openCyto#113]
Hello,
are there any gating algorithms/methods that would (just like in leukocyte gates with K-clustering) would gate several populations at once in 2D. I mean, K-clustering in leukocyte gate identifies several clusters, if you specify the number. However, it only gates for one population. How to make the algorithm to gate several populations/clusters & display 2 or 3 ellipsoidal populations? 

thank you,

**Comment by SamGG** [comment]
Hi,
It's possible to use flowClust in a final node.
Best.

**Comment by mikejiang** [comment]
Basically you need to define a `gating` function that returns either `m` or `filters` object instead of conventional single `filter`. `openCyto::quadGate.tmix` is one example that uses `filters`.
See [here](http://rpubs.com/wjiang2/188182) for the detailed examples of both approaches. You can choose `flowClust` (not `flowClust.1d` or `flowClust.2d` in `openCyto` package) as the actual clustering engine and write your own `plugin` wrapper function around that.

Also [here](https://github.com/RGLab/openCyto/issues/73#issuecomment-48972826) is related issue.

**Comment by anaraserikbek** [comment]
I've found it'd be better to use mclust in this case for me. But, I need to perform the clustering on already pre-gated data. So, how could I save the data that was already gated and is a result of several gates (gated using .csv gating template)?

**Comment by SamGG** [comment]
Mike will answer better than I do, but in the mean time this could help you. Basically, curv2gate is the name he gave to the new function/plugin he defined in the example. I think there is another recent discussion concerning building plugin, but I don't remember it. Mike will certainly do.

**Comment by anaraserikbek** [comment]
Thank you SamGG. This is helpful. However, I have several questions for using both curv2gate & curv2gate_geom methods. 

1) what clustering algorithm (mathematically) does curv2gate & curv2gate_geom use? (I read that they make logicalGate, like booleanGate, but does that mean it will just use a density approach for accessing +/- of markers?) Also, i looked at the function code in github where you added curv2gate, and there're rectangle and quadrant gates. 

2-1) can curv2gate & curv2gate_geom make not hard +/- distinctions but rather identify population clusters that have overlapping expressions? (like GMM/mclust function?) I've tried to use mclust on my data & it worked well, identifying the clusters i needed. However, to do that only for 1 patient, i had to preliminarily gate on flowJo-->extract the .csv-->use it as a matrix in R for generation of GMM for my markers of interest. And since i have over 100 patients, if i could add this mclust algorithm into the .csv template,or, if curv2gate & curv2gate_geom work similarly, could use them instead of mclust. But, the problem with mclust is also it took 7-10 mins for processing 15000 cells(1 patient). I wonder if you can advice something that could be more efficient to use as a plugin function in creating the .csv template? 

2-2)How & where can you specify the number of clusters you want to get through curv2gate_geom?

3) I had a problem when using both curv2gate & curv2gate_geom. 
When using curv2gate, I received the following error:  
 **_**Error in ovalues[, 1] : incorrect number of dimensions**_** 
when I use the following code to gate my data: 
**alias = "*",pop = "*",dims = "CD25,CD127",gating_method ="curv2gate",bwFac=5,parent = "CD4+CD8b-"** 

And when I do a **traceback()**, I receive the following:

> **_**16: stop("failed at ", paste0(sn), "\n", filterRes)
> 15: (function (fs, pp_res, gFunc, popAlias, channels, gFunc_args) 
>     {
>         require(openCyto)
>         sn <- sampleNames(fs)
>         fr <- as(fs, "flowFrame")
>         total <- nrow(fr)
>         subSample <- gFunc_args[["subSample"]]
>         gFunc_args[["subSample"]] <- NULL
>         if (!is.null(subSample)) {
>             if (is.numeric(subSample)) {
>                 if (subSample > 1) {
>                     samp.ind <- sample.int(total, subSample)
>                     fr <- fr[samp.ind]
>                 }
>                 else if (subSample > 0) {
>                     samp.ind <- sample.int(total, subSample * total)
>                     fr <- fr[samp.ind]
>                 }
>                 else stop("invalid 'subSample' argument: ", subSample)
>             }
>             else stop("invalid 'subSample' argument: ", subSample)
>         }
>         openCyto.options <- getOption("openCyto")
>         minEvents <- openCyto.options[["gating"]][["minEvents"]]
>         if (is.null(minEvents)) 
>             minEvents <- 0
>         if (nrow(fr) <= minEvents) {
>             warning(paste(sn, collapse = ","), ": Not enough events to proceed the data-driven gating!Returning a dummy gate instead.")
>             channels <- as.vector(na.omit(channels))
>             nDim <- length(channels)
>             if (nDim == 1) 
>                 gate_coordinates <- list(c(-Inf, -Inf))
>             else if (nDim == 2) 
>                 gate_coordinates <- list(c(-Inf, -Inf), c(-Inf, -Inf))
>             else stop(nDim, " dimensional gating is not supported yet!")
>             names(gate_coordinates) <- channels
>             filterRes <- rectangleGate(gate_coordinates)
>             if (grepl("flowClust\\.[12]d", gFunc)) 
>                 filterRes <- fcRectangleGate(filterRes, priors = list(), 
>                     posts = list())
>             nPop <- length(popAlias)
>             filterResType <- ifelse(nPop == 1, "filter", "filters")
>             if (filterResType == "filters") {
>                 filterRes <- filters(lapply(1:nPop, function(i) filterRes))
>             }
>         }
>         else {
>             if (!.isRegistered(gFunc)) {
>                 stop(sprintf("Can't gate using unregistered method %s", 
>                     gFunc))
>             }
>             thisCall <- substitute(f(fr = fr, pp_res = pp_res, channels = channels), 
>                 list(f = as.symbol(gFunc)))
>             filterRes <- try(do.call(gFunc, c(list(fr = fr, pp_res = pp_res, 
>                 channels = channels), gFunc_args)), silent = TRUE)
>         }
>         if (extends(class(filterRes), "filter") || extends(class(filterRes), 
>             "filters")) {
>             list(sapply(sampleNames(fs), function(i) filterRes, simplify = FALSE))
>         }
>         else {
>             stop("failed at ", paste0(sn), "\n", filterRes)
>         }
>     })(dots[[1L]][[7L]], dots[[2L]][[7L]], gFunc = ".curv2gate", 
>         popAlias = "*", channels = c("Green-E-582/15-A", "Violet-C-670/30-A"
>         ), gFunc_args = list())
> 14: mapply(list(`Alcina TregMAIT_AV 10-1974 P1.fcs` = <S4 object of class "flowSet">, 
>         `Alcina TregMAIT_BV 08-1966.fcs` = <S4 object of class "flowSet">, 
>         `Alcina TregMAIT_CM 06-1955.fcs` = <S4 object of class "flowSet">, 
>         `Alcina TregMAIT_GG 08-1951.fcs` = <S4 object of class "flowSet">, 
>         `Alcina TregMAIT_LM 04-1938 P1.fcs` = <S4 object of class "flowSet">, 
>         `Alcina TregMAIT_RM 01-1951.fcs` = <S4 object of class "flowSet">, 
>         `Alcina TregMAIT_TA 09-1949 P1.fcs` = <S4 object of class "flowSet">), 
>         list(`Alcina TregMAIT_AV 10-1974 P1.fcs` = NULL, `Alcina TregMAIT_BV 08-1966.fcs` = NULL, 
>             `Alcina TregMAIT_CM 06-1955.fcs` = NULL, `Alcina TregMAIT_GG 08-1951.fcs` = NULL, 
>             `Alcina TregMAIT_LM 04-1938 P1.fcs` = NULL, `Alcina TregMAIT_RM 01-1951.fcs` = NULL, 
>             `Alcina TregMAIT_TA 09-1949 P1.fcs` = NULL), FUN = .gating_adaptor, 
>         MoreArgs = list(gFunc = ".curv2gate", popAlias = "*", channels = c("Green-E-582/15-A", 
>         "Violet-C-670/30-A"), gFunc_args = list()))
> 13: eval(expr, envir, enclos)
> 12: eval(thisCall)
> 11: .gating_gtMethod(x, y, ...)
> 10: gating(x = this_gate, y, parent = parent, gtPop = gt_node_pop, 
>         pp_res = pp_res, ...)
> 9: gating(x = this_gate, y, parent = parent, gtPop = gt_node_pop, 
>        pp_res = pp_res, ...)
> 8: .gating_gatingTemplate(x, y, env_fct, ...)
> 7: .local(x, y, ...)
> 6: gating(gt, gs, ...)
> 5: gating(gt, gs, ...)
> 4: withCallingHandlers(expr, message = function(c) invokeRestart("muffleMessage"))
> 3: suppressMessages(gating(gt, gs, ...))
> 2: add_pop(gs, alias = "*", pop = "*", dims = "CD25,CD127", gating_method = "curv2gate", 
>        bwFac = 5, parent = "CD4+CD8b-")
> 1: rbind(template, add_pop(gs, alias = "*", pop = "*", dims = "CD25,CD127", 
>        gating_method = "curv2gate", bwFac = 5, parent = "CD4+CD8b-"))**_**
> 


4. When I use the curv2gate_geom, I receive the following error, even though  I tried 1, 2, 3, 4,5,6 number in the alias names column and the error I keep receiving is: 
  **_number of population names (given by 'name' argument) does not agree with the number of filter objects in 'filters'!_**
  When I do traceback() I receive the following: 
```
  20: stop("number of population names (given by 'name' argument) does not agree with the number of filter objects in 'filters'!")
19: .local(wf, action, ...)
18: add(wf = gh, action = curFilter, ...)
17: add(wf = gh, action = curFilter, ...)
16: FUN(X[[i]], ...)
15: lapply(samples, function(sample) {
  curFilter <- action[[sample]]
  gh <- wf[[sample]]
  add(wf = gh, action = curFilter, ...)
})
14: lapply(samples, function(sample) {
  curFilter <- action[[sample]]
  gh <- wf[[sample]]
  add(wf = gh, action = curFilter, ...)
})
13: .local(wf, action, ...)
12: selectMethod("add", signature = c(wf = "GatingSet", action = "filterList"))(wf, 
                                                                                action, ...)
11: add(wf, flist, ...)
10: add(wf, flist, ...)
9: add(y, flist, parent = parent, name = popAlias, validityCheck = FALSE, 
       recompute = TRUE)
8: add(y, flist, parent = parent, name = popAlias, validityCheck = FALSE, 
       recompute = TRUE)
7: .gating_gtMethod(x, y, ...)
6: gating(x = this_gate, y, parent = parent, gtPop = gt_node_pop, 
          pp_res = pp_res, ...)
5: gating(x = this_gate, y, parent = parent, gtPop = gt_node_pop, 
          pp_res = pp_res, ...)
4: .gating_gatingTemplate(x, y, env_fct, ...)
3: .local(x, y, ...)
2: gating(gt_tcell, gs)
1: gating(gt_tcell, gs) 

```
--- And if I try alias=* & pop=*, i get:
  ****_Error in add(y, flist, parent = parent, name = popAlias, validityCheck = FALSE,  : 
                 the gate list doesn't constain valid 'filter', 'filters' or 'filterResult' objects!_**** 

**P.S. I would like to ask if I'm asking very basic questions here & if there're other online reading materials you can suggest for me? Great one would be if you have deeper information i could read in building/registering a function as a plugin to use in the .csv gating template?**

**Comment by anaraserikbek** [comment]
Thank you Sam. This is helpful. However, I have several questions for using both curv2gate & curv2gate_geom methods. 

**1)** what clustering algorithm (mathematically) does curv2gate & curv2gate_geom use? (I read that they make logicalGate, like booleanGate, but does that mean it will just use a density approach for accessing +/- of markers?) Also, i looked at the function code in github where you added curv2gate, and there're rectangle and quadrant gates. 

**2-1)** can curv2gate & curv2gate_geom make not hard +/- distinctions but rather identify population clusters that have overlapping expressions? (like GMM/mclust function?) I've tried to use mclust on my data & it worked well, identifying the clusters i needed. However, to do that only for 1 patient, i had to preliminarily gate on flowJo-->extract the .csv-->use it as a matrix in R for generation of GMM for my markers of interest. And since i have over 100 patients, if i could add this mclust algorithm into the .csv template,or, if curv2gate & curv2gate_geom work similarly, could use them instead of mclust. But, the problem with mclust is also it took 7-10 mins for processing 15000 cells(1 patient). I wonder if you can advice something that could be more efficient to use as a plugin function in creating the .csv template? 

**2-2)**How & where can you specify the number of clusters you want to get through curv2gate_geom?

**3)** I had a problem when using both curv2gate & curv2gate_geom. 
When using curv2gate, I received the following error:  
 **_**Error in ovalues[, 1] : incorrect number of dimensions**_** 
when I use the following code to gate my data: 
**alias = "*",pop = "*",dims = "CD25,CD127",gating_method ="curv2gate",bwFac=5,parent = "CD4+CD8b-"** 

And when I do a **traceback()**, I receive the following:

> **_**16: stop("failed at ", paste0(sn), "\n", filterRes)
> 15: (function (fs, pp_res, gFunc, popAlias, channels, gFunc_args) 
>     {
>         require(openCyto)
>         sn <- sampleNames(fs)
>         fr <- as(fs, "flowFrame")
>         total <- nrow(fr)
>         subSample <- gFunc_args[["subSample"]]
>         gFunc_args[["subSample"]] <- NULL
>         if (!is.null(subSample)) {
>             if (is.numeric(subSample)) {
>                 if (subSample > 1) {
>                     samp.ind <- sample.int(total, subSample)
>                     fr <- fr[samp.ind]
>                 }
>                 else if (subSample > 0) {
>                     samp.ind <- sample.int(total, subSample * total)
>                     fr <- fr[samp.ind]
>                 }
>                 else stop("invalid 'subSample' argument: ", subSample)
>             }
>             else stop("invalid 'subSample' argument: ", subSample)
>         }
>         openCyto.options <- getOption("openCyto")
>         minEvents <- openCyto.options[["gating"]][["minEvents"]]
>         if (is.null(minEvents)) 
>             minEvents <- 0
>         if (nrow(fr) <= minEvents) {
>             warning(paste(sn, collapse = ","), ": Not enough events to proceed the data-driven gating!Returning a dummy gate instead.")
>             channels <- as.vector(na.omit(channels))
>             nDim <- length(channels)
>             if (nDim == 1) 
>                 gate_coordinates <- list(c(-Inf, -Inf))
>             else if (nDim == 2) 
>                 gate_coordinates <- list(c(-Inf, -Inf), c(-Inf, -Inf))
>             else stop(nDim, " dimensional gating is not supported yet!")
>             names(gate_coordinates) <- channels
>             filterRes <- rectangleGate(gate_coordinates)
>             if (grepl("flowClust\\.[12]d", gFunc)) 
>                 filterRes <- fcRectangleGate(filterRes, priors = list(), 
>                     posts = list())
>             nPop <- length(popAlias)
>             filterResType <- ifelse(nPop == 1, "filter", "filters")
>             if (filterResType == "filters") {
>                 filterRes <- filters(lapply(1:nPop, function(i) filterRes))
>             }
>         }
>         else {
>             if (!.isRegistered(gFunc)) {
>                 stop(sprintf("Can't gate using unregistered method %s", 
>                     gFunc))
>             }
>             thisCall <- substitute(f(fr = fr, pp_res = pp_res, channels = channels), 
>                 list(f = as.symbol(gFunc)))
>             filterRes <- try(do.call(gFunc, c(list(fr = fr, pp_res = pp_res, 
>                 channels = channels), gFunc_args)), silent = TRUE)
>         }
>         if (extends(class(filterRes), "filter") || extends(class(filterRes), 
>             "filters")) {
>             list(sapply(sampleNames(fs), function(i) filterRes, simplify = FALSE))
>         }
>         else {
>             stop("failed at ", paste0(sn), "\n", filterRes)
>         }
>     })(dots[[1L]][[7L]], dots[[2L]][[7L]], gFunc = ".curv2gate", 
>         popAlias = "*", channels = c("Green-E-582/15-A", "Violet-C-670/30-A"
>         ), gFunc_args = list())
> 14: mapply(list(`Alcina TregMAIT_AV 10-1974 P1.fcs` = <S4 object of class "flowSet">, 
>         `Alcina TregMAIT_BV 08-1966.fcs` = <S4 object of class "flowSet">, 
>         `Alcina TregMAIT_CM 06-1955.fcs` = <S4 object of class "flowSet">, 
>         `Alcina TregMAIT_GG 08-1951.fcs` = <S4 object of class "flowSet">, 
>         `Alcina TregMAIT_LM 04-1938 P1.fcs` = <S4 object of class "flowSet">, 
>         `Alcina TregMAIT_RM 01-1951.fcs` = <S4 object of class "flowSet">, 
>         `Alcina TregMAIT_TA 09-1949 P1.fcs` = <S4 object of class "flowSet">), 
>         list(`Alcina TregMAIT_AV 10-1974 P1.fcs` = NULL, `Alcina TregMAIT_BV 08-1966.fcs` = NULL, 
>             `Alcina TregMAIT_CM 06-1955.fcs` = NULL, `Alcina TregMAIT_GG 08-1951.fcs` = NULL, 
>             `Alcina TregMAIT_LM 04-1938 P1.fcs` = NULL, `Alcina TregMAIT_RM 01-1951.fcs` = NULL, 
>             `Alcina TregMAIT_TA 09-1949 P1.fcs` = NULL), FUN = .gating_adaptor, 
>         MoreArgs = list(gFunc = ".curv2gate", popAlias = "*", channels = c("Green-E-582/15-A", 
>         "Violet-C-670/30-A"), gFunc_args = list()))
> 13: eval(expr, envir, enclos)
> 12: eval(thisCall)
> 11: .gating_gtMethod(x, y, ...)
> 10: gating(x = this_gate, y, parent = parent, gtPop = gt_node_pop, 
>         pp_res = pp_res, ...)
> 9: gating(x = this_gate, y, parent = parent, gtPop = gt_node_pop, 
>        pp_res = pp_res, ...)
> 8: .gating_gatingTemplate(x, y, env_fct, ...)
> 7: .local(x, y, ...)
> 6: gating(gt, gs, ...)
> 5: gating(gt, gs, ...)
> 4: withCallingHandlers(expr, message = function(c) invokeRestart("muffleMessage"))
> 3: suppressMessages(gating(gt, gs, ...))
> 2: add_pop(gs, alias = "*", pop = "*", dims = "CD25,CD127", gating_method = "curv2gate", 
>        bwFac = 5, parent = "CD4+CD8b-")
> 1: rbind(template, add_pop(gs, alias = "*", pop = "*", dims = "CD25,CD127", 
>        gating_method = "curv2gate", bwFac = 5, parent = "CD4+CD8b-"))**_**
> 


**4.** When I use the curv2gate_geom, I receive the following error, even though  I tried 1, 2, 3, 4,5,6 number in the alias names column and the error I keep receiving is: 
  **_number of population names (given by 'name' argument) does not agree with the number of filter objects in 'filters'!_**
  When I do traceback() I receive the following: 
```
  20: stop("number of population names (given by 'name' argument) does not agree with the number of filter objects in 'filters'!")
19: .local(wf, action, ...)
18: add(wf = gh, action = curFilter, ...)
17: add(wf = gh, action = curFilter, ...)
16: FUN(X[[i]], ...)
15: lapply(samples, function(sample) {
  curFilter <- action[[sample]]
  gh <- wf[[sample]]
  add(wf = gh, action = curFilter, ...)
})
14: lapply(samples, function(sample) {
  curFilter <- action[[sample]]
  gh <- wf[[sample]]
  add(wf = gh, action = curFilter, ...)
})
13: .local(wf, action, ...)
12: selectMethod("add", signature = c(wf = "GatingSet", action = "filterList"))(wf, 
                                                                                action, ...)
11: add(wf, flist, ...)
10: add(wf, flist, ...)
9: add(y, flist, parent = parent, name = popAlias, validityCheck = FALSE, 
       recompute = TRUE)
8: add(y, flist, parent = parent, name = popAlias, validityCheck = FALSE, 
       recompute = TRUE)
7: .gating_gtMethod(x, y, ...)
6: gating(x = this_gate, y, parent = parent, gtPop = gt_node_pop, 
          pp_res = pp_res, ...)
5: gating(x = this_gate, y, parent = parent, gtPop = gt_node_pop, 
          pp_res = pp_res, ...)
4: .gating_gatingTemplate(x, y, env_fct, ...)
3: .local(x, y, ...)
2: gating(gt_tcell, gs)
1: gating(gt_tcell, gs) 

```
--- And if I try alias=* & pop=*, i get:
  ****_Error in add(y, flist, parent = parent, name = popAlias, validityCheck = FALSE,  : 
                 the gate list doesn't constain valid 'filter', 'filters' or 'filterResult' objects!_**** 

**P.S. I would like to ask if I'm asking very basic questions here & if there're other online reading materials you can suggest for me? Great one would be if you have deeper information i could read in building/registering a function as a plugin to use in the .csv gating template?**

**Comment by mikejiang** [comment]
`curv2gate` is just an example to illustrate how to produce more than one gate from one `row` in `csv template`. You should probably pick your own gating engine and wrap it into the similar wrapper function I showed you.
And I don't understand why you would leave `alias` and `pop` empty in your template? I thought the `openCyto` vignette and the example above were pretty clear on this matter.

**Comment by anaraserikbek** [comment]
No, in the alias and pop fields i have tried several variations as explained in the vignette & the example above. leaving them * was only the last option I tried. If you look, I've been getting errors even when using as described in the vignette. 
so, if i decide to use one of the outside clustering models, how can I write them as a plugin so that I can use it in the .csv template? there're any vignette for plugin functions?

**Comment by mikejiang** [comment]
`curv2gate` and `curv2gate_geom` in the example are the plugin functions
