### ISSUE TITLE
speed up flowClust.2d 

### ISSUE THREAD

**Issue by mikejiang** [RGLab/openCyto#115]
It has been the method of choice for `lymph` gate in auto gating pipeline. However it is also a known bottleneck in terms of its speed.  I am thinking about tailoring the original `flowClust` code into a `lightweight` and dedicated version for `openCyto`

**Comment by mikejiang** [comment]
The profiling result indicates that [this line](https://github.com/RGLab/flowClust/blob/trunk/R/flowClust.R#L290) is responsible for `70%` of computing time. 
Reducing `nstart` from `100` to `1` immediately eliminates this `overhead` without changing the gate result in my test case. 
So my question for @raphg and @gfinak  is:
* how crucial is this `kmeans initialization` step for the proceeding `flowClust` C code? 
* And does this `random sets` parameter have to big enough to ensure the robustness of the algorithm?

**Comment by gfinak** [comment]
I don't think there's any need for nstart to be as large as it is. Maybe go for 10.

**Comment by SamGG** [comment]
What about sub-sampling the dataset down to 10k or 5k events?

**Comment by mikejiang** [comment]
`nstart = 10`  does make big difference, but still makes `kmeans` standing out as `44%`. I wonder if we could go a step further by trying `1`, which is the default for `kmeans`.  Because I am able to get the same gate and it brings the time down to `0`

**Comment by mikejiang** [comment]
@SamGG, it is not documented, but `sub-sampling` is actually already available as part of `openCyto` framework.  It can be done by simply specifying `subSample` argument (s `numeric` value, number of cells to be sampled) directly in `gating_args` column.

**Comment by SamGG** [comment]
@mikejiang Thanks for this useful tip
kmeans states also that `iter.max = 10` as default. IMHO time is proportional with the same weight to `nstart` and `iter.max`. I would prefer to keep 10 random initializations rather only 1 in order to avoid falling in some kind of local minimum, but as the time, I would accept a trade-off on the precision of the solution as it will be improved by the EM algorithm, and so `iter.max = 10` sounds good to me. That's only my two cents opinion. Find the right solution guys...

**Comment by mikejiang** [comment]
Here is the improvement(for now,  the `fast` version is turned off by default, we will change it when it is proved to be robust)
```r
Unit: seconds
                                               expr      min       lq     mean
 g1 <- flowClust.2d(fr, "FSC-A", "SSC-A")           7.174108 7.293012 8.168923
 g2 <- flowClust.2d(fr, "FSC-A", "SSC-A", fast = T) 1.028226 1.035266 1.327760
```
and resulted two gates
```r
autoplot(fr, "FSC-A", "SSC-A") + geom_gate(g1, size = 1, alpha = 0.5) + geom_gate(g2, col = "black", size = 1, linetype = "dotted")
```
![image](https://cloud.githubusercontent.com/assets/1385649/16351027/7290cab2-3a17-11e6-95d9-cfe2199bb90d.png)

`profling` shows `94%` of computing now attributes to `flowClust .C` function indicating that there is probably no more optimization room at `R` level.
```r
                 total.time total.pct self.time self.pct
".flowClustFast"        1.06    100.00      0.00     0.00
"flowClust.2d"          1.06    100.00      0.00     0.00
...
".C"                    1.00     94.34      1.00    94.34
...
```
