### ISSUE TITLE
openCyto paper's gating template trial 

### ISSUE THREAD

**Issue by anaraserikbek** [RGLab/openCyto#117]
hello everyone, 
I have a question regarding the gating template for **Figure_S3** (supplementary figure) & its corresponding gating template **File_S1.** In that gating template there are several alias & pop names that repeatedly occur in the gating template. As I've tried to use the same names in my gating template, openCyto gives an error that the alias name has to be unique. So, I wonder if there's a way to get around this requirement that they used in the paper? (or, did just the older version of openCyto  did not have this requirement? and if it was changed now, how is it more adequate or why it was changed) I believe this would make writing the templates much easier

**Comment by mikejiang** [comment]
`alias` doesn't have to be unique but its `gating path` must be. e.g. this is ok
```r
alias parent
IL2   cd4
IL2   cd8
``
but this is not
```r
alias parent
IL2   cd4
IL2   cd4
``
