### ISSUE TITLE
flowClust gating method for identifying several clusters

### ISSUE THREAD

**Issue by anaraserikbek** [RGLab/openCyto#118]
hello everyone, 
I know that **openCyto** (when using in the gating template) while writing **flowClust**, openCyto automatically gates for 1 main cluster (the most dense one). However, I've used the actual flowClust package to identify overlapping clusters with its t-misture possibilities, and I would like to gate for those three clusters through openCyto package (either through gating template or just manually coding). My questions are as follows: 
1) why, when using flowClust in openCyto, it only gates for 1 cluster, even though originally flowClust can identify several clusters ? 
2) if I want to use flowClust to gate for several clusters & use those found clusters for further gating  with openCyto, how can I accomplish this? 
Currently, i've tried flowClust on my data & it has given a reasonable clustering. 
the code i used: ```

```
data=read.FCS("Alcina TregMAIT_AV 10-1974 P1_CD4cells.fcs")
res1=flowClust(data,varNames=c("Green-E-582_15-A","Violet-C-670_30-A"),K=3,B=100)
data2=data[data %in% res1,]
res2=flowClust(data2,varNames=c("Green-E-582_15-A","Violet-C-670_30-A"),K=1:4,B=100)
criterion(res2,"BIC")
summary(res2[[3]])
flowClust(data2,varNames=c("Green-E-582_15-A","Violet-C-670_30-A"),B=100,K=3,level=1)
plot(res2[[3]],data=data2,level=0.8,z.cutoff=0)
[flowClust_CD25_CD127.pdf](https://github.com/RGLab/openCyto/files/343717/flowClust_CD25_CD127.pdf)
```

```
Also, I've included the clustering which I'm trying to achieve 
```

**Comment by mikejiang** [comment]
You've asked (been answered) the same question 3 weeks ago https://github.com/RGLab/openCyto/issues/113#issuecomment-224992932

**Comment by mikejiang** [comment]
`tmix2DGate` from `flowIncubator` package is what you are after.
See its example [here](http://rpubs.com/wjiang2/194332)

**Comment by anaraserikbek** [comment]
I see tmix2DGate is using flowClust as well. but, is flowIncubator is a valid package? I couldn't install it through bioconductor, i have also tried to download the .zip file of flowIncubator; however, i receive an error saying it is not a valid package, and, after I updated my R to 3.3.1, it says it's not available for R Version 3.3.1.  do i need to install an older version for R for this package?

**Comment by mikejiang** [comment]
It is on `github`
```r
devtools::install_github("RGLab/flowIncubator")
```

**Comment by anaraserikbek** [comment]
hi, i've tried this code & I receive: 
```
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Timeout was reached
> traceback()
12: .Call(R_curl_fetch_disk, url, handle, path, "wb", nonblocking)
11: curl::curl_fetch_disk(url, x$path, handle = handle)
10: request_fetch.write_disk(req$output, req$url, handle)
9: request_fetch(req$output, req$url, handle)
8: request_perform(req, hu$handle$handle)
7: httr::GET(url, path = path, httr::write_disk(path = tmp))
6: remote_package_name.github_remote(remote)
5: remote_package_name(remote)
4: FUN(X[[i]], ...)
3: vapply(remotes, install_remote, ..., FUN.VALUE = logical(1))
2: install_remotes(remotes, quiet = quiet, ...)
1: devtools::install_github("RGLab/flowIncubator")
```
 After, i've re-installed devtools & curl packages and changed R to the 3.2 & still was not able to install it. They also suggest changing the mirror, which i'm not sure which one you belong to: http://cran.wustl.edu/ ?
  I wonder which version of R can flowIncubator be supported by? (32bit 64bit)?

**Comment by mikejiang** [comment]
Are you on `windows`? check [this post](http://stackoverflow.com/questions/31311872/error-while-using-install-github-devtools-timeout-issue) out to see if it helps.

**Comment by anaraserikbek** [comment]
@mikejiang yes, I'm using Windows version 6.1.7601. 
and I have seen this post before & tried their suggestion as well & even created a thread with this question in stocoverflow: 
1) when i run:
 ```
options(download.file.method = "wininet")
 library("devtools")
 install_github("RGLab/flowIncubator") 
```
as they suggested, i receive: 
```
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Timeout was reached
```
2) When i try :
```
library(devtools) 
dev_mode(on=F)
install_github("RGLab/flowIncubator")

```
I receive the same error: 
 ```
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Timeout was reached
> traceback()
12: .Call(R_curl_fetch_disk, url, handle, path, "wb", nonblocking)
11: curl::curl_fetch_disk(url, x$path, handle = handle)
10: request_fetch.write_disk(req$output, req$url, handle)
9: request_fetch(req$output, req$url, handle)
8: request_perform(req, hu$handle$handle)
7: httr::GET(url, path = path, httr::write_disk(path = tmp))
6: remote_package_name.github_remote(remote)
5: remote_package_name(remote)
4: FUN(X[[i]], ...)
3: vapply(remotes, install_remote, ..., FUN.VALUE = logical(1))
2: install_remotes(remotes, quiet = quiet, ...)
1: install_github("RGLab/flowIncubator")
```


if this could be of any help, my colleague have tried the 2nd code as well, and there was a different sort of error: 
And the error at the end:
```
* installing *source* package ‘flowIncubator’ ...
** R
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  namespace ‘flowWorkspace’ 3.16.16 is being loaded, but >= 3.17.15 is required
ERROR: lazy loading failed for package ‘flowIncubator’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/flowIncubator’
Erreur : Command failed (1)
```

**Comment by mikejiang** [comment]
I don't know what happened to your windows, but ` options(download.file.method = "wininet")` definitely works for me
```r
> devtools::install_github("RGLab/flowIncubator")
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Timeout was reached
> options(download.file.method = "wininet")
> devtools::install_github("RGLab/flowIncubator")
Downloading GitHub repo RGLab/flowIncubator@master
from URL https://api.github.com/repos/RGLab/flowIncubator/zipball/master
Installing flowIncubator

```
And I don't want to comment on your colleague's try since the error message was self-explaining.

If you can't use `devtools`, you can always download it and run `R CMD INSTALL`

The bottom line is `flowIncubator::tmix2DGate` is a `self-contained` wrapper function, if all these failed, you can at least to inline it in your code

**Comment by anaraserikbek** [comment]
@mikejiang after` Installing flowIncubator` line, do you get any messages? and the function is running? 

yes, i have tried it on a Mac as well to see if it is really my Windows, but i got an error too:
```
options(download.file.method = "wininet")
 > devtools::install_github("RGLab/flowIncubator")
Downloading GitHub repo RGLab/flowIncubator@master
from URL https://api.github.com/repos/RGLab/flowIncubator/zipball/master
Installing flowIncubator
Error in download.file(url, destfile, method, mode = "wb", ...) :
  objet 'status' introuvable
Warning in download.packages(x$name, destdir = dest_dir, repos = x$repos,  :
  download of package ‘QUALIFIER’ failed
Error in download.packages(x$name, destdir = dest_dir, repos = x$repos,  :
  indice hors limites 

```
and when I do traceback():
```
> traceback()
13: remote_download.cran_remote(remote, quiet = quiet)
12: remote_download(remote, quiet = quiet)
11: FUN(X[[i]], ...)
10: vapply(remotes, install_remote, ..., FUN.VALUE = logical(1))
9: install_remotes(object$remote[behind], ..., quiet = quiet)
8: update.package_deps(pkg, ..., Ncpus = threads, quiet = quiet,
       upgrade = upgrade)
7: update(pkg, ..., Ncpus = threads, quiet = quiet, upgrade = upgrade)
6: install_deps(pkg, dependencies = initial_deps, upgrade = upgrade_dependencies,
       threads = threads, force_deps = force_deps, quiet = quiet,
       ...)
5: install(source, ..., quiet = quiet, metadata = metadata)
4: FUN(X[[i]], ...)
3: vapply(remotes, install_remote, ..., FUN.VALUE = logical(1))
2: install_remotes(remotes, quiet = quiet, ...)
1: devtools::install_github("RGLab/flowIncubator")
```

And then i've tried to install QUALIFIER directly from Bioconductor through biocLite and it did not work either. 

But in order as you're saying to use it in the inline code, don't I still need to install flowIncubator somehow? 
Also, I thought if I could just use the t

`mix2DGate`

 function in my code & looked at the function's code in `flowIncubator`. And, there is a function specified from `openCyto` named `flowClustFast ` & I wonder how tmix2DGate is supposed to utilize it, it's not incorporated in openCyto?  
(and, regarding devtools, it's working very well)

**Comment by mikejiang** [comment]
`options(download.file.method = "wininet")` is for `windows` **only**, you don't put that on `mac` or `linux`
