### ISSUE TITLE
flowIncubator function tmix2DGate and flowClustFast error

### ISSUE THREAD

**Issue by anaraserikbek** [RGLab/openCyto#121]
Hi everyone, 

I was not successful in installing the flowIncubator package on Windows, however it was installed on my Mac through `install_github("RGLab/flowIncubator").`

I tried the function of flowIncubator `tmix2DGate` on my data and it seems that the `flowClustFast` function of openCyto that the flowIncubator is referring to is non-existent? When I compare my flowIncubator package files in the library on Windows vs Mac, they have a bit different number of files. Especially, there are no tmix2DGate.R in flowIncubator's R file. So, I tried to change the constituents of my flowIncubator on Mac, adding all missing files and still R does give this error: 
my code: `add_pop(gs, alias = "cd41,cd42,cd43", pop = "*", parent = "root", dims = "CD25,CD127", gating_method = "tmix2DGate.wrapper", gating_args = "K = 3, quantile = 0.6, trans = 0")`

```
Error in (function (fs, pp_res, gFunc, popAlias, channels, gFunc_args)  : 
  failed at Alcina TregMAIT_AV 10-1974 P1.fcs
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object '.flowClustFast' not found
```

**when I do traceback()**

```
 traceback()
15: stop("failed at ", paste0(sn), "\n", filterRes)
14: (function (fs, pp_res, gFunc, popAlias, channels, gFunc_args) 
    {
        require(openCyto)
        sn <- sampleNames(fs)
        fr <- as(fs, "flowFrame")
        total <- nrow(fr)
        subSample <- gFunc_args[["subSample"]]
        gFunc_args[["subSample"]] <- NULL
        if (!is.null(subSample)) {
            if (is.numeric(subSample)) {
                if (subSample > 1) {
                    samp.ind <- sample.int(total, subSample)
                    fr <- fr[samp.ind]
                }
                else if (subSample > 0) {
                    samp.ind <- sample.int(total, subSample * total)
                    fr <- fr[samp.ind]
                }
                else stop("invalid 'subSample' argument: ", subSample)
            }
            else stop("invalid 'subSample' argument: ", subSample)
        }
        openCyto.options <- getOption("openCyto")
        minEvents <- openCyto.options[["gating"]][["minEvents"]]
        if (is.null(minEvents)) 
            minEvents <- 0
        if (nrow(fr) <= minEvents) {
            warning(paste(sn, collapse = ","), ": Not enough events to proceed the data-driven gating!Returning a dummy gate instead.")
            channels <- as.vector(na.omit(channels))
            nDim <- length(channels)
            if (nDim == 1) 
                gate_coordinates <- list(c(-Inf, -Inf))
            else if (nDim == 2) 
                gate_coordinates <- list(c(-Inf, -Inf), c(-Inf, -Inf))
            else stop(nDim, " dimensional gating is not supported yet!")
            names(gate_coordinates) <- channels
            filterRes <- rectangleGate(gate_coordinates)
            if (grepl("flowClust\\.[12]d", gFunc)) 
                filterRes <- fcRectangleGate(filterRes, priors = list(), 
                    posts = list())
            nPop <- length(popAlias)
            filterResType <- ifelse(nPop == 1, "filter", "filters")
            if (filterResType == "filters") {
                filterRes <- filters(lapply(1:nPop, function(i) filterRes))
            }
        }
        else {
            if (!.isRegistered(gFunc)) {
                stop(sprintf("Can't gate using unregistered method %s", 
                    gFunc))
            }
            thisCall <- substitute(f(fr = fr, pp_res = pp_res, channels = channels), 
                list(f = as.symbol(gFunc)))
            filterRes <- try(do.call(gFunc, c(list(fr = fr, pp_res = pp_res, 
                channels = channels), gFunc_args)), silent = TRUE)
        }
        if (extends(class(filterRes), "filter") || extends(class(filterRes), 
            "filters")) {
            list(sapply(sampleNames(fs), function(i) filterRes, simplify = FALSE))
        }
        else {
            stop("failed at ", paste0(sn), "\n", filterRes)
        }
    })(dots[[1L]][[1L]], dots[[2L]][[1L]], gFunc = ".tmix2DGate.wrapper", 
        popAlias = c("cd41", "cd42", "cd43"), channels = c("Green-E-582/15-A", 
        "Violet-C-670/30-A"), gFunc_args = list(K = 3, quantile = 0.6, 
            trans = 0))
13: mapply(list(`Alcina TregMAIT_AV 10-1974 P1.fcs` = <S4 object of class "flowSet">, 
        `Alcina TregMAIT_BV 08-1966.fcs` = <S4 object of class "flowSet">, 
        `Alcina TregMAIT_CM 06-1955.fcs` = <S4 object of class "flowSet">, 
        `Alcina TregMAIT_GG 08-1951.fcs` = <S4 object of class "flowSet">, 
        `Alcina TregMAIT_LM 04-1938 P1.fcs` = <S4 object of class "flowSet">, 
        `Alcina TregMAIT_RM 01-1951.fcs` = <S4 object of class "flowSet">, 
        `Alcina TregMAIT_TA 09-1949 P1.fcs` = <S4 object of class "flowSet">), 
        list(`Alcina TregMAIT_AV 10-1974 P1.fcs` = NULL, `Alcina TregMAIT_BV 08-1966.fcs` = NULL, 
            `Alcina TregMAIT_CM 06-1955.fcs` = NULL, `Alcina TregMAIT_GG 08-1951.fcs` = NULL, 
            `Alcina TregMAIT_LM 04-1938 P1.fcs` = NULL, `Alcina TregMAIT_RM 01-1951.fcs` = NULL, 
            `Alcina TregMAIT_TA 09-1949 P1.fcs` = NULL), FUN = .gating_adaptor, 
        MoreArgs = list(gFunc = ".tmix2DGate.wrapper", popAlias = c("cd41", 
        "cd42", "cd43"), channels = c("Green-E-582/15-A", "Violet-C-670/30-A"
        ), gFunc_args = list(K = 3, quantile = 0.6, trans = 0)))
12: eval(expr, envir, enclos)
11: eval(thisCall)
10: .gating_gtMethod(x, y, ...)
9: gating(x = this_gate, y, parent = parent, gtPop = gt_node_pop, 
       pp_res = pp_res, ...)
8: gating(x = this_gate, y, parent = parent, gtPop = gt_node_pop, 
       pp_res = pp_res, ...)
7: .gating_gatingTemplate(x, y, env_fct, ...)
6: .local(x, y, ...)
5: gating(gt, gs, ...)
4: gating(gt, gs, ...)
3: withCallingHandlers(expr, message = function(c) invokeRestart("muffleMessage"))
2: suppressMessages(gating(gt, gs, ...))
1: add_pop(gs, alias = "cd41,cd42,cd43", pop = "*", parent = "root", 
       dims = "CD25,CD127", gating_method = "tmix2DGate.wrapper", 
       gating_args = "K = 3, quantile = 0.6, trans = 0")
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.4 (El Capitan)
```

**Sessioninfo()**

```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.4 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  splines   stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] devtools_1.12.0           flowClust_3.10.1          clue_0.3-51              
 [4] corpcor_1.6.8             mnormt_1.5-4              ellipse_0.3-8            
 [7] RBGL_1.48.1               graph_1.50.0              Biobase_2.32.0           
[10] BiocGenerics_0.18.0       rgl_0.95.1441             flowIncubator_0.99.9     
[13] ggplot2_2.1.0             data.table_1.9.6          flowStats_3.30.1         
[16] cluster_2.0.4             fda_2.4.4                 Matrix_1.2-6             
[19] flowWorkspaceData_2.8.0   openCyto_1.10.3           flowWorkspace_3.18.8     
[22] gridExtra_2.2.1           ncdfFlow_2.18.0           BH_1.60.0-2              
[25] RcppArmadillo_0.7.100.3.1 flowViz_1.36.2            lattice_0.20-33          
[28] flowCore_1.38.2          

```

Could it also be due to the RStudio version that I have? They suggest updating the RStudio, however I have the newest one for Mac.

**Comment by mikejiang** [comment]
You need to install the latest version of `openCyto` (`1.11.6`) from either github or bioconductor development branch.

**Comment by anaraserikbek** [comment]
How often do newer versions of packages get updated in Bioconductor? when i install through Bioconductor,  the version installed is still 1.10.3. and when I install directed from github for 1.11.6, I receive the error 404: Not found
```
install_github("RGLab/openCyto")
Downloading GitHub repo RGLab/openCyto@master
from URL https://api.github.com/repos/RGLab/openCyto/zipball/master
Error in stop(github_error(request)) : 404: Not Found
 (404)
> traceback()
8: stop(github_error(request))
7: download_github(dest, src, auth)
6: remote_download.github_remote(remote, quiet = quiet)
5: remote_download(remote, quiet = quiet)
4: FUN(X[[i]], ...)
3: vapply(remotes, install_remote, ..., FUN.VALUE = logical(1))
2: install_remotes(remotes, quiet = quiet, ...)
1: install_github("RGLab/openCyto") 
```
I also tried to download the .zip file & install, but got various warnings & the package wasn't in the library:
```
> install.packages( "/Users/annickviguier/Downloads/openCyto-trunk.zip",repos="NULL", type="source")
Warning in install.packages :
  URL 'HTTP://NULL/src/contrib/PACKAGES.gz': status was 'Couldn't resolve host name'
Warning in install.packages :
  URL 'HTTP://NULL/src/contrib/PACKAGES': status was 'Couldn't resolve host name'
Warning in install.packages :
  unable to access index for repository NULL/src/contrib:
  cannot download all files
Warning in install.packages :
  package ‘/Users/annickviguier/Downloads/openCyto-trunk.zip’ is not available (for R version 3.3.1)

```

**Comment by anaraserikbek** [comment]
Hi Mike,
i've resolved the issue with flowIncubator on my Windows. Turns out it was a proxy-issue.
For openCyto 1.11.6, through Bioconductor the version is still 10.3. However, i installed directly through github using the following code, after updating the Rtools & it worked!
```
library("devtools")
Sys.setenv("https_proxy"="http://www-cache.curie.fr:3128")
devtools::install_git("https://github.com/RGLab/openCyto.git") 
```
However, before I tried another way: 
`devtools::install_github("RGLab/flowIncubator")`
and I kept receiving an `Error 404: Not Foun`d (both through Windows & the Mac)

**Comment by mikejiang** [comment]
provide your code and `traceback` output (to keep this thread short, don't paste it here directly, but attach them as files)

**Comment by anaraserikbek** [comment]
Okay, i have searched in the R-codeof flowClust, tmixFilter, flowClustFast, tmix2DGate and haven't found such an error. Also, i have tried to specify the gate boundaries in several ways, but had errors in all. I didn't see in the code that flowClustFast or even flowClust asking for the specification of the gate location, except the min & max values. 
I have attached the template line, the code & traceback to this comment. 
[tmix2DGate-flowClustFast error.docx](https://github.com/RGLab/openCyto/files/371133/tmix2DGate-flowClustFast.error.docx)

**Comment by mikejiang** [comment]
You may want to reduce `quantile` so that they don't overlap. An percentage of `3` pops may not sum up to `100%`. @gfinak can better explain the rationale behind that.

`openCyto` template can't match alias to cluster intelligently. Because there is no such information. It It rather simply assumes the order you provided in `alias` column is the order by which `gating function`(here is `tmix2DGate`) returns the 3 clusters consistently across samples.

Also Can you also post your `tmix2DGate.wrapper` definition?

**Comment by gfinak** [comment]
@anaraserikbek Something's wonky, you should definitely have the proportions sum to 100%. How are you calculating the proportions from the output?

**Comment by anaraserikbek** [comment]
@mikejiang yes, but if I reduce the quantile a lot of cells are left, and I want ALL existing cells to be in one of the K=3 gates. If the gates order is consistent, does that mean I just manually identify which population comes first and then always keep the order/name match for downstream ordering? There's no other way? 
the tmix2DGate.wrapper that I use is the following: 
```
tmix2DGate.wrapper <- function(fr, pp_res = NULL, channels, ...){
  flowIncubator:::tmix2DGate(fr, channels, ...)}
registerPlugins(tmix2DGate.wrapper, "tmix2DGate.wrapper") 
``` 
@gfinak yes, I believe you're right. Indeed, out of my expected 3 populations (a picture attached below), the 2 populations are largest & the 3rd one is hard to identify (i'm not even sure if it could be having a centroid). I thought the clusters in flowClust do not overlap, but now realized assuming t-mixture model of-course they would. It's possible to specify each of the 3 populations' expected range in the gating arguments?
The problem with using another (fixed gates for those 3 populations) is that i'll have to process hundreds of .fcs patient files & the location of the gate shifts a bit. But, i wonder if I use quadGate.tmix & specify the range of the gates, is it going to be a better method? 

![polygon_gate_question](https://cloud.githubusercontent.com/assets/19268148/16986308/05d60332-4e86-11e6-93c3-72b44e6cbb7b.png)

**Comment by gfinak** [comment]
If the cd127+ cd25- population is consistent across samples, fit a 1
component mixture to that, and then define the other populations relative
to it. You would have to write a custom gating function for that.

Greg Finak

**Comment by anaraserikbek** [comment]
@gfinak do you mean putting the coordinates of the gates fixed? 
no, unfortunately the CD127+CD25- is not consistent (either by location or by size) across samples/patients. but if the quadGate.tmix clusters overlap, how are they used in the further downstream analysis since one  cell won't be distinctly assigned to a cluster.
Anara

**Comment by gfinak** [comment]
No, I don't mean fixed coordinates. I mean if that population is always the
major population in the projection, across samples.  You could include a
prior to help flowClust identify that one population, then within the
gating routine, gate off of the 90th percentile of that population (for
example) to pick up where the others are. It's doable.
The quad gate tmix filter is probably not the right too for this use case..
two of your quadrants have few cells thus little information to inform
where the cell populations are.

Greg Finak
