### ISSUE TITLE
Plotting an overlay of multiple density plots from gatingset

### ISSUE THREAD

**Issue by john-lee-johnson** [RGLab/openCyto#122]
Hello, I'm new to R and doing flow analysis in R. I read in my flow set, compensated, transformed, applied a gating template to create a gating set. My question is: How can I take my gating set and do an overlaid density plot of two populations (e.g., "CD4+" and "CD8+") for some parameter (e.g., 582/15 Green-A) using the densityplot function.

The following code produces a plot that is very similar to what I would like, but I figure there must be an easier way if I have already produced a GatingSet object

`library(flowViz)`
`data(GvHD)`
`fs <- GvHD[1:5]`
`fs <- transform(fs, estimateLogicle(fs[[1]], colnames(fs)[-c(1:2)]))`
`g <- rectangleGate(` `` `FL1-H` `` ` =  c(3, 5))`
`pos <- Subset(fs, g)`
`densityplot(~` `` `FL1` `` `, fs, margin = F, overlay = list(pos =  pos), stack = F, filter = g, fitGate = F) `

(sorry I had some trouble getting the backticks into the codeblock)

Thank you much for the help!

**Comment by gfinak** [comment]
Hi, John
Have a look at the ggcyto package.

Greg Finak

**Comment by john-lee-johnson** [comment]
Will do!

**Comment by mikejiang** [comment]
moved to RGLab/ggcyto#9
