### ISSUE TITLE
allow the program keep gating a GatingSet when Error occurs

### ISSUE THREAD

**Issue by anaraserikbek** [RGLab/openCyto#123]
Hello,
I am applying the same gating template for a full gating set & some .FCS files do not have enough number of events to gate either in mindensity or flowDensity, and the program stops running at that specific .FCS file. I would like to continue gating with the other files, and only seeing "not enough cells info" in my actual plots. How can I do this?

**Comment by SamGG** [comment]
Hi,
What about `` tryCatch()```?
HTH

**Comment by mikejiang** [comment]
It is addressed by #77, basically you can change `openCyto.options[["gating"]][["minEvents"]]` option so that whenever the events are lower than that threshold a `dummy gate` is added with warnings instead of error.

**Comment by anaraserikbek** [comment]
@mikejiang but this function of displaying warnings instead of errors is already incorporated to openCyto package while installing? (isn't this already in openCyto?
 ```
if(nrow(fr) <= minEvents){
      warning(paste(sn, collapse =","), ": Not enough events to proceed the data-driven gating!Returning a dummy gate instead.") )
```
Does it work on all gating methods (for example, i'm receiving this error for flowClust and I was wondering if I need to modify it directly in flowClust)?

**Comment by anaraserikbek** [comment]
@SamGG but would you have to run tryCatch for this error each time you load R and run a pipeline? Do you have an example of tryCatch usage?

**Comment by mikejiang** [comment]
As I said,  the global variable `options("openCyto")[["gating"]][["minEvents"]]` controls how the `rare-event` population is gated. Default is `0`, which means the `dummy gate` logic will not take place and the `rare-event` will be passed on to the actual gating function and thus will fail and error out. To enter this `if` branch, you have to change and relax that threshold. e.g.
```r
> opt <- options("openCyto")
> opt[["openCyto"]][["gating"]][["minEvents"]]
[1] 0
> opt[["openCyto"]][["gating"]][["minEvents"]] <- 50
> options("openCyto"= opt)
> options("openCyto")
$openCyto
$openCyto$openCyto
$openCyto$openCyto$gating
$openCyto$openCyto$gating$minEvents
[1] 50
```
And yes, this strategy is agnostic to any gating method. You should not do it in `flowClust` intrusively.
