### ISSUE TITLE
When using flowClust.2d for a transitional gate 

### ISSUE THREAD

**Issue by anaraserikbek** [RGLab/openCyto#124]
Hello everyone,
When using the flowClust.2d for creating a transitional gate as shown in this example: 
https://bioconductor.org/packages/devel/bioc/vignettes/openCyto/inst/doc/HowToAutoGating.html#flowclust2d 
In the example, the value of K=6, and i don't see clear 6 populations & I'm trying recreate a similar gate, however, i don't understand the logic behind choosing a certain number of K. Also, how does translation=0.15 affect the population identification?

**Comment by ccasar** [comment]
Have you read the help page for flowClust.2d?

> We cluster the observations in fr into K clusters. 
> [...]
> The cluster for the population of interest is selected as the one with cluster centroid nearest the target in Euclidean distance. By default, the largest cluster (i.e., the cluster with the largest proportion of observations) is selected as the population of interest.

In the example without K flowClust would probably just identify the whole red/yellow area as one big cluster. With the use of K flowClust tries to identify 6 (smaller) clusters and with the use of `target` flowClust chooses the one cluster that is closest to the target. So with the help of K and target it is possible to get better control over the area which is returned as the population.
