### ISSUE TITLE
registering the quadrantGate function of flowStats package

### ISSUE THREAD

**Issue by anaraserikbek** [RGLab/openCyto#125]
Hello, 
i have registered the quadrantGate method from package flowStats with the following code:

```
quadrantGate=function(fr=NA, pp_res=NULL, channels=NA, ...){
  flowStats:::quadrantGate(fr, stains=channels, ...)}
registerPlugins(fun=quadrantGate,methodName="quadrantGate",dep="flowStats","gating")
```

and i get the following error: 

```
Error in (function (fs, pp_res, gFunc, popAlias, channels, gFunc_args)  : 
  failed at ALCINA T_BJ 03-1949 P1.fcs
Error : 'stains' must be object of class 'character' of length 2 
```

the corresponding line in the `gating template` is: 
`pop1   CD27+/-CD45RA+/-    LT CD4+ CD27,CD45RA quadrantGate` 
i do not see why the stains as shown in my gating template is not working. 

> traceback()
> 
> ```
> 12: stop("failed at ", paste0(sn), "\n", filterRes)
> 11: (function (fs, pp_res, gFunc, popAlias, channels, gFunc_args) 
>     {
>         require(openCyto)
>         sn <- sampleNames(fs)
>         fr <- as(fs, "flowFrame")
>         total <- nrow(fr)
>         subSample <- gFunc_args[["subSample"]]
>         gFunc_args[["subSample"]] <- NULL
>         if (!is.null(subSample)) {
>             if (is.numeric(subSample)) {
>                 if (subSample > 1) {
>                     samp.ind <- sample.int(total, subSample)
>                     fr <- fr[samp.ind]
>                 }
>                 else if (subSample > 0) {
>                     samp.ind <- sample.int(total, subSample * total)
>                     fr <- fr[samp.ind]
>                 }
>                 else stop("invalid 'subSample' argument: ", subSample)
>             }
>             else stop("invalid 'subSample' argument: ", subSample)
>         }
>         openCyto.options <- getOption("openCyto")
>         minEvents <- openCyto.options[["gating"]][["minEvents"]]
>         if (is.null(minEvents)) 
>             minEvents <- 0
>         if (nrow(fr) <= minEvents) {
>             warning(paste(sn, collapse = ","), ": Not enough events to proceed the data-driven gating!Returning a dummy gate instead.")
>             channels <- as.vector(na.omit(channels))
>             nDim <- length(channels)
>             if (nDim == 1) 
>                 gate_coordinates <- list(c(-Inf, -Inf))
>             else if (nDim == 2) 
>                 gate_coordinates <- list(c(-Inf, -Inf), c(-Inf, -Inf))
>             else stop(nDim, " dimensional gating is not supported yet!")
>             names(gate_coordinates) <- channels
>             filterRes <- rectangleGate(gate_coordinates)
>             if (grepl("flowClust\\.[12]d", gFunc)) 
>                 filterRes <- fcRectangleGate(filterRes, priors = list(), 
>                     posts = list())
>             nPop <- length(popAlias)
>             filterResType <- ifelse(nPop == 1, "filter", "filters")
>             if (filterResType == "filters") {
>                 filterRes <- filters(lapply(1:nPop, function(i) filterRes))
>             }
>         }
>         else {
>             if (!.isRegistered(gFunc)) {
>                 stop(sprintf("Can't gate using unregistered method %s", 
>                     gFunc))
>             }
>             thisCall <- substitute(f(fr = fr, pp_res = pp_res, channels = channels), 
>                 list(f = as.symbol(gFunc)))
>             filterRes <- try(do.call(gFunc, c(list(fr = fr, pp_res = pp_res, 
>                 channels = channels), gFunc_args)), silent = TRUE)
>         }
>         if (extends(class(filterRes), "filter") || extends(class(filterRes), 
>             "filters")) {
>             list(sapply(sampleNames(fs), function(i) filterRes, simplify = FALSE))
>         }
>         else {
>             stop("failed at ", paste0(sn), "\n", filterRes)
>         }
>     })(dots[[1L]][[1L]], dots[[2L]][[1L]], gFunc = ".quadrantGate", 
>         popAlias = "CD45RA+", channels = "Green-A-780/60-A", gFunc_args = list(
>             positive = TRUE))
> 10: mapply(list(`ALCINA T_BJ 03-1949 P1.fcs` = <S4 object of class "ncdfFlowSet">, 
>         `ALCINA Treg MAIT_AV 10-1974 P2bis.fcs` = <S4 object of class "ncdfFlowSet">, 
>         `ALCINA Treg MAIT_DC 05-1952 P1.fcs` = <S4 object of class "ncdfFlowSet">, 
>         `ALCINA Treg MAIT_SF 09-1947 P2.fcs` = <S4 object of class "ncdfFlowSet">, 
>         `Alcina TregMAIT_AP 11,2f,1948.fcs` = <S4 object of class "ncdfFlowSet">, 
>         `Alcina TregMAIT_AV 10-1974 P1.fcs` = <S4 object of class "ncdfFlowSet">, 
>         `Alcina TregMAIT_AV 10-1974 P2.fcs` = <S4 object of class "ncdfFlowSet">, 
>         `Alcina TregMAIT_BP 02,2f,1954 13082015.fcs` = <S4 object of class "ncdfFlowSet">), 
>         list(`ALCINA T_BJ 03-1949 P1.fcs` = NULL, `ALCINA Treg MAIT_AV 10-1974 P2bis.fcs` = NULL, 
>             `ALCINA Treg MAIT_DC 05-1952 P1.fcs` = NULL, `ALCINA Treg MAIT_SF 09-1947 P2.fcs` = NULL, 
>             `Alcina TregMAIT_AP 11,2f,1948.fcs` = NULL, `Alcina TregMAIT_AV 10-1974 P1.fcs` = NULL, 
>             `Alcina TregMAIT_AV 10-1974 P2.fcs` = NULL, `Alcina TregMAIT_BP 02,2f,1954 13082015.fcs` = NULL), 
>         FUN = .gating_adaptor, MoreArgs = list(gFunc = ".quadrantGate", 
>             popAlias = "CD45RA+", channels = "Green-A-780/60-A", 
>             gFunc_args = list(positive = TRUE)))
> 9: eval(expr, envir, enclos)
> 8: eval(thisCall)
> 7: .gating_gtMethod(x, y, ...)
> 6: gating(x = this_gate, y, parent = parent, gtPop = gt_node_pop, 
>        pp_res = pp_res, ...)
> 5: gating(x = this_gate, y, parent = parent, gtPop = gt_node_pop, 
>        pp_res = pp_res, ...)
> 4: .gating_gatingTemplate(x, y, env_fct, ...)
> 3: .local(x, y, ...)
> 2: gating(gating_template, gs)
> 1: gating(gating_template, gs)
> ```

**Comment by mikejiang** [comment]
You `pop` pattern (`CD27+/-CD45RA+/-`) is telling the template parser to split it into `1d` gating and `refGate`. Please read `section 3` in [vignette](http://bioconductor.org/packages/release/bioc/vignettes/openCyto/inst/doc/HowToWriteCSVTemplate.html)
