### ISSUE TITLE
Using quantileGate in template throws error: "A single channel must be specified."

### ISSUE THREAD

**Issue by ccasar** [RGLab/openCyto#126]
I'm trying to use a quantileGate in one of my templates:

`CD20_CD14,CD20_CD14+,living_CD45+,CD20_CD14,quantileGate,,,,,`

Parsing the template works fine. But as soon as this population is being gated, openCyto exits with the error:

`Gating for 'CD20_CD14'`
`Running in parallel mode with 10 cores.`
`Error in (function (fs, pp_res, gFunc, popAlias, channels, gFunc_args)  : 
  failed at ILCs_008.fcs`
`Error in quantileGate(fr = fr, stain = channels, ...) : 
  A single channel must be specified.`

If I replace quantileGate with mindensity the gating completes successfully. I don't really see where my error is here, as both [quantileGate](https://github.com/RGLab/openCyto/blob/7c430895d3fba76690ad97ae6378a4d63e7eb7a4/R/gating-functions.R#L644) and [mindensity](https://github.com/RGLab/openCyto/blob/7c430895d3fba76690ad97ae6378a4d63e7eb7a4/R/gating-functions.R#L721) seem to use the same check before the error message is thrown.

**Comment by mikejiang** [comment]
The `template` looks fine to me. Make sure to reload the cvs template every time after you make some changes to it.
Another way to trouble shoot the individual row in the `template` is to use `add_pop` API, e.g.
```r
add_pop(gs, gating_method = "quantileGate"
              , dims = "CD20_CD14"
              , parent = "living_CD45+"
              , pop = "CD20_CD14+"
              , alias = "CD20_CD14"
      )      
```

**Comment by ccasar** [comment]
I was now able to go step by step via the add_pop API and when adding the `quantileGate` population, I still get the same error (and only for `quantileGate` and not `mindensity` nor `tailgate`):
`Error in quantileGate(fr = fr, stain = channels, ...) : A single channel must be specified`

This is with the current version from Bioconductor:
```R
> packageVersion('openCyto')
[1] ‘1.10.3’
```

If I install the current version from github, applying the gate via `add_pop` works without causing the error:
```R
install_github('RGLab/openCyto', ref='trunk')
[...]
> packageVersion('openCyto')
[1] ‘1.11.8’
```
So I guess, I'll keep the github version for now.
