### ISSUE TITLE
Suggestion for gating template file format

### ISSUE THREAD

**Issue by zhanxw** [RGLab/openCyto#128]
In the BioConductor page https://www.bioconductor.org/packages/devel/bioc/vignettes/openCyto/inst/doc/openCytoVignette.html

The example file is named as `extdata/gating_template/tcell.csv`. 
However, the content of that file is actually not CSV, but a TSV (tab-separated).
I suggest:
* change the example file name to `extdata/gating_template/tcell.tsv`
* only support TSV files, because in CSV files, users cannot flexibly set `gating_args`. For example, when I tried to set `gate_range=c(50000,80000)`, the extra comma will make confusions for a CSV file.

PS: Thanks for developing OpenCyto. It's very helpful for my research.
PS2: Thanks for bringing back the access to opencyto.org.

**Comment by mikejiang** [comment]
It is just a matter of selecting different delimiters.  I am sure it can be handled by any modern spreedsheet software without problems.

Regarding to the `comma` in the field, you can simply quote the text to avoid confusion , e.g.
`"gate_range=c(50000,80000)"`.
