### ISSUE TITLE
gate_flowClust_1d returns error

### ISSUE THREAD

**Issue by evangreene** [RGLab/openCyto#129]
Hi Everyone,

When I run the following script using the attached flowSet, it returns the error message: "Error: all additional arguments must be of length 2".  When I make the same call to gate_flowClust_1d using different channels/flowsets, it returns without error.

The script:

```R
library(flowWorkspace)
library(flowClust)
library(flowCore)
library(openCyto)
library(ncdfFlow)

fs <- readRDS("./fserrormsg.RDS")
fr <- fs[[1, use.exprs = FALSE]]
chnl <- c("V545-A")
gate <- openCyto::gate_flowClust_1d(fr
                                  , params = c(eval(chnl))
                                  , K = 2
                                  , cutpoint_method="min_density")
```

Please let me know if I can provide additional information.

Thanks,
Evan
[fserrormsg.RDS.zip](https://github.com/RGLab/openCyto/files/700009/fserrormsg.RDS.zip)

**Comment by mikejiang** [comment]
It has to do with `density calculation of t mixture` from `flowClust::dmvtmix` [here](https://github.com/RGLab/openCyto/blob/trunk/R/gating-functions.R#L191), which is returning all `NaN` values. It is beyond my knowledge, maybe @gfinak can give more information about it.

**Comment by gfinak** [comment]
pass in `max.count=10, min.count=10` to the gating routine, this will filter boundary events, which are the source of the problem here. They lead to a cluster with singular variance at the edge of the data.
