### ISSUE TITLE
Gating error message. 

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/openCyto#133]
Dear Dr. Finak and Mike. 
It looks like issue #130, 131. 
I redownloaded 'openCyto' from "https://bioconductor.org/biocLite.R". 
However, There still is an issue.
 
> gt_yohann <- gatingTemplate("gt_yohann_2017Mar.csv")
Adding population:boundary
Adding population:singlet
Adding population:Living
Adding population:lymph
Adding population:CD56dimtemp
Adding population:CD56dim
Warning messages:
1: In `[.data.table`(dt, , `:=`(col, as.character(newCol)), with = FALSE) :
  with=FALSE together with := was deprecated in v1.9.4 released Oct 2014. Please wrap the LHS of := with parentheses; e.g., DT[,(myVar):=sum(b),by=a] to assign to column name(s) held in variable myVar. See ?':=' for other examples. As warned in 2014, this is now a warning.
2: In `[.data.table`(dt, , `:=`(col, as.character(newCol)), with = FALSE) :
  with=FALSE together with := was deprecated in v1.9.4 released Oct 2014. Please wrap the LHS of := with parentheses; e.g., DT[,(myVar):=sum(b),by=a] to assign to column name(s) held in variable myVar. See ?':=' for other examples. As warned in 2014, this is now a warning.

**Comment by kdh4win4** [comment]
[gt_yohann_2017Mar.xlsx](https://github.com/RGLab/openCyto/files/834889/gt_yohann_2017Mar.xlsx)

**Comment by gfinak** [comment]
Are you using the development version of Bioconductor and openCyto version 1.13.4? I am, just loaded your template and don't get those errors.

**Comment by kdh4win4** [comment]
Dear Greg, 

Which R version do you have? openCyto 1.13.4 version is not working on R 3.3.3

**Comment by gfinak** [comment]
I'm using 3.3.2
Can you better define "not working"?

**Comment by kdh4win4** [comment]
> install.packages("~/Downloads/openCyto_**1.13.4**.tgz", repos = NULL, type = .Platform$pkgType)
> library("openCyto", lib.loc="/Library/Frameworks/R.framework/Versions/3.2/Resources/library")
Error: package ‘flowWorkspace’ required by ‘openCyto’ could not be found
In addition: Warning message:
**package ‘openCyto’ was built under R version 3.4.0**

**Comment by mikejiang** [comment]
The error clearly indicates you need to install `flowWorkspace`. Also it is recommended to install these packages through `biocLite` command from bioconductor or through `devtools::install_github("RGLab/openCyto", ref = "trunk")`

**Comment by kdh4win4** [comment]
Rstudio console message is that openCyto 1.13.4 version is written on R 3.4.0 version. 

Is it impossible to read above csv file

**Comment by kdh4win4** [comment]
I installed 1.13.4 version openCyto.
There still is an issue.

Error: package ‘flowWorkspace’ 3.16.16 was found, but >= 3.17.43 is required by ‘openCyto’
In addition: Warning message:
package ‘openCyto’ was built under R version 3.4.0 

I have two questions;
Q1: Where can I get 3.17.43 version flowWorkspace ?
Q2: Do I have to update openCyto ? Why can not I upload gating template csv file using older version openCyto ?

**Comment by mikejiang** [comment]
again, install the latest version from github
`devtools::install_github("RGLab/flowWorkspace", ref = "trunk")`

**Comment by kdh4win4** [comment]
There still are some errors. 

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libkern/OSAtomicDeprecated.h:247:9: note: 'OSAtomicAdd64Barrier' has been explicitly marked deprecated here
int64_t OSAtomicAdd64Barrier( int64_t __theAmount,
        ^
In file included from wsNode.cpp:10:
In file included from ./include/wsNode.hpp:10:
In file included from ./include/nodeProperties.hpp:11:
In file included from ./include/POPINDICES.hpp:15:
In file included from ./include/gate.hpp:15:
In file included from ./include/transformation.hpp:23:
In file included from ./include/calibrationTable.hpp:20:
In file included from ./include/../GatingSet.pb.h:22:
In file included from protobuf-2.6.0/src/google/protobuf/generated_message_util.h:44:
In file included from protobuf-2.6.0/src/google/protobuf/stubs/once.h:81:
In file included from protobuf-2.6.0/src/google/protobuf/stubs/atomicops.h:179:
protobuf-2.6.0/src/google/protobuf/stubs/atomicops_internals_macosx.h:173:9: warning: 'OSAtomicCompareAndSwap64Barrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_compare_exchange_strong() from <atomic> instead [-Wdeprecated-declarations]
    if (OSAtomicCompareAndSwap64Barrier(
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libkern/OSAtomicDeprecated.h:645:9: note: 'OSAtomicCompareAndSwap64Barrier' has been explicitly marked deprecated here
bool    OSAtomicCompareAndSwap64Barrier( int64_t __oldValue, int64_t __newValue,
        ^
In file included from wsNode.cpp:10:
In file included from ./include/wsNode.hpp:10:
In file included from ./include/nodeProperties.hpp:11:
In file included from ./include/POPINDICES.hpp:15:
./include/gate.hpp:440:60: warning: field 'quadrant' will be initialized after field 'interpolated' [-Wreorder]
        CurlyGuadGate(paramPoly _inter, QUAD _quad):polygonGate(),quadrant(_quad),interpolated(false){
                                                                  ^
12 warnings generated.
make: *** No rule to make target `pb_build/src/google/protobuf/.libs/*.o', needed by `/Library/Frameworks/R.framework/Versions/3.2/Resources/library/flowWorkspace/lib/libprotobuf.a'.  Stop.
ERROR: compilation failed for package ‘flowWorkspace’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/flowWorkspace’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/flowWorkspace’
Error: Command failed (1)

**Comment by mikejiang** [comment]
The latest flowWorkspace is 3.21.10, since you are on mac, you should be able to install binary version directly from http://bioconductor.org/packages/3.5/bioc/html/flowWorkspace.html once you upgrade your R to the latest devel. If you want to stick to the R release , then `openCyto 1.12.1` and `flowWorkspace 3.20.5` are the latest you can have. And you will have to manually suppress the warning messages .e.g.
```r
suppressWarnings(gt_yohann <- gatingTemplate("gt_yohann_2017Mar.csv"))
```
which shouldn't affect your gating

**Comment by kdh4win4** [comment]
Hi Mike, 
My R version is 3.2.5
I updated flowWorkspace(3.21.10) and flowCore(1.40.4)
They require R 3.4.0 
I installed R 3.4.0 two days ago, but that was not working well. I am not sure why it was not working well. maybe it still is developing version and not stable yet OR I am not that level programmer. 
There still error signs on Rstudio console window;

Loading required package: flowWorkspace
Error: package ‘flowCore’ 1.36.9 was found, but >= 1.39.9 is required by ‘flowWorkspace’

**> install.packages("~/Downloads/flowWorkspace_3.21.10.tgz", repos = NULL, type = .Platform$pkgType)
> install.packages("~/Downloads/flowCore_1.40.4.tgz", repos = NULL, type = .Platform$pkgType)**

> {
+ library(openCyto) # 
+ library(flowWorkspace);library(flowWorkspaceData);
+ library(flowCore);library(flowDensity)
+ library(dplyr);library(flowViz);
+ library(flowStats); # 
+ library(ncdfFlow);library(data.table);library(COMPASS);library(oligoClasses)
+ }
Loading required package: flowWorkspace
Loading required package: flowCore
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/flowCore/libs/flowCore.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/flowCore/libs/flowCore.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/3.3/Resources/lib/libR.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/flowCore/libs/flowCore.so
  Reason: Incompatible library version: flowCore.so requires version 3.3.0 or later, but libR.dylib provides version 3.2.0
In addition: Warning messages:
**1: package ‘openCyto’ was built under R version 3.4.0 
2: package ‘flowWorkspace’ was built under R version 3.4.0 
3: package ‘flowCore’ was built under R version 3.3.2 
Error: package ‘flowCore’ could not be loaded**

**Comment by gfinak** [comment]
@kdh4win4, please **read the error messages carefully.**

first: `Error: package ‘flowCore’ 1.36.9 was found, but >= 1.39.9 is required by ‘flowWorkspace’`

**This means the wrong version of flowCore is installed and is preventing flowWorkspace from being updated.**

Second: 
```
Loading required package: flowCore
Error in dyn.load(file, DLLpath = DLLpath, ...) :
unable to load shared object '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/flowCore/libs/flowCore.so':
dlopen(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/flowCore/libs/flowCore.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/3.3/Resources/lib/libR.dylib
Referenced from: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/flowCore/libs/flowCore.so
Reason: Incompatible library version: flowCore.so requires version 3.3.0 or later, but libR.dylib provides version 3.2.0
```
Means R is loading packages from an installation of R 3.2. The error **clearly** states you need at least R 3.3 or greater.
You *need* to do the following:
1. Install R 3.3 or greater. Remove old versions of R from your system to make sure dynamic library loading doesn't point to old versions of libraries.
2. Install BioConductor and required packages using the documented approach using either `biocLite.R` or `install_github` as @mikejiang mentioned above.

Installation instructions for BioConductor: https://www.bioconductor.org/install/
By the way, that page says  on the **first line** that **you need R 3.3 or greater**.

`The current release of Bioconductor is version 3.4; it works with R version 3.3.1. Users of older R and Bioconductor users must update their installation to take advantage of new features and to access packages that have been added to Bioconductor since the last release.`

It also explains there how to use the devel branch of bioconductor:
https://www.bioconductor.org/developers/how-to/useDevel/

You will need that to install the latest versions of the flow packages.

**Comment by kdh4win4** [comment]
There still are issues. 
I am in military base there might be network issue.
By the way, I installed R 3.3 and R 3.4.0(dev) and installed each package last stable or developing version (flowCore, flowWorkspace). 

I send you some error signs. I will check what is the problem. My only concern is to read template csv file for gating anyway. Thank you. 


Warning: unable to access index for repository https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.4:
  cannot open URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.4/PACKAGES'
installing the source package ‘flowWorkspaceData’

* installing *source* package ‘flowWorkspaceData’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (flowWorkspaceData)

The downloaded source packages are in
	‘/private/var/folders/hl/blqxfzv56gd2pbhk3nq725hr0000gn/T/RtmpIBJwBr/downloaded_packages’
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.5 (BiocInstaller 1.25.3), R Under development (unstable) (2017-03-15 r72357).
Installing package(s) ‘flowCore’
also installing the dependencies ‘robustbase’, ‘mvtnorm’, ‘pcaPP’, ‘rrcov’

Warning: unable to access index for repository https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.4:
  cannot open URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.4/PACKAGES'
Packages which are only available in source form, and may need compilation of
  C/C++/Fortran: ‘robustbase’ ‘mvtnorm’ ‘pcaPP’ ‘rrcov’
Do you want to attempt to install these from sources?

he downloaded binary packages are in
	/var/folders/hl/blqxfzv56gd2pbhk3nq725hr0000gn/T//RtmpIBJwBr/downloaded_packages
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.5 (BiocInstaller 1.25.3), R Under development (unstable) (2017-03-15 r72357).
Installing package(s) ‘flowWorkspaceData’
Warning: unable to access index for repository https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.4:
  cannot open URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.4/PACKAGES'
installing the source package ‘flowWorkspaceData’

**Comment by gfinak** [comment]
Indeed there don't seem to be any pre-build binaries for 3.4 or r-devel, but they are there for 3.3
See if you can't point the url to :
 `https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/PACKAGES`

**Comment by SamGG** [comment]
My two cents. @kdh4win4 could you upload the exact CSV you are trying to process.

**Comment by kdh4win4** [comment]
Here is my csv file.

> read.csv("gt_yohann_2017Mar.csv")
        alias      pop      parent        dims gating_method                             gating_args
1    boundary boundary        root FSC-A,SSC-A      boundary          min=c(0,0), max=c(2.5e5,2.5e5)
2     singlet  singlet    boundary FSC-A,FSC-H   singletGate                   prediction_level=0.98
3      Living    LIVE-     singlet        LIVE     flowClust target=c(8.5e4, 1.5e4), quantile = 0.89
4       lymph    lymph      Living    CD19,CD3     flowClust                   K=2, target=c(0, 1e2)
5 CD56dimtemp    CD56-       lymph        CD56    mindensity                   gate_range=c(1e3,2e3)
6     CD56dim    CD56+ CD56dimtemp        CD56    mindensity                   gate_range=c(1e2,2e2)
  collapseDataForGating groupBy preprocessing_method preprocessing_args
1                    NA      NA                                        
2                    NA      NA                                        
3                    NA      NA                                        
4                    NA      NA      prior_flowClust                K=3
5                  TRUE      NA                                        
6                  TRUE      NA                                        
> gt_yohann <- gatingTemplate("gt_yohann_2017Mar.csv")
Adding population:boundary
Adding population:singlet
Adding population:Living
Adding population:lymph
Adding population:CD56dimtemp
Adding population:CD56dim
Warning messages:
1: In `[.data.table`(dt, , `:=`(col, as.character(newCol)), with = FALSE) :
  with=FALSE together with := was deprecated in v1.9.4 released Oct 2014. Please wrap the LHS of := with parentheses; e.g., DT[,(myVar):=sum(b),by=a] to assign to column name(s) held in variable myVar. See ?':=' for other examples. As warned in 2014, this is now a warning.
2: In `[.data.table`(dt, , `:=`(col, as.character(newCol)), with = FALSE) :
  with=FALSE together with := was deprecated in v1.9.4 released Oct 2014. Please wrap the LHS of := with parentheses; e.g., DT[,(myVar):=sum(b),by=a] to assign to column name(s) held in variable myVar. See ?':=' for other examples. As warned in 2014, this is now a warning.
3: In `[.data.table`(dt, , `:=`(col, as.character(newCol)), with = FALSE) :
  with=FALSE together with := was deprecated in v1.9.4 released Oct 2014. Please wrap the LHS of := with parentheses; e.g., DT[,(myVar):=sum(b),by=a] to assign to column name(s) held in variable myVar. See ?':=' for other examples. As warned in 2014, this is now a warning.
4: In `[.data.table`(dt, , `:=`(col, as.character(newCol)), with = FALSE) :
  with=FALSE together with := was deprecated in v1.9.4 released Oct 2014. Please wrap the LHS of := with parentheses; e.g., DT[,(myVar):=sum(b),by=a] to assign to column name(s) held in variable myVar. See ?':=' for other examples. As warned in 2014, this is now a warning.
5: In `[.data.table`(dt, , `:=`(col, as.character(newCol)), with = FALSE) :
  with=FALSE together with := was deprecated in v1.9.4 released Oct 2014. Please wrap the LHS of := with parentheses; e.g., DT[,(myVar):=sum(b),by=a] to assign to column name(s) held in variable myVar. See ?':=' for other examples. As warned in 2014, this is now a warning.
6: In `[.data.table`(dt, , `:=`(col, as.character(newCol)), with = FALSE) :
  with=FALSE together with := was deprecated in v1.9.4 released Oct 2014. Please wrap the LHS of := with parentheses; e.g., DT[,(myVar):=sum(b),by=a] to assign to column name(s) held in variable myVar. See ?':=' for other examples. As warned in 2014, this is now a warning.
7: In `[.data.table`(dt, , `:=`(col, as.character(newCol)), with = FALSE) :
  with=FALSE together with := was deprecated in v1.9.4 released Oct 2014. Please wrap the LHS of := with parentheses; e.g., DT[,(myVar):=sum(b),by=a] to assign to column name(s) held in variable myVar. See ?':=' for other examples. As warned in 2014, this is now a warning.
8: In `[.data.table`(dt, , `:=`(col, as.character(newCol)), with = FALSE) :
  with=FALSE together with := was deprecated in v1.9.4 released Oct 2014. Please wrap the LHS of := with parentheses; e.g., DT[,(myVar):=sum(b),by=a] to assign to column name(s) held in variable myVar. See ?':=' for other examples. As warned in 2014, this is now a warning.
9: In `[.data.table`(dt, , `:=`(col, as.character(newCol)), with = FALSE) :
  with=FALSE together with := was deprecated in v1.9.4 released Oct 2014. Please wrap the LHS of := with parentheses; e.g., DT[,(myVar):=sum(b),by=a] to assign to column name(s) held in variable myVar. See ?':=' for other examples. As warned in 2014, this is now a warning.

**Comment by kdh4win4** [comment]
I deleted R and Rstudio and reinstalled R 3.4.0(developer version) and R studio last mac version 1.0.136. 
There still is an error message for installing 'cluster' and other packages. flowCore, flowStats, flowViz.
make: gfortran-4.8: No such file or directory
make: *** [mvt.o] Error 1
ERROR: compilation failed for package ‘mvtnorm’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/mvtnorm’
ERROR: dependency ‘mvtnorm’ is not available for package ‘ks’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ks’

The downloaded source packages are in
	‘/private/var/folders/hl/blqxfzv56gd2pbhk3nq725hr0000gn/T/RtmpZgRAfA/downloaded_packages’
Old packages: 'cluster'
Update all/some/none? [a/s/n]: 
a
Warning: unable to access index for repository https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.4:
  cannot open URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.4/PACKAGES'
Package which is only available in source form, and may need compilation of C/C++/Fortran:
  ‘cluster’
Do you want to attempt to install these from sources?
y/n: y
installing the source package ‘cluster’

trying URL 'https://cran.rstudio.com/src/contrib/cluster_2.0.6.tar.gz'
Content type 'application/x-gzip' length 319245 bytes (311 KB)
==================================================
downloaded 311 KB

* installing *source* package ‘cluster’ ...
** package ‘cluster’ successfully unpacked and MD5 sums checked
** libs
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include   -fPIC  -Wall -mtune=core2 -g -O2  -c clara.c -o clara.o
gfortran-4.8   -fPIC  -g -O2  -c daisy.f -o daisy.o
make: gfortran-4.8: No such file or directory
make: *** [daisy.o] Error 1
ERROR: compilation failed for package ‘cluster’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/cluster’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/cluster’

The downloaded source packages are in
	‘/private/var/folders/hl/blqxfzv56gd2pbhk3nq725hr0000gn/T/RtmpZgRAfA/downloaded_packages’
Warning messages:
1: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘mvtnorm’ had non-zero exit status
2: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘ks’ had non-zero exit status
3: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘cluster’ had non-zero exit status

**Comment by kdh4win4** [comment]
I download cluster package from the link. 
> install.packages("~/Downloads/cluster_2.0.6.tar.gz", repos = NULL, type = "source")
* installing *source* package ‘cluster’ ...
** package ‘cluster’ successfully unpacked and MD5 sums checked
** libs
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include   -fPIC  -Wall -mtune=core2 -g -O2  -c clara.c -o clara.o
gfortran-4.8   -fPIC  -g -O2  -c daisy.f -o daisy.o
make: gfortran-4.8: No such file or directory
make: *** [daisy.o] Error 1
ERROR: compilation failed for package ‘cluster’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/cluster’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/cluster’
Warning in install.packages :
  installation of package ‘/Users/dev_dohoon/Downloads/cluster_2.0.6.tar.gz’ had non-zero exit status

**Comment by gfinak** [comment]
You don’t have gfortran installed or it’s pointing to the wrong version.

 

At the command line check 

`which gfortran`

to see what gfortran binary is getting called, if it’s installed. 

You can try to either set the gfortran environment variables defining the compiler in ~/.R/Makevars

or you may want to reinstall a binary from here:

https://gcc.gnu.org/wiki/GFortranBinaries#MacOS

depending on what version of MacOS you are running.

**Comment by SamGG** [comment]
I tested your file. Same warnings, although my flowWorkspace is 3.20.2. But those messages are only warnings. So I guess the following gating operations will run successfully. Unless I really need to get rid of such warnings, I will wait for the next release of bioconductor. It sounds safer for my setup. I wish you luck if you still want to go in the devel way.

**Comment by kdh4win4** [comment]
I tried to uninstalled wrong gnu fortran 6.3 version on my mac.
sudo rm -r /usr/local/gfortran /usr/local/bin/gfortran
Even though I uninstalled 6.3 version, Mac denied installing 6.1 version(for El Capitan OSx) because mac still think 6.3 version is in system. 
I made a ticket with IT team for this issue and will see how this could be resolved. 
Thank you for your time. 
I will keep posting.

**Comment by nreith** [comment]
brew install gcc

Then install.packages("cluster") works fine from within R.
