### ISSUE TITLE
Log-scale plot with "plotGate()" function ?

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/openCyto#134]
Is it possible to make log-scale plot with "plotGate()" function ?

**Comment by kdh4win4** [comment]
Axes like this figure. 
![screen shot 2017-03-24 at 11 17 01 am](https://cloud.githubusercontent.com/assets/12645005/24300636/7a6bc76c-1083-11e7-99d6-31f96cdc17fe.png)

**Comment by gfinak** [comment]
Can I suggest you try the [ggcyto](https://github.com/RGLab/ggcyto) package instead?
[rpubs link](https://rpubs.com/wjiang2/179697)

**Comment by kdh4win4** [comment]
Thank you. Greg. 
I have still some issues. 
ggcyto does not recognize column names;

ggcyto(gs, aes(x='CD16', y='CD56'), subset = "singlet")
**Error in .cpp_getGate(obj@pointer, sampleNames(obj), y) : CD16 not found!**
Actually, CD16 is partially matched with R780-ACD16-APCCy7
How do I have to change the name "CD16" ?

**Comment by mikejiang** [comment]
You should remove quotes from the variable names, see `?aes`

**Comment by kdh4win4** [comment]
There still an issue. 
Quotes are just fine for aes function I think.
Both has exactly same error message;
**ggcyto(gs, aes(x=CD16, y=CD56), subset = "singlet")**
**ggcyto(gs, aes(x='CD16', y='CD56'), subset = "singlet")**
Warning messages:
1: In getChannelMarker(frm, dim) :
  CD16 is partially matched with R780-ACD16-APCCy7
2: In getChannelMarker(frm, dim) :
  CD56 is partially matched with G780-ACD56-PECy7



[Rplot09.pdf](https://github.com/RGLab/openCyto/files/873509/Rplot09.pdf)

**Comment by kdh4win4** [comment]
I can not see any flow cytometry data on plots.

**Comment by mikejiang** [comment]
You were reporting the error message with the quotes last time, now the error is gone, what you see is just warning, which you can safely ignore.
There could be various reasons that you don't see the data. Check if your `singlet` indeed has events within the gate by `getPopStats(gs)`.
Also change the `xlim/ylim` by the actual data range , i.e. adding the layer `ggcyto_par_set(limits = "data")`

**Comment by kdh4win4** [comment]
Thank you, Mike. 
I did. but there still are issues.

fs <- read.ncdfFlowSet(fcs_files) 
gs <- GatingSet(fs)

> getPopStats(gs)
                                                                                                                       name
  1: NK ELISA DLB01 Total Ig SHIV gp145 ABL p5 mg mL Total Ig_DLB01 NK ELISA SHIV gp145 ABL p5 mg mL Tot Ig 6135 M0_022.fcs
  2: NK ELISA DLB01 Total Ig SHIV gp145 ABL p5 mg mL Total Ig_DLB01 NK ELISA SHIV gp145 ABL p5 mg mL Tot Ig 6135 M0_022.fcs
 
161:  NK ELISA DLB01 Total Ig SHIV gp145 ABL p5 mg mL Total Ig_DLB01 NK ELISA SHIV gp145 ABL p5 mg mL Tot Ig Nil Ag_026.fcs
162:  NK ELISA DLB01 Total Ig SHIV gp145 ABL p5 mg mL Total Ig_DLB01 NK ELISA SHIV gp145 ABL p5 mg mL Tot Ig Nil Ag_026.fcs
      Population    Parent  Count ParentCount
  1:    boundary      root 346678      350479
  2:     singlet  boundary 337293      346678
  3:      viable   singlet 319226      337293
  4:   nonNeutro    viable 203185      319226
  5:     CD19CD3 nonNeutro   5672      203185
 ---                                         
158:     singlet  boundary 332111      342939
159:      viable   singlet 308280      332111
160:   nonNeutro    viable 211921      308280
161:     CD19CD3 nonNeutro   5662      211921
162: CD16CD56dim   CD19CD3   5317        5662

> ggcyto(gs, aes(x=CD16, y=CD56), xlim =  c(-1e2, 1e4) , ylim = c(-1e2, 1e4), subset = "CD19CD3")
Warning messages:
1: In getChannelMarker(frm, dim) :
  CD16 is partially matched with R780-ACD16-APCCy7
2: In getChannelMarker(frm, dim) :
  CD56 is partially matched with G780-ACD56-PECy7
> myPars <- ggcyto_par_set(limits = list(x = c(-1e2, 1e4), y = c(-1e2, 1e4)))
[Rplot10.pdf](https://github.com/RGLab/openCyto/files/873662/Rplot10.pdf)

> pz <- ggcyto(gs, aes(x=CD16, y=CD56), subset = "CD19CD3")
Warning messages:
1: In getChannelMarker(frm, dim) :
  CD16 is partially matched with R780-ACD16-APCCy7
2: In getChannelMarker(frm, dim) :
  CD56 is partially matched with G780-ACD56-PECy7
> pz <- pz + myPars
> pz

**Comment by mikejiang** [comment]
Now you are switching to `CD19CD3` and I assume your `singlet` plot is working fine. Why don't you follow my example to set `limits='data'`? 

Also, your partially pasted code is very confusing, the first two lines of code just reads fcs files and creates an empty `GatingSet`, yet you are showing me the `pop stats` from another `GatingSet` that  has gates. I recommended you edit your post and enclose the code with appropriate language block, see https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by kdh4win4** [comment]
Including CD19CD3 and singlet, every plot is not working fine. 
Your example to set limits="data" has same issue. 
I am sorry for confusing you a lot. 
Just ignore first two lines of code, which are working well. I got right GatingSet. 
I could generate plots using "plotGate()" function. No problem to make plots with plotGate function. 
However, I could not do that with ggcyto function. The issue is that it seems like my GatingSet is not working well on ggcyto() function. 
The link you added before is very helpful. I appreciate it. Mike.

**Comment by kdh4win4** [comment]
```R
#load raw FCS
setwd("/some_directory/")
fcs_files <- Sys.glob('NK*.fcs') # This is set without Compensation fcs file.
fcs_files
fs <- read.ncdfFlowSet(fcs_files) # 36 set, # FSC-A, FSC-H, SSC-A, B515-A, V450-A, V525-A, R730-A, R780-A, G575-A, G660-A, G780-A, Time
gs <- GatingSet(fs)


library('openCyto')
gt_yo <- gatingTemplate("gt_080_y_m.csv") 
gating(gt_yo,  gs) 
```

**Comment by mikejiang** [comment]
I noticed that you did not compensate and transform the data before gating, could that be the cause?

**Comment by kdh4win4** [comment]
No, Mike. They already compensated fcs data and then gave the compensated ones.

**Comment by mikejiang** [comment]
How about the transformation?

**Comment by kdh4win4** [comment]
Well, the transformation may be fine because previous plots generated with plotGate() function shows fine figure. So, the process of compensation and transformation would have been successfully.

**Comment by mikejiang** [comment]
Can you send the example `GatingSet` for me to take a look?, e.g.
```r
gs_sub <- clone(gs[11])
save_gs(gs_sub , path = "./gsToSend") 
```

**Comment by kdh4win4** [comment]
[gsToSend.zip](https://github.com/RGLab/openCyto/files/876670/gsToSend.zip)
I appreciate it. Mike.

**Comment by mikejiang** [comment]
The `singlet` gate looks fine
```r
library(flowWorkspace)
library(ggcyto)
gs <- load_gs("/loc/no-backup/mike/shared/gsToSend/")
gh <- gs[[1]]
autoplot(gh, "singlet")
```
![image](https://cloud.githubusercontent.com/assets/1385649/24421594/85c50ee0-13ab-11e7-95cb-e50205936d72.png)

And as I pointed out, lacking of transformation step in your workflow was the cause of problems. If you plot the `1d` density of your data
```r
fr <- getData(gh)
autoplot(fr)
```
![image](https://cloud.githubusercontent.com/assets/1385649/24421618/9c5052f0-13ab-11e7-8197-a55629a41cdd.png)
All those fluorescence channels have signals piled up at low end and hard for visualization.
 So the right thing to do is to do the `logicle` transformation before doing any gating, e.g.
```r
chnls <- markernames(gh)
trans <- estimateLogicle(gh, chnls)
gs <- transform(gs, trans)
autoplot(getData(gs[[1]]))
```
Only after transformation, can you display the data properly with `ggcyto` or `plotGate`
![image](https://cloud.githubusercontent.com/assets/1385649/24422152/636c3650-13ad-11e7-8356-9273e9225ee3.png)

See more details about the discussion of transformation here https://github.com/RGLab/flowWorkspace/issues/206

I also recommend you to read the openCyto [vignette](https://bioconductor.org/packages/release/bioc/html/openCyto.html) (these html documenations) carefully, especially the `section 4` of the [Introduction doc](https://bioconductor.org/packages/release/bioc/vignettes/openCyto/inst/doc/openCytoVignette.html)

**Comment by kdh4win4** [comment]
Thank you very much. Mike
I will let you know soon how this transformation works in my fcs data. 
I appreciate it.

**Comment by kdh4win4** [comment]
markernames() function is not working for other gatingset type. 
Is there any reference solved issue which I can read for this issue?

**Comment by kdh4win4** [comment]
```R
> chnls <- markernames(gh)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘markernames’ for signature ‘"GatingHierarchy"’
```

**Comment by gfinak** [comment]
See here:
https://github.com/RGLab/flowWorkspace/issues/192

Not working how?
What do you mean by "other gatingset type"?
Post a reproducible example of your bug.

**Comment by gfinak** [comment]
Is flowWorkspace loaded? What version are you running?
What does
`showMethods("markernames")` return?

**Comment by kdh4win4** [comment]
I post reproducible gs which is not working well. 
[gsToSend 2.zip](https://github.com/RGLab/openCyto/files/887777/gsToSend.2.zip)

The "other gatingset type" is in issue #133 which was working well on markernames() function. 
flowWorkspace (version 3.16.16) is loaded. 

```R
> showMethods("markernames")
Function: markernames (package flowCore)
object="flowFrame"
```

**Comment by gfinak** [comment]
I think your flowWorkspace library is not loaded. 
From a clean R session:
```r
> showMethods("markernames")

Function "markernames":
 <not an S4 generic function>
> library(flowCore)
Warning message:
package ‘flowCore’ was built under R version 3.3.3 
> showMethods("markernames")
Function: markernames (package flowCore)
object="flowFrame"
object="flowSet"
> library(flowWorkspace)
Loading required package: flowCore
Loading required package: ncdfFlow
Loading required package: RcppArmadillo
Loading required package: BH
> showMethods("markernames")
Function: markernames (package flowCore)
object="flowFrame"
object="flowSet"
object="GatingHierarchy"
object="GatingSet"
object="ncdfFlowList"
> gs = load_gs("~/Downloads/gsToSend/")
loading R object...
loading tree object...
Done
> markernames(gs)
[1] "TNFa-FITC"                "IFNg-V450"                "Aqua LIVE/DEAD"           "CD3-AFL700"               "CD16-APCCy7"              "MIP1B-PE"                 "CD19/CD14 PECy5 Tricolor" "CD56-PECy7"              
```
