### ISSUE TITLE
mindensity issue

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/openCyto#136]
Dear Mike and Greg, 

```R
gs1 <- GatingSet(fs[1])
gs1t <- transform(gs1, trans)
read.csv("gt_080_yohann_macpro_1.csv")
gt_yohann_1 <- gatingTemplate("gt_080_yohann_macpro_1.csv") # for single set, key causion, 
gating(gt_yohann_1,  gs1t) 
plotGate(gs1t[[1]]) # 
```
![screen shot 2017-03-31 at 12 14 50 pm](https://cloud.githubusercontent.com/assets/12645005/24559195/ccfcf806-160b-11e7-9ef7-55dfa5b0a5b3.png)

```R
grid.arrange(plotGate(gs1t, "G660_n"), plotGate(gs1t, "G660_p"), ncol=2)
```
![screen shot 2017-03-31 at 12 15 03 pm](https://cloud.githubusercontent.com/assets/12645005/24559202/d10d7a24-160b-11e7-8581-6fee3b40e489.png)

**Comment by kdh4win4** [comment]
mindensity is not dividing clusters well.
Here is a gating template.
[gt_080_y_m_1.xlsx](https://github.com/RGLab/openCyto/files/886297/gt_080_y_m_1.xlsx)

**Comment by gfinak** [comment]
Your populations are not well separated. Perhaps try lowering the amount of smoothing (the “adjust” parameter).

**Comment by kdh4win4** [comment]
It does not working well. I tried to change 'adjust=' value from 2 to 1.5

**Comment by mikejiang** [comment]
I see you set `gate_range=c(3e2,7e2)` in template, which is at raw scale. You want to use the transformed scale here (or not specify it and let the algorithm determine t)

You can use `ggcyto` to display the `1d` density at transformed coordinates and quickly see how different `adjust` values affects the two peaks .
```r
 ggcyto(gs, aes(x =`G660`), subset = "nonNeutro") + geom_density(adjust = 0.5)
```

**Comment by kdh4win4** [comment]
I appreciate it. Mike. 
I solve this issue with your help. I just removed gate_range() function and could made what I want.  
If you don't mind, can I know how to see raw scale and transformed scale of fcs data ?

**Comment by mikejiang** [comment]
data is already stored at transformed scale once the transformation is done. `plotGate`  simply `inverse transform` axis labels (NOT the data) so that it display the numbers at raw scale.  To disable this behavior, you can set `raw.scale = F` when you `plotGate`

Again, it is more intuitive to use `ggcyto`, The one I showed you was `transformed` axis, to `inverse transform` to linear, simply add `axis_x_inverse_trans()` layer, e.g.
``r
p + axis_x_inverse_trans()
```

**Comment by kdh4win4** [comment]
Dear Mike, 
Can I know what I did wrong on plotGate() ?
```R
> grid.arrange(plotGate(gst[[1]],"CD16CD56dim"), plotGate(gst[[2]], "CD16CD56dim"), 
+              plotGate(gst[[3]],"CD16CD56dim"), plotGate(gst[[4]], "CD16CD56dim"),
+              plotGate(gst[[5]],"CD16CD56dim"), plotGate(gst[[6]], "CD16CD56dim"),
+              plotGate(gst[[7]],"CD16CD56dim"), plotGate(gst[[8]], "CD16CD56dim"),
+              plotGate(gst[[9]],"CD16CD56dim"), ncol=3) # "alias name"
Error in gList(list(wrapvp = list(x = 0.5, y = 0.5, width = 1, height = 1,  : 
  only 'grobs' allowed in "gList"
```

**Comment by kdh4win4** [comment]
It did not generate 3x3 matrix format plots.

**Comment by kdh4win4** [comment]
I just solved this grid.arrange issue by changing "[[]]" to "[]".  Thank you.

**Comment by mikejiang** [comment]
You should be able to do it with one-liner
```r
plotGate(gst[1:9],"CD16CD56dim" , layout = c(3, NA))
```
see `layout` section of lattice documenation for `?xyplot`

Again, it is more intuitive with `ggcyto`
```r
autoplot(gst[1:9],"CD16CD56dim") + facet_wrap(~name, nrow = 1)
```

**Comment by kdh4win4** [comment]
Thank you. Mike 
Can I ask one more question?
The FSC and SSC channel are not naturally transformed by transform() function. 
Do you know how to transform those channels ?

**Comment by gfinak** [comment]
@kdh4win4 you should not be transforming FSC and SSC. Those channels do not measure fluorescence and the data are not log-normal.

**Comment by kdh4win4** [comment]
Thank you. Dr. Greg Finak
