### ISSUE TITLE
How to get autogating result as excel file

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/openCyto#140]
Dear Mike and Finak, 
I produced gating plots.
Can I know how to make an excel file with this gating result. 
In this case, I would like to have G575-A positive percentage of each 120 samples. 
On each plot, positive percentage is shown. 
Here is the plot.
[opencyto_new_issue.pdf](https://github.com/RGLab/openCyto/files/930071/opencyto_new_issue.pdf)
Thank you.

**Comment by gfinak** [comment]
`getPopStats()` will return a table of cell population statistics that you can write to file.

```
library(xlsx) 
stats  =  getPopStats(mygatingset)
write.xlsx(x = stats, file = "population_statistics.xlsx", sheetName = "All_Stats", row.names = FALSE)
#alternately
write.csv(stats, file="population_statistics.csv", row.names=FALSE)
```

**Comment by kdh4win4** [comment]
It's great. I appreciate it.
