### ISSUE TITLE
How to get the outside of flowClust-circled area

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/openCyto#141]
Dear Mike and Finak, 

Can I know how to choose the outside of flowClust circled area ?
Is there a gating method for that ?
Thank you.

**Comment by mikejiang** [comment]
simply put `pop` column as `A-`, which indicates the negation of the `ellipseGate` fitted by `flowClust`. e.g.

|   alias  | pop | parent | dims    | gating_method | gating_args |
|:--------:|-----|--------|---------|---------------|-------------|
| nonLymph | A-  | root   | FSC,SSC | flowClust     | K=2         |

**Comment by kdh4win4** [comment]
It's so cool. Thanks.
