### ISSUE TITLE
How to change sample name 

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/openCyto#143]
Dear Mike and Finak, 

My fcs files have long sample names. 
gst_123 is a gatingset with long sample names.
Can I know how to make change the name for this S4 class ?
![screen shot 2017-04-21 at 2 24 18 pm](https://cloud.githubusercontent.com/assets/12645005/25291099/b3858930-269e-11e7-987a-e31ee21a01fa.png)

**Comment by mikejiang** [comment]
see doc ?`sampleNames<-`

**Comment by kdh4win4** [comment]
Thank you, Mike. I solved the issue.
