### ISSUE TITLE
plotGate issue ?

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/openCyto#145]
Dear Mike and Finak, 

For single set, The "**plotGate(gss1t[[1]],"V450_gate")** "works well. 
```R
gs1 <- GatingSet(fs100[1]) # one of 100 fcs files
gs1t <- transform(gs1, trans_123)
gt <- gatingTemplate("gt_080_y_m.csv") # for single set, 
gating(gt,  gs1t) 
plotGate(gss1t[[1]],"V450_gate") # ok
```

However, for 100 fcs file set, below code line does not working well.
```R
# gs100t is transformed one hundred gating set. 
plotGate(gs100t,"V450_gate") # error
Error in .cpp_getGate(obj@pointer, sampleNames(obj), y) : 
  V450+ not found!
```

Thank you.

**Comment by kdh4win4** [comment]
Other G660+, R730+, R780+, G780+ are working well on single set or one hundred fcs set

**Comment by mikejiang** [comment]
Your error message suggests it failed to find the gate that is named by `v450+`, yet your `plotGate` call is asking for `v450_gate`, which is contradicting the error message. So I am wondering if you are reporting it correctly.
Why don't you paste the original output of `traceback` right after your `plotGate`'s failure?

**Comment by kdh4win4** [comment]
```R v450_gate``` and ```R V450+ ``` both have the same issue in hundred fcs file gating. 

However, single sample fcs gating in hundred fcs group has no issue like this.

**Comment by gfinak** [comment]
As usual, you need to post working code, error messages, the relevant lines of your template and even a printout of the flowFrame that is failing.
We don't have enough information to help your right now.

**Comment by kdh4win4** [comment]
I guess there might be a conflict of same dim names, 'V450+' vs  V450+'
Thank you for your time.
