### ISSUE TITLE
Using more CPU and Memory

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/openCyto#146]
Dear Mike and Finak, 

For faster gating speed, I am searching a way how to speed up gating process.
I am gating more than 90 fcs samples. In near future, it might be more than 400-500 fcs samples. 
Gating for ninety samples usually took 15 minutes with 3GHz 8-Core Intel Xeon E5, 64 GB memory  1866 MHz desktop. 
By Activity Moniter software, it looks like using just one core for R auto-gating process.
Can I know how to use more CPU and memory for auto-gating ? Or is it impossible ?

**Comment by mikejiang** [comment]
type `?gating` and see the examples of `parallel` gating

**Comment by mikejiang** [comment]
BTW, I strongly recommend you to always seek the help from package vignette and help documents first. 
Only after these docs fail to answer your question, should you post here. Because that's the very reason we spend so much time writing those docs in the first place.

**Comment by kdh4win4** [comment]
Certainly, 
I appreciate your help.
