### ISSUE TITLE
Transform option

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/openCyto#148]
Dear Mike and Finak, 

I would like to change transform option. 
In 4th figure below, the "viable", has too compressed y-axis range. 
Can I know how to wide y-axis range between 0 and 100?
Thank you very much for your time.
[Rplot18.pdf](https://github.com/RGLab/openCyto/files/1011628/Rplot18.pdf)

**Comment by mikejiang** [comment]
If you are talking about how to adjust the range during the visualization, take a look at the [ggcyto vignettes](https://www.bioconductor.org/packages/release/bioc/vignettes/ggcyto/inst/doc/ggcyto.GatingSet.html#ggcyto_par_set) to learn how to set `limits`

**Comment by kdh4win4** [comment]
I solve this issue. Thank you very much, Mike
