### ISSUE TITLE
How to get gated-area

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/openCyto#149]
Dear Mike and Finak, 

Can I know how to get gated area as a value in R or csv file which include all cell's information in the alias which alias name is "**CD16pos**"? 
Thank you for your time.

**Comment by mikejiang** [comment]
look at `?getData`

**Comment by kdh4win4** [comment]
Thank you very much, Mike. 
I would like to get each individual cell's marker information for the further analysis. 
For example, 
```
cell_#               CD16        CD56      KIR        AQUA        FSC        SSC
40000023       400.34     12.12       0.3        100000     10000    10000
.                         .                 .              .                .               .                .
.                         .                 .              .                .               .                .
.                         .                 .              .                .               .                .
```
Thank you for your time.

**Comment by mikejiang** [comment]
`exprs(getData(gs[[1]], "CD16Pos"))`, this gives you the matrix with column names of `channel`, you will have to replace channel with `marker` by your self

**Comment by kdh4win4** [comment]
That's great, 
I appreciate it, Mike.
