### ISSUE TITLE
quadGate.tmix is not working well. 

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/openCyto#150]
Dear Mike and Finak, 
Sorry to bother you too much. 
Can I get an example how to use/write quadGate.tmix or quadGate.seq gating method in .csv gating template ?
Because I could not find many quadGate examples in template csv file and the quadGate.tmix in my csv template is not working at all. 
There is an error message;
```R
invalid number of channels for quadGate.tmix
```
However, it just has two channels. 
[gt_example.xlsx](https://github.com/RGLab/openCyto/files/1032873/gt_example.xlsx)
I appreciate your help.

**Comment by mikejiang** [comment]
put `*` in your `pop` column
