### ISSUE TITLE
Use "gating.template()" on data.table

### ISSUE THREAD

**Issue by kratschie** [RGLab/openCyto#151]
Hello,

I am working on a small app that allows the user to create a gating Template on html based textInput which is stored in an 'R' data.table(including all the needed columns). I would now like to use the opencyto's gating.Template() function to use the Users Input for automated gating without having the user saving the data.table as csv and read from there.

I could not find a way to read from data.table instead of csv so far. Is there a way?

Thanks!

**Comment by mikejiang** [comment]
Writing such small table to a temporary csv incurs very little overhead, this is exactly what [add_pop](https://github.com/RGLab/openCyto/blob/trunk/R/add_pop.R#L72-L77) API does .

If you really want to avoid that, you can wrap [this lines](https://github.com/RGLab/openCyto/blob/trunk/R/AllClasses.R#L365-L374) into your own convenient function.
