### ISSUE TITLE
Using flowJo workspace to gate FCS files

### ISSUE THREAD

**Issue by jmckib** [RGLab/openCyto#152]
I have a flowJo workspace .xml file, and I'd like to apply the compensations, transformations, and the gating from that xml file to a new set of FCS files. The gates from the xml file are just static gates that have been set in flowJo. @mikejiang gave some code to at least do the gating part here: https://github.com/RGLab/openCyto/issues/108#issuecomment-219805897 However, it no longer seems to work, as the GatingSet constructor for that signature is now defunct.

```
> GatingSet(gh, fcsFiles)
Error: '.local' is defunct.
```

Is there currently a way to do this?

**Comment by gfinak** [comment]
I believe you have found a bug. Congrats!
We'll fix this ASAP.
Best
Greg

**Comment by jmckib** [comment]
Thanks @gfinak. One question: once that is fixed, I assume it will take care of applying the static gates from a GatingHierarchy to a new set of FCS files, but will I still have to apply the compensation and transformations myself? Is there an easier way of applying the transformations to a new set of FCS files, besides calling `trans <- getTransformations(gh)` and then modifying the result into something accepted by `transform(new_gs, trans)`?

**Comment by mikejiang** [comment]
I've pushed the fix. That should take care of comp and trans as well as the gates.
