### ISSUE TITLE
simplify 'pop' column in csv template

### ISSUE THREAD

**Issue by mikejiang** [RGLab/openCyto#156]
Maybe it is time for us to consider restricting `pop` as a simple and generic quadrant-pattern-only string (e.g. `++`, `+`), @gfinak ? 
I know it will have some backward compatibility issue with the legacy template, but just felt it has been the known culprit in the past. We had enough questions and problems caused by it. (e.g. https://github.com/RGLab/openCyto/issues/155#issuecomment-332282002).

And we will have validity check for `dims` for `+-` signs.

**Comment by gfinak** [comment]
So the idea is no more marker or channel info there? I'm fine with that. I think it will be easier to explain.

**Comment by mikejiang** [comment]
The changes have been pushed. The code involves the `pop` pattern is now cleaner than it used to be. Also `-` can allowed in `dims` in any circumstance since it no longer messes with `pop` in those `refGate` cases.

To turn off this validity check for  the legacy template, simply set the global option, e.g.
```r
opt <- getOption("openCyto")
opt[["check.pop"]] <- FALSE
options(openCyto = opt)
```
