### ISSUE TITLE
CSV gating template option 1.4. pop="*"

### ISSUE THREAD

**Issue by PierreLebrun** [RGLab/openCyto#157]
Hello,

We just installed the OpenCyto 3.6 release (a new computer needed to be installed and we found the new version due to the automatic installer biocLite). Many thanks for the hard work on this package !
Unfortunately, our quadrantGate in our CSV gatingTemplate stopped working on lines like this one (blinded data) :

alias        ,pop,    parent, dims                ,  gating_method , gating_args ,,,,,
'A,B,C,D' , *   ,  stable   , FSC.A,SSC.A   , quadrantGate    ,                     ,,,,,  

> Error in .preprocess_row(this_row, strict = strict) :
>   'pop': stable should only contain the + and - symbols and must conform to the valid +/- or +/-+/- patterns!
>                       
> Please remove any other letters and correct the pop pattern!
>                       
> Or type ?openCyto.options to see how you can turn off the 'check.pop' flag in option('openCyto') to bypass this validiy check (Not recommended)

So, it seems that the '*' in _pop_ is causing issues... Documentation hasn't change (Except the red comment you added in release 3.5: http://bioconductor.org/packages/3.5/bioc/vignettes/openCyto/inst/doc/HowToWriteCSVTemplate.html), so we are unsure how to write a quadrantGate. Is that a bug, or an update that is not yet documented ?

Additionally, ?openCyto.options is returning no results in V3.6...

Thanks in advance,

Pierre Lebrun

**Comment by mikejiang** [comment]
I've added doc for `openCyto.options` (see https://github.com/RGLab/openCyto/blob/trunk/man/openCyto.options.Rd ). With regard to `pop` error, it is not a buy but a new rule introduced (see details #156 )
And I've verified there shouldn't be any issue with the current release (Here I am using built-in gating method `quadGate.seq`)
```r
> packageVersion("openCyto")
[1] ‘1.16.0’
> library(openCyto)
> dataDir <- system.file("extdata",package="flowWorkspaceData")
> gs <- load_gs(list.files(dataDir, pattern = "gs_manual",full = TRUE))
loading R object...
loading tree object...
Done
> add_pop(gs, alias = "A,B,C,D", parent = "CD3+", pop = "*", dims = "CD4,CD8", gating_method = "quadGate.seq", gating_args ="gFunc = 'mindensity'")
...
done
> library(ggcyto)
> autoplot(gs[[1]], c("A","B", "C", "D"))
```
![image](https://user-images.githubusercontent.com/1385649/32342265-17623e46-bfbd-11e7-9711-ffe5ab63c1c9.png)
I think it is rather the row of  your `stable` definition may need to be changed in `pop` column so that no other character is used other than `+` or `-`

**Comment by cjungR** [comment]
Sorry to piggyback off the thread here, but I have a similar question related to `pop` = "*":  

With regards to @mikejiang 's example above, how would we know which quadrants above are which as defined by  `alias` = "A,B,C,D" ? Would "A" be `++` (ie CD4+CD8+), "B" be `-+`, "C" be `+-`, and "D" be `--` just as if `pop` = `+/-+/-` ?

**Comment by mikejiang** [comment]
The name sequence in `alias` column doesn't know about the quadrants, they are simply assigned to the `multi-gates` generated by the gating function specified by `gating_method`. So, here in this case, it is `quadGate.seq` that determines the order of the four gates (quadrants), which can be in any order depending on implementation of the function.
