### ISSUE TITLE
Registering flowDensity gating in openCyto does not work.

### ISSUE THREAD

**Issue by BenPVD** [RGLab/openCyto#158]
Hi everybody,

I am trying to register gating methods from the flowDensity package to openCyto, but up to this point with no success.

I have read the threads here regarding registering flowDensity gating to openCyto using the following code:

`.flowDensity <- function(fr, pp_res, channels=NA, filterId="",...){
    if(length(channels)==2)
    flowDensity:::.flowDensity.2d(fr, channels = channels, ...)
  else
    flowDensity:::.flowDensity.1d(fr, channel = channels, ...)
  }
registerPlugins(fun = .flowDensity,
                methodName = "flowDensity",
                dep = 'flowDensity',
                'gating')`

This will create a registered "flowDensity" gate when executing the `listgtMethods()` command, but after executing the gating method within my gating template this error comes up:

`Error in flowDensity:::.flowDensity.2d(fr, channels = channels, ...) : 
  object 'remove.margins' not found`

I checked the flowDensity package and can't find `flowDensity.1d` or `flowDensity.2d`functions within the manual, so I tried to change the wrapper function which was posted here earlier. Again without success.

`Error in .densityGating(flow.frame = obj, channel, n.sd = n.sd, use.percentile = use.percentile,  : 
  formal argument "flow.frame" matched by multiple actual arguments`

Can anyone help?
Maybe simply post the code for registering the `flowDensity` gating to opencyto from the beginning to the end?
Additionally, I was trying to find the source code from the pre-registered gating functions in order to see how this works there, but commands like `UseMethod()`, `method()` or `stats:::` did not work. Any idea how to get the source code of the pre-registered gating methods of openCyto?

Thanks for your help!

**Comment by gfinak** [comment]
It looks like the .flowDensity.2d method needs to be updated to reflect the changes in .deGate2D (it is a copy of that method adapted for openCyto). It is missing the default remove.margins argument and perhaps others.

**Comment by BenPVD** [comment]
Thanks for the quick response.
If I understand correctly the .flowDensity2D method is a copy of the .deGate2D method adapted for openCyto?
Can you point out a way to approach this problem?
Where do I find the .deGate2D method?
Or where do I have to look for the missing but necessary arguments?
Can you also point out how to look at the source code of the pre-registered methods of the openCyto package? I guess that would help me understand the correct structure of the method implementations.
(Sorry, obviously only a user of openCyto and not a bioinformatician.)

Thanks!

**Comment by gfinak** [comment]
This is a fix the package maintainer needs to make.

**Comment by mikejiang** [comment]
both `.deGate2D` and `.flowDensity.2d` are private functions defined in `flowDensity` package. You can see the source by adding namespace prefix `flowDensity:::`.
Or view the source from bioc git mirror site
https://github.com/Bioconductor-mirror/flowDensity/blob/master/R/helper_functions.R#L118
https://github.com/Bioconductor-mirror/flowDensity/blob/master/R/openCyto_wrappers.R#L60

As @gfinak said, you should contact its maintainer(Mehrnoush Malek <mmalekes@bccrc.ca>) for the fix (which should be an easy one).

**Comment by BenPVD** [comment]
Okay, that deletes an item from my to-do-list!
Thanks for your help and quick response. I'll definitely check the source code to get a better sense what's going on and contact Mehrnoush Malek regarding the fix.
Thanks again!

**Comment by dbunsko** [comment]
I'm still getting the error `Error in flowDensity:::.flowDensity.2d(fr, channels = channels, ...) : object 'remove.margins' not found`. Was this issue ever resolved @BenPVD? I understand it's an issue with the flowDensity package maintainer.

I followed registering flowDensity using:
``` R
.flowDensity <- function(fr, pp_res, channels = NA, ...){
  if(length(channels)==2)
    flowDensity:::.flowDensity.2d(fr, channels = channels, ...)
  else
    flowDensity:::.flowDensity.1d(fr, channel = channels, ...)
}
registerPlugins(fun = .flowDensity, methodName = "flowDensity", dep = "flowDensity", "gating")
```

Package versions: `flowDensity_1.12.0, openCyto_1.16.1, flowCore_1.44.2`

Thanks!
