### ISSUE TITLE
Error when trying to register a plugin

### ISSUE THREAD

**Issue by laderast** [RGLab/openCyto#159]
I have some custom plugins that I've written for openCyto and I'm getting the following error with the new version (1.17.1)

```
registerPlugins(fun=.dnaGate,methodName='dnaGate', dep=NA,'gating')
 
 Error in .Call("unlockNamespace", PACKAGE = "openCyto", env) : 
  "unlockNamespace" not available for .Call() for package "openCyto" 
```

I have to confess that I'm not super strong on R's C integration, otherwise I'd try and fix this. Any thoughts?

**Comment by mikejiang** [comment]
It seems to me that your `openCyto` is not loaded (or installed) properly.Make sure run `library(openCyto)`  and `getNativeSymbolInfo("unlockNamespace", "openCyto")`, which should give you this
```r
$name
[1] "unlockNamespace"

$address
<pointer: 0x7fb4cbaac9d0>
attr(,"class")
[1] "NativeSymbol"

$package
DLL name: openCyto
Filename: R/x86_64-pc-linux-gnu-library/3.4/openCyto/libs/openCyto.so
Dynamic lookup: TRUE

attr(,"class")
[1] "NativeSymbolInfo"
```

**Comment by laderast** [comment]
Ah, ok. Got it to work, thanks!
