### ISSUE TITLE
Gating samples independently with different channels

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/openCyto#160]
Hi Mike and Greg,

I was wondering if there was any plan to support gating samples independently with different channels?

For example, if I have five samples each stained with an anti-CD4 antibody conjugated to different fluorochromes (e.g. APC, PerCP, PE Cy7, PE, APC Cy7), in situations such as this we do not want to gate the same channel in each of the samples to identify the CD4 T cell population.

It would be nice if we could supply a vector of channels in the gating template (in the order of the samples) all with the same alias (e.g. CD4 T cells) and perhaps the groupBy argument can be used to segregate samples? It would be awesome if this could work with both ID and 2D gating methods!

These types of experiments occur quite often, especially when adding antibodies to pre-existing panels which forces you to use different fluorochromes. It would be great if these samples could be analysed together!

This feature would also help in pre-gating compensation controls by matching the channels to each single stain control you could home in on the positive populations with the same alias and then export these populations to spillover().

Keep up the great work!

Kind regards,

Dillon Hammill

**Comment by mikejiang** [comment]
As long as `channel` is consistent (i.e. `B710-A` in the example below), you can use these `channel` names in your `dim` column of csv. Or if these `markers` share the same keyword `CD4` and it is uniquely identifiable, you can use that as well.
e.g. 
```r
P3     FSC-W         <NA> 262143.000    0.0000 262143.000
$P4     SSC-A         <NA> 262143.000    0.0000 262143.000
$P5  <B710-A>  CD4 PcpCy55   3671.475  426.3119   4097.787
$P6  <R660-A>     CD38 APC   3578.944  518.5215   4097.465
$P7  <R780-A>    CD8 APCH7   3217.039  877.4007   4094.440
```

**Comment by DillonHammill** [comment]
Oh yes of course!

I have assigned CD4 in desc slot to different channels in each sample and added CD4 in dims slot in gating template.

`template <- rbind(template,add_pop(
  gs, alias = "CD4 T Cells", pop = "+", parent = "Single Cells", dims = "CD4",gating_method = "mindensity",gating_args =
    "gate_range=c(0,100000)", collapseDataForGating = FALSE
))`

How would you plot the result of the gate for each sample with the channels being different in each sample? (I keep getting - don't know how to add o to plot when adding geom_gate("CD4 T Cells)). 

`autoplot(getData(gs[[1]], "Single Cells"),"CD4") +  scale_x_logicle() + geom_gate("CD4 T Cells")
Error: Don't know how to add o to a plot`

Thanks for your help.

**Comment by mikejiang** [comment]
`autoplot(gs, "CD4 T Cells")` should do it

**Comment by DillonHammill** [comment]
Yes I did try this but it seems to plot the same channel on the x axis for all the samples - the channel on the x axis should be different for each flowframe.
![image](https://user-images.githubusercontent.com/28646736/32977503-c31a5184-cc82-11e7-85f0-6b1951a9c83e.png)

**Comment by mikejiang** [comment]
If your `desc` column (marker) is consistent across files, you can swap it with `name` column so that they can be gated and plotted together. here is the convenient function you can use to achieve that,
```r
> library(flowIncubator)
> library(flowCore)
> data(GvHD)
> fr <- GvHD[[1]]
> fr
flowFrame object 's5a01'
with 3420 cells and 8 observables:
     name              desc range minRange maxRange
$P1 FSC-H        FSC-Height  1024        0     1023
$P2 SSC-H        SSC-Height  1024        0     1023
$P3 FL1-H         CD15 FITC  1024        1    10000
$P4 FL2-H           CD45 PE  1024        1    10000
$P5 FL3-H        CD14 PerCP  1024        1    10000
$P6 FL2-A              <NA>  1024        0     1023
$P7 FL4-H          CD33 APC  1024        1    10000
$P8  Time Time (51.20 sec.)  1024        0     1023
153 keywords are stored in the 'description' slot
> fr1 <- swapChannelMarker_flowframe(fr)
> fr1
flowFrame object 's5a01'
with 3420 cells and 8 observables:
                 name  desc range minRange maxRange
$P1        FSC-Height FSC-H  1024        0     1023
$P2        SSC-Height SSC-H  1024        0     1023
$P3         CD15 FITC FL1-H  1024        1    10000
$P4           CD45 PE FL2-H  1024        1    10000
$P5        CD14 PerCP FL3-H  1024        1    10000
$P6             FL2-A  <NA>  1024        0     1023
$P7          CD33 APC FL4-H  1024        1    10000
$P8 Time (51.20 sec.)  Time  1024        0     1023
153 keywords are stored in the 'description' slot
```

**Comment by DillonHammill** [comment]
Thanks Mike, I will give it a try.

Please can you add a pureR branch to flowIncubator as you did for cytoUtils - still experiencing compilation problems.

Thanks,

Dillon

**Comment by mikejiang** [comment]
Just copy and source the function in your script from here https://github.com/RGLab/flowIncubator/blob/master/R/flowWorkspace-methods.R

**Comment by DillonHammill** [comment]
Yeah that is what I have done - if I use fsApply to do apply this change to all flowFrames in the FlowSet I get an error:

`> Controls.Swap <- fsApply(Controls,swapChannelMarker_flowframe)
Error in asMethod(object) : 
  The individual flowFrames do not contain identical stains.`

**Comment by mikejiang** [comment]
they have to be in the same order, you can order the channel after the swapping, e.g.
```r
Controls.Swap <- fsApply(Controls, function(fr)
{
  fr <- swapChannelMarker_flowframe(fr)
  chnls <- colnames(fr)
  fr[, sort(chnls)]
}) 
```
If still not working, then you need to compare these frames to see which channel causes discrepancy and remove it if necessary.

**Comment by DillonHammill** [comment]
Hi Mike,

Still not working, I don't think that the swapping will work with CD4 assigned to different channels in each flowFrame - after swapping the colnames of each frame will always be different.

It would be nice if opencyto would look at each flowFrame to identify the channel matching the marker (dim) and use this channel (different for each flowFrame) for gating. Have you ever tried to gate flowFrames with the same colnames but different marker assignment (desc)?

Probably the easiest test would be to use single stain controls and use the desc column to identify which channel to use for each flowFrame (using a consistent name e.g. "Stained") and the pass this to opencyto with "Stained" as the dim. Each flowFrame should then be gated independently in a different channel. But at the moment I think it is only using the channel of the first flowFrame for all flowFrames?

Hope that we can find a way to achieve this!

Thanks again for your help,

Dillon

**Comment by mikejiang** [comment]
If non-stained channel aren't used and causing trouble, why not removing it by subsetting frame by column through `[` ?

**Comment by DillonHammill** [comment]
That would be fine for single stain controls but for samples with different panels (same colnames different markers) we will have to keep all channels (e.g. two different panels on a 7 colour machine).

**Comment by mikejiang** [comment]
It is not clear to me what the problem is now without a concrete example.

**Comment by DillonHammill** [comment]
Hopefully I explain it a bit better with a more detailed example:

Let's say you want to look at the activation of CD4 and CD8 T cells (activation markers include CD44 and CD69). In an older experiment you did not have a CD44 antibody and so you used PANEL 1 below. In a second experiment you obtain a CD44 antibody but the antibody is conjugated to Alexa Fluor 700-A clashing with the CD4 antibody in PANEL1 - so we switch CD4 antibody to fill the free channel (CD4 PerCP Cy5.5) giving us PANEL 2.

![image](https://user-images.githubusercontent.com/28646736/33045245-4b6800c6-cea0-11e7-9f2f-7b2d4117e480.png)

The gating strategy would be to identify singlets and then identify CD4 (x axis) and CD8 (y axis) T cells - however, the CD4 antibodies fluoresce in different channels Alexa Fluor 700-A or PerCP Cy5.5. So for fs[[1]] CD4 T cells should be gated as Alexa Fluor 700-A positive cells whilst in fs[[2]] CD4 T cells should be gated as PerCP Cy5.5 positive cells.

I would like to keep these flowFrames in the same flowSet (as they have the same channels (colnames)) and pass these to openCyto for gating.

If I add CD4 into the appropriate slot in desc for each flowFrame and use CD4 as dim for openCyto, for all flowFrames the CD4 T cells are gated in the Alexa Fluor 700-A channel (only correct for fs[[1]].

In this case I don't want to remove channels as they are required for further downstream analyses (e.g. CD44 and CD69).

Hopefully this make more sense. Basically openCyto is great for passing the same gating routine to samples but can we pass different gating routines to subsets of samples? or have openCyto identify the correct channel for each flowFrame based on the markers?

Thanks again,

Dillon

**Comment by mikejiang** [comment]
`flowSet` is used to represent the homogeneous data ,i.e. the same channels with consistent stains. The stain names doesn't have to be exact same but at least needs to be interpreted consistently (e.g. `CD4 xxx` and  `cd4 yyy` are ok, but `CD4` vs `CD44` is definitely conflicting and confusing). 

In your case, your `flowSet` violates this assumption and thus is not valid. Even if we change `openCyto` so that it can do your `CD4` and `CD8` gating, you will have to address the missing `CD44` issue in your first frame sooner or later in the downstream analyses if you would still pass the entire `flowSet` down to your pipeline. There will be lots of other problems down the road, e.g. plot, getData, etc

So I still think the data has to be prepossessed properly so that it is a valid `flowSet` instead of expecting the pipeline to treat it differently at each individual sample level.

 @gfinak can give the final verdict on this

**Comment by gfinak** [comment]
@DillonHammill The amount of work involved to support this is non-trivial since it touches on fundamental design decisions that were made in the early days of the core flow infrastructure development. I suggest you split your data into groups with consistent panels and maintain separate templates.

**Comment by DillonHammill** [comment]
Fair enough, probably asking too much from the software. I will stick to splitting up the flowSet and maintaining separate templates - this works well.

Thanks for your help.

Dillon
