### ISSUE TITLE
Errors in parseWorkspace() function 

### ISSUE THREAD

**Issue by yangkangyf** [RGLab/openCyto#161]
A flowjo workspace file (.wsp) could be imported into R using opencyto.  Please see [https://support.bioconductor.org/p/101761/#103653](url)
for the same problem for details.
The error showed: 
```
loading data: E:/test.fcs
Compensating
gating ...
Error in .cpp_gating(gs@pointer, mat, guid, gains, nodeInd, recompute,  : 
  FITC-A not found in flowData!
```
However,  FITC-A is indeed one of the parameters present.

**Comment by gfinak** [comment]
`sessionInfo()`, please.

**Comment by mikejiang** [comment]
This can occur in one scenario, where parameters could be changed (i.e. `Comp-FITC-A`) after compensation, and if there is still some gate that is defined on `FITC-A`, then the parser will complain.
But to verify, we need your wsp and FCS example file.

**Comment by yangkangyf** [comment]
@gfinak @mikejiang Thanks for your suggetions. The problem was solved.  May be some  parameters was changed. I used the origin .fcs and .wsp files and it was worked.
