### ISSUE TITLE
flowClust Transitional Gate - Negative Population

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/openCyto#162]
Hi Greg and Mike,

I am trying to replicate the gate below using a flowClust transitional gate:
![image](https://user-images.githubusercontent.com/28646736/33534234-56918b02-d8fa-11e7-9cc3-9a4ada3f878a.png)

I have tried a number of things in the gating template to try to achieve this (including setting target and min/max arguments) but the gate returned always gates the upper positive population. Is there a way to use a transitional gate to gate out a negative population?

I can do this easily with a traditional flowClust gate coupled to a boolGate but it is not perfect...
![image](https://user-images.githubusercontent.com/28646736/33534975-efbe0d74-d8fe-11e7-85e6-9b6b3e9269b1.png)

Excluding the population using a boolGate:
![image](https://user-images.githubusercontent.com/28646736/33535020-2c4fa4e6-d8ff-11e7-9363-2672b09885a5.png)

Thanks,

Dillon.

**Comment by mikejiang** [comment]
How about  transitional gate + boolGate?

**Comment by DillonHammill** [comment]
Yeah at is what I am trying to do. However the transitional gate always gates the top right population/s  (Q2) even with target = c(1,1) and max = c(3.5,3.5), I have also tried K = 1:6.

**Comment by mikejiang** [comment]
Do you mean the transitional gate can't gate out the entire top right region properly because of the extra small pop between APC (10^4-10^5) range?

**Comment by DillonHammill** [comment]
Yeah in some samples tgere is also a APC- PECy7high population that makes gating this with a transitional gate difficult. I thijnk it is easier to exclude double negative population instead...with a transitional gate ideally...

**Comment by mikejiang** [comment]
You can remove that small region so that you get cleaner UR for transitional gate,then apply the gate as `refGate` back to the original parent
 e.g.

alias | pop | parent | dim | gating_method | gating_args
-- | -- | -- | -- | -- | --
clean | - | p1 | APC | mindensity | gate_range=c(1e4,1e5)
transGate | + | clean | APC,PE | flowClust | transitional=TRUE,K=3
target | + | p1 | APC,PE | refGate | transGate

**Comment by DillonHammill** [comment]
Thanks Mike I will give it a try later today.

**Comment by DillonHammill** [comment]
So using the above template I can get a better gate for the POSITIVE population:
![image](https://user-images.githubusercontent.com/28646736/33590268-5026d168-d9d2-11e7-9761-aa9871c49b01.png)

But this gate does not encompass all the events I want to keep with quantile=0.999 - here is a different sample (collapseDataForGating=TRUE):
![image](https://user-images.githubusercontent.com/28646736/33590223-ff967ce4-d9d1-11e7-8141-132cf612b779.png)

Does transitional gate only return a gate at the upper end after the transition? Is it possible to put a transitional gate at the lower end before the transition, to gate just the APC-CY7- PE-CY7- (double negative cells)?

It would be great if I could construct the flowClust gate (as per first comment above) and add transitional=TRUE to get a broader rectangular gate that would encompass the events missed by the ellipsoidal flowClust gate.

**Comment by mikejiang** [comment]
If you are referring to the cells excluded by the first 1d helper gate at high end of `APC` , you can add  it back by `boolGate`

alias | pop | parent | dim | gating_method | gating_args
-- | -- | -- | -- | -- | --
\* | +/- | p1 | APC | mindensity | gate_range=c(1e4,1e5)
transGate | + | APC- | APC,PE | flowClust | transitional=TRUE,K=3
target | + | p1 | APC,PE | refGate | transGate
transitional | + | p1 |   | boolGate | target\|APC

**Comment by DillonHammill** [comment]
Not quite, I want to keep everything OUTSIDE of this gate:
![image](https://user-images.githubusercontent.com/28646736/33633429-e72e7cc2-da64-11e7-8f2d-e035c843d908.png)

Basically I want to know whether you can gate either side of the transition? It seems as if you can only gate events above the transition (Trans+)?
![image](https://user-images.githubusercontent.com/28646736/33633264-4fc97a9e-da64-11e7-9688-740d72a91fbd.png)

**Comment by mikejiang** [comment]
I didn't wrote `transitional` version of `flowClust` so can't comment on that. But seems to me a legitimate feature request if it doesn't already have. @gfinak ?

**Comment by gfinak** [comment]
I'd have to look at the code, it was written by a post doc in the lab a few years ago. But it should be doable to simply negate the gate.

**Comment by mikejiang** [comment]
After looking into the code, it turns out `transitional_angle` is the argument that does the trick, see https://github.com/RGLab/openCyto/blob/trunk/R/gating-functions.R#L561-L577
The doc is vague on this, which I will have to add a note for it.
Here is the example 
```r
library(openCyto)
library(ggcyto)

data("GvHD")
fs <- GvHD[1]
gs <- GatingSet(fs)
gh <- gs[[1]]
trans <- estimateLogicle(gh, markernames(gh))
gs <- transform(gs, trans)

add_pop(gs, alias = "trans_pos"
          , dims = "FL2-H,FL4-H"
          , parent = "root"
          , gating_method = "flowClust"
          , gating_args = "K=2, transitional = T, translation = 0.5
           ,transitional_angle = pi*.25")
autoplot(gs, "trans_pos")
```
![image](https://user-images.githubusercontent.com/1385649/33681624-f67b5f3c-da79-11e7-968d-aa63861123bf.png)

Now change the `angle` 
```r
add_pop(gs, alias = "trans_neg"
        , dims = "FL2-H,FL4-H"
        , parent = "root"
        , gating_method = "flowClust"
        , gating_args = "K=2, transitional = T, translation = 0.1
        , transitional_angle = pi*1.25")
autoplot(gs, "trans_neg")
```
![image](https://user-images.githubusercontent.com/1385649/33681587-daa8c8e4-da79-11e7-9ec1-a39ebfcb4003.png)

**Comment by DillonHammill** [comment]
Thanks Mike, I can now get a negative gate but it is proving difficult to position correctly - I might stick to the traditional flowClust gate.
![image](https://user-images.githubusercontent.com/28646736/33690544-1277a916-db38-11e7-9f9f-937f4be45ff5.png)

On a separate question, is there the possibility of a adding a width argument to flowClust gate - so that the user can adjust the width of the ellipse (quantile changes both length and width)? It would be nice if you had control over both dimensions independently...

**Comment by mikejiang** [comment]
You can tweak `translation` argument to adjust the position of that diagonal bar. Also you want to make sure the appropriate number of cluster (`K`) and `target` is selected. The good way to fine tune these parameters is to run the `gate_flowClust_2d` function separately on the selected `flowFrame` and turn on the `plot` switch to visually check the clustering results.

For the question of `flowClust`, please post a separate issue and mention Greg

**Comment by DillonHammill** [comment]
Success! I got to work playing around with` gate_flowClust_2d`, the plots are very useful!
![image](https://user-images.githubusercontent.com/28646736/33696102-bdcfaae0-db54-11e7-90ed-9eee9f4bbcf3.png)

![image](https://user-images.githubusercontent.com/28646736/33695968-282bd6e4-db54-11e7-8cac-e4ac81952199.png)

Here is the final entry in the gating template...
`template <- rbind(template, add_pop(
  gs, alias = "Remove", pop = "+", parent = "Live", dims = "APC-Cy7-A,PE-Cy7-A",gating_method = "flowClust", gating_args ="K=1,target=c(1,1),max=c(3.5,3.5),translation=0,transitional=TRUE,transitional_angle=1.25*pi",collapseDataForGating = TRUE
))`

Thanks Mike!
