### ISSUE TITLE
Tmix2DGate Error

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/openCyto#165]
Hi Greg and Mike,

I am playing around with tmix2DGate, which seems to work well when providing two TRANSFORMED channels. When I provide a transformed channel and a linear morphology channel (e.g. FSC-A) I keep getting an error - which seems to originate in `getEllipseGate`.

![image](https://user-images.githubusercontent.com/28646736/33697435-05aa434c-db5b-11e7-91b5-b25cabb6917d.png)

Thanks again for your help!

**Comment by mikejiang** [comment]
It is probably due to the unsuccessful clustering from `flowClust` . I've added the `plot` switch so you can visualize the `tmixture clustering` outcome for the diagnostic purpose. Please post on `flowClust` github page for the further question regarding to the usage of `flowClust`,

**Comment by gfinak** [comment]
You generally shouldn't be clustering a linear and fluorescent channel
using flowclust. The scales are so different that you'll often run into
numerical issues estimating the covariance matrix.

Greg Finak
