### ISSUE TITLE
Kmeans Plugin for openCyto

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/openCyto#167]
Hi Mike,

I would really like to construct a Kmeans plugin for openCyto to gate multiple populations in a single dimension.

I was hoping that you would be able to guide me through the process if it is possible?

Thanks again Mike!

Dillon Hammill

**Comment by mikejiang** [comment]
Here are some links for your reference
http://rpubs.com/wjiang2/188182
http://rpubs.com/wjiang2/194332

**Comment by DillonHammill** [comment]
Thanks Mike.

**Comment by DillonHammill** [comment]
Hi Mike,

I am still trying to write a wrapper for multiple gates in a single dimension. I would like to use a method similar to mindensity2 but return multiple gates.

I think using splines as you have done for .improvedMindensity can identify cutoff points using the first derivative, how do I convert this vector of cutoffs (minima_xcoords) into gates? Can we construct multiple rectangleGates?

Here is an example of the gates I hope to get:

![image](https://user-images.githubusercontent.com/28646736/36768724-a11dc19e-1c94-11e8-9039-e84c89f5ce81.png)

**Comment by mikejiang** [comment]
Use `filters` container to wrap multiple gates , again, look at the links I provided above.
Type `?rectangleGate` to see how to construct 1d rectangleGate from cutoffs. Here is some more examples
https://github.com/RGLab/openCyto/blob/trunk/R/gating-functions.R#L1116-L1129
https://github.com/RGLab/openCyto/blob/trunk/R/gating-functions.R#L667-L681

**Comment by DillonHammill** [comment]
Thanks Mike.

I can accomplish this for a set number of gates (e.g. 6 in this case) but how can I construct gates if there are 8 populations?

For example I will include a K argument (number of populations) so the length of minima_xcoords will differ - so we may want to construct a different number of gates? I can run through values of K manually but is there a nicer way of doing this?

For example:
`` K = 6
g <- c(60,102,135,165, 204) # vector of cutoffs

if(K=6) {
coords <- list(p1 = list(c(-Inf, g[1]), c(-Inf, Inf))  # not sure if y coordinates are necessary
                     , p2 = list(c(g[1], g[2]), c(-Inf, Inf))
                     , p3 = list(c(g[2], g[3]), c(-Inf, Inf))
                     , p4 = list(c(g[3], g[4]), c(-Inf, Inf))
                     , p5 = list(c(g[4], g[5]), c(-Inf, Inf))
                     , p6 = list(c(g[5], Inf), c(-Inf, Inf))
                     )
} else if (K = 8) {
coords <- list(p1 = list(c(-Inf, g[1]), c(-Inf, Inf))  # not sure if y coordinates are necessary
                     , p2 = list(c(g[1], g[2]), c(-Inf, Inf))
                     , p3 = list(c(g[2], g[3]), c(-Inf, Inf))
                     , p4 = list(c(g[3], g[4]), c(-Inf, Inf))
                     , p5 = list(c(g[4], g[5]), c(-Inf, Inf))
                     , p6 = list(c(g[5], g[6]), c(-Inf, Inf))
                     , p7 = list(c(g[6], g[7]), c(-Inf, Inf))
                     , p8 = list(c(g[7], Inf), c(-Inf, Inf))
} ... and so on .....

gates <- lapply(coords, function(coord){
names(coord) <- as.character(channel)
rectangleGate(coord)
})

filters(gates)
}
``
Thanks for your help.

**Comment by gfinak** [comment]
Maybe I'm missing something but can you not build up the list of gates programmatically (i.e. in a loop)?

**Comment by DillonHammill** [comment]
Something like this?

`p <- list()`
`for( i in 1:length(g)){`
`p[i] <- list(c(g[i],g[i+1]))`
`}`

Then add first and last gates with -Inf and Inf separately?

**Comment by gfinak** [comment]
Yes, that's what I had in mind.

**Comment by DillonHammill** [comment]
Great thanks Greg! 

So I have constructed the list of coordinates for gating, I then added to the channel to the names and use lapply to construct rectangleGates but encounter a problem:

`names(coords) <- rep(channel,length(coords))`
  
`gates <- lapply(coords, function(coord){`
   ` rectangleGate(coord)`
  `})`

Error additional arguments have to be named.

Any idea why this might be happening?

![image](https://user-images.githubusercontent.com/28646736/36822033-0c1ae994-1d4a-11e8-98f7-d735453b0f44.png)

**Comment by gfinak** [comment]
I think the `names` need to be applied to the nested list elements, not the top level. 
In Mike's examples:
```
gates <- lapply(coords, function(coord){
            
      names(coord) <- as.character(channels)
      rectangleGate(coord)
    })
```
he loops over the list and assigns names to the interior list of coordinates.

**Comment by DillonHammill** [comment]
I had tried this originally but get the same error:

![image](https://user-images.githubusercontent.com/28646736/36822296-72ddf94a-1d4b-11e8-9965-638314d5b6a0.png)

**Comment by DillonHammill** [comment]
Is there an issue with the structure of my `coords`?

![image](https://user-images.githubusercontent.com/28646736/36822422-14b4abe2-1d4c-11e8-80c4-c29cfb18f525.png)

**Comment by gfinak** [comment]
I'm just looking into it, I'll post shortly.

**Comment by DillonHammill** [comment]
Thank you

**Comment by gfinak** [comment]
This will do it:

**Comment by gfinak** [comment]
This will do it:
```
g=seq(1,10)
# coords is an empty list
coords <- list();

#first element of the list is itself a list
coords[[1]] = list(c(-Inf,g[1]))

#iterate over remaining elements and assign to them
for(i in 1:length(g)){
  coords[[i+1]] <- list(c(g[i],g[i+1]))
}
#we have a list of lists.
coords

#last element
coords[[length(g)+1]] <- list(c(g[length(g)], Inf))

library(openCyto)

#loop over list and assign the channel to be gated each sub-element
#return one gate per list element
gates <- lapply(coords, function(coord){
  names(coord) = "A"
  rectangleGate(coord)
})
#gates is a list of gates.
gates
```

**Comment by DillonHammill** [comment]
Perfect thanks Greg, I was just missing double square brackets!

**Comment by DillonHammill** [comment]
I have successfully added the function as a plugin! 

In terms of the gatingTemplate I thought pop should be set to "*" for returning multiple populations?

Keep getting error saying population name should end with '+' or '-' ?

**Comment by mikejiang** [comment]
Post your template and the error message

**Comment by DillonHammill** [comment]
`> template <- add_pop(`
  `gs, alias = "*", pop = "*", parent = "root", dims = "Comp-Alexa Fluor 488-A", gating_method =` `"multimindensity", gating_args = "K=6"`
` )`
`...`
Error in .gating_gtMethod(x, y, ...) : 
  Invalid population name! Name should end with '+' or '-' symbol.

**Comment by mikejiang** [comment]
I pushed the fix and try again.

**Comment by DillonHammill** [comment]
Another error:

`> template <- add_pop(`
`gs, alias = "*", pop = "*", parent = "root", dims = "Comp-Alexa Fluor 488-A", gating_method =` `"multimindensity", gating_args = "K=6"`
` )`
`...`
`Error in .cpp_addGate(ptr, sn, filterObject, parent, name) : `
  `defaultRectangleGate already exists!`

**Comment by mikejiang** [comment]
When you set `alias` to `*`,  you are telling the parser to derive the population names from the `filterId` of each `rectangeGate` generated by your `multimindensity` function.

So you either need to set `filterId` when you construct the `rectangelGate` or explicitly name the populations (through `alias`) as you did in your previus post

**Comment by DillonHammill** [comment]
Sorry that was a typo...

Thanks this works fine now!

One last question, is it possible to apply a refGate to multiple populations in a single line of the gatingTemplate? Can we supply multiple parent populations?

**Comment by mikejiang** [comment]
Currently one line per parent. If it's proved to be useful, we can add that support. For now, simply wrapping `add_pop` call into the loop should be straightforward to achieve the goal.

**Comment by DillonHammill** [comment]
I can also see this being useful when gating proliferation data where you gate based on number of divisions and apply same downstream gating strategy to each population to look at activation markers etc.

**Comment by mikejiang** [comment]
Loop would be something like this
```r
for(p in parents)
  add_pop(gs, alias = "your_new_gate", pop = "+", parent = p, dims = "Comp-Alexa Fluor 488-A", gating_method = "refGate", gating_args = "your/refgate/path")
```
I am closing this issue and you can post this feature request in new issue

**Comment by DillonHammill** [comment]
Thanks for all your help.
