### ISSUE TITLE
Feature Request: Allowing Multiple Parent Populations in GatingTemplate Entry

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/openCyto#168]
Would it be possible to add support for including multiple parent populations in a GatingTemplate entry?

For example, if we have cells labelled with the proliferation dye CFSE we may want to gate distinct populations based on their CFSE intensity (CFSE intensity decreases with subsequent divisions). Let say that 6 populations are identified named A-F, we may then want to apply gates to each of these populations to look at activation markers etc. It would be nice if you could simply set `parent = "A,B,C,D,E,F"` for the activation gates rather than having to construct these individually.

**Comment by mikejiang** [comment]
Done. Let me know if it works for you.

**Comment by DillonHammill** [comment]
Hi Mike, 

Thanks for adding this, I will be testing this soon.

Just wanted to check whether refGate supports multiple gates? E.g. if I want to save my multimindensity gates to a refGate is this possible?

**Comment by DillonHammill** [comment]
Looks like multiple parents is working now!

![image](https://user-images.githubusercontent.com/28646736/36953667-99b5b224-2070-11e8-8b47-fd0193a0c2ff.png)

![image](https://user-images.githubusercontent.com/28646736/36953687-c416e3c6-2070-11e8-80e6-091d9b6b9f7d.png)

**Comment by mikejiang** [comment]
Yes, any gating method including `refGate` is supported

**Comment by DillonHammill** [comment]
Thanks Mike!
