### ISSUE TITLE
Preprocessing Function to Restrict FlowSet by pData

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/openCyto#174]
Hi Guys,

I am trying to construct a preprocessing function which restricts the flowSet based on pData. For example, I would like to find all the control samples, coerce them into a flowFrame and sample using the subSample argument. I would then like to apply this gate to all the samples.

pData would have column called "stain" with values "unstained", "autofluorescence", "FMO" and "stained". Let's say I want to use the "autofluorescnce " samples collectively for the gating - how would I go about this?

Would such a processing function only need to supply the restricted flowSet? Or are coercion and sampling also required to result in a flowFrame which is passed to the gating function?

Thanks again!

Dillon

**Comment by gfinak** [comment]
The groupBy column can take pData variables to help you with that.
You might need to have custom gating and / or custom preprocessing.. we'll get back to you about this.

**Comment by mikejiang** [comment]
Do you mean you want collapse all `autofluorescnce` samples into a single `flowFrame` and randomly subsample it. Then apply the gating template on this single `flowFrame` to generate the gates and simply copy the entire gating tree (static gates) to the rest of all other samples?

**Comment by DillonHammill** [comment]
That is correct!

**Comment by mikejiang** [comment]
You can do something like this
```r
pd <- pData(fs) #by the way, ncdfFlowSet is favored over flowSet for better performance and efficiency
idx <- pd[["stain"]] == "autofluorescnce"
sn <- rownames(pd)[idx]
fr <- as(fs[sn], "flowFrame")
fr <- Subset(fr, SampleFilter(size = 1e5))
fs1 <- as(fr, "flowSet")
gs1 <- GatingSet(fs1)
gh <- gs1[[1]]
#assume compensation and transformation were already done prior to coersing
#then apply your gating template

#then copy the gates from the existing gh to the rest of data
gs <- GatingSet(gh, fcs_file_names, fcs_path)
```

**Comment by DillonHammill** [comment]
We can close this now. This issue is solved with new DrawGate methods.
