### ISSUE TITLE
Access GatingTemplate Entries within Plugin Function

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/openCyto#175]
Hi guys,

Just wondering if there is a way to access entries in the `GatingTemplate` within a plugin gating function? For example would it be possible to extract the `alias` entry to determine the number of expected gates or population names?

Thanks again!

Dillon``

**Comment by mikejiang** [comment]
plugin is designed to be agnostic to the template itself, all it does is to take a flowFrame and spit out the gate or gates.
Can you elaborate your use case?

**Comment by mikejiang** [comment]
As you can see https://github.com/RGLab/openCyto/blob/trunk/R/pluginFramework.R#L49-L52
these are the current formals expected by plugins, `alias` is not one of them. The idea is to keep it as clean as possible. We have to think about this before adding it to the framework. For drawGate case, I still prefer to keep this interactive thing outside of the template gating process.

**Comment by mikejiang** [comment]
Also, shouldn't the number of gates be determined by the gating function itself? You can simply leave the alias as `*` and set `filterId` slot to your desired name for each gate object generated in your function.

**Comment by DillonHammill** [comment]
Ok fair enough. I made many updates to the plugin, I will let you know when I have pushed the changed to GitHub.
