### ISSUE TITLE
no manual.xml in extdata

### ISSUE THREAD

**Issue by abbatidanilo** [RGLab/openCyto#178]
Hello RGLab,

I am trying to dig into the openCyto package and I am having trouble loading the "_manual.xml_" as depicted in the vignette trough the following commands:

_flowDataPath <- system.file("extdata", package = "flowWorkspaceData")
wsfile <- list.files(flowDataPath, pattern="manual.xml",full = TRUE)
wsfile_

I installed the flowWorkspace package but in the _extdata_ directory I have only the _empty_workspace_9.2.xml_ and not the _manual.xml_ file as expected

I also tried to check under the flowWorkspace repository but with no success (the install_github(_"flowWorkspace/RGLab", ref="trunk"_) command doesn't work) 

could you help me?

thanks

cheers

Danilo Abbati

**Comment by gfinak** [comment]
The package you need to install is called "flowWorkspaceData".

**Comment by abbatidanilo** [comment]
many thanks Greg
