### ISSUE TITLE
Extracting entire gatingTemplate from GatingSet

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/openCyto#179]
Hi @gfinak and @mikejiang,

Is there an easy way to extract the entire gatingTemplate from a GatingSet/GatingHierachy? I am aware of `templateGen` but I need to extract gating_method and gating_args as well.

Regards,
Dillon

**Comment by gfinak** [comment]
There is no gating method or gating args associated with a gating set. It's
not possible to reconstruct the template with full arguments and gating
methods directly at this time.

Greg Finak

**Comment by DillonHammill** [comment]
Ok, thank you. I have a work around for the mean time.

Cheers,
Dillon

**Comment by DillonHammill** [comment]
It would be nice if the `add_pop` entries were attached to the `GatingSet` as you add them in a `gs@template` slot for example. Then the entire template can be extracted from the `GatingSet`. Maybe this might be possible?

**Comment by mikejiang** [comment]
`add_pop` returns a row of the current gating information and you can use `rbind` to collect and build the template as you go

**Comment by DillonHammill** [comment]
Hi @mikejiang,

Yes this is how I construct the template normally, I am just wondering if there is way to get this information from the `GatingSet` directly if you don't have access to the template?

I think I can add the add_pop entries to a new slot in the GatingSet as I construct the gates? something like this...

```{r}
row <- add_pop(gs, alias, pop, channels etc.)
gs$template <- row

# New entry
row2 <- add_pop(gs, alias, pop, channels etc.)
gs$template <- rbind(gs$template,row2)

# Extract the entire template from gs
template <- gs$template
```

**Comment by mikejiang** [comment]
`GatingSet` was designed as the lower level of data structure that stores the tree of actual gates and intended to be agnostic about how these gates were generated (by template or by parsing xml). I am not sure if it is the best thing to do by adding template information to `GatingSet`.

**Comment by DillonHammill** [comment]
I guess the best way is to go through saving and reloading the gatingTemplate csv file?

```{r}
template <- add_pop(gs, ....)
write.csv(template, "gatingTemplate.csv")

# Load in file and add gate
template <- read.csv("gatingTemplate.csv")
template <- rbind(template, add_pop(gs, ...))
```

**Comment by DillonHammill** [comment]
`getGate()` can be used to extract gates from GatingSet
