### ISSUE TITLE
Quadrant gates are not showing up

### ISSUE THREAD

**Issue by jfreimer** [RGLab/openCyto#185]
Hi,
I gated my files in FlowJo and then imported into R with openCyto. For samples with just 1 gate, it shows the red outline of that gate. However, for my quadrant gates, plotGates only displays the percentage, but not the actual gate. Do I need to specify something else for the quadrant gates?
Thanks

`plot(gh)`
`plotGate(gh)`
`plotGate(gh,
         c('Q1: mCherry- , GFP+',
           'Q2: mCherry+ , GFP+',
           'Q3: mCherry+ , GFP-',
           'Q4: mCherry- , GFP-'),
         merge = T,
         xlim = c(0, 300),
         ylim = c(0, 300))`

![plot1](https://user-images.githubusercontent.com/7303848/46892261-a9094600-ce21-11e8-9405-c8d6e0342e2f.png)
![plot2](https://user-images.githubusercontent.com/7303848/46892263-a9094600-ce21-11e8-9203-7c1344da4a8c.png)
![plot3](https://user-images.githubusercontent.com/7303848/46892264-a9a1dc80-ce21-11e8-94f7-fe48595802c0.png)

**Comment by jfreimer** [comment]
I can see them if I use ggcyto with the following command:
`autoplot(gh, nodes[5:8], bins = 100)`

**Comment by mikejiang** [comment]
`plotGate` is the old viz tool built on lattice and thus we no longer actively maintain and support it.
