### ISSUE TITLE
FSC and SSC scale changed after export fcs file

### ISSUE THREAD

**Issue by mimisikai** [RGLab/openCyto#186]
The purpose of this code is aiming to consistent the fcs channels in bunch of files. But after exporting the new fcs file, the FSC and SSC scale totally changed. Files send out to your email separately due to confidentiality. 

library(openCyto)
library(ggcyto)
library(data.table)

#---------------------------------------------------------------------------------------------------------------------------------------------------#
# Raw data clean up
# The raw fcs files are pretty messy, unmatched channels(fluorochrome/dye), unmatched compensations, unstandardized sample name et al
# In this step, we create channel matching map to consolidate unmatched dye to unique channel; remove some unused compensations; and rename the file
#---------------------------------------------------------------------------------------------------------------------------------------------------#
# making a channel map to match all mismatched dys
map = data.frame(alias = c("FITC-A","PerCP-Cy5-5-A","V450-A","V500-A","BV605-A","BV650-A","Alexa Fluor 647-A","Alexa Fluor 700-A","APC-Cy7-A","PE-A","PE-Cy7-A"),
                 channels = c("FITC-A, Alexa Fluor 488-A",
                              "PerCP-Cy5-5-A, PerCP-A, ef710-A",
                              "BV421-A, V450-A, ef450-A, Pacific Blue-A",
                              "V500-A, AmCyan-A, BV510-A",
                              "BV605-A, Qdot 605-A",
                              "BV650-A, Qdot 655-A",
                              "Alexa Fluor 647-A, APC-A",
                              "Alexa Fluor 700-A",
                              "APC-Cy7-A, APC-H7-A",
                              "PE-A",
                              "PE-Cy7-A"))

# read ALL samples to clean up the data
# Load the raw data
mainPath = "H:/CAT Project 1-McMaster/3 Tmr Rename/Before rename/batch1"
FCS_rawfile_Tmr_ALL = read.ncdfFlowSet(list.files(mainPath, recursive = TRUE,full.names = TRUE), channel_alias = map)

# remove some compensation columes contain unmatched channels
for (i in 1:length(FCS_rawfile_Tmr_ALL))
{
  comp_col = colnames(FCS_rawfile_Tmr_ALL[[i]]@description$SPILL)
  idx = setdiff(comp_col, as.character(map$alias))
  
  if (length(idx) > 0){
    print(FCS_rawfile_Tmr_ALL[[i]]@description$`TUBE NAME`)
    re = match(idx,comp_col)
    FCS_rawfile_Tmr_ALL[[i]]@description$SPILL = FCS_rawfile_Tmr_ALL[[i]]@description$SPILL[-re,-re]}
}

# exprot all sample names
# OriSampleName = sampleNames(FCS_rawfile_Tmr_ALL)
# write.csv(OriSampleName, file = "C:/Users/jhou/Desktop/testing/OriSampleNameTmr.csv")

# Assign the new name to replace the old name, that's done in the excel manually

# read in the name match
SampleNameListTmr = read.csv("C:/Users/jhou/Desktop/testing/SampleNameListTmr.csv", stringsAsFactors = FALSE)

# rename the FILENAME in the keyword and rename the fcs files and rewrite the fcs into disk for further 
for (i in SampleNameListTmr$Old){
  newN = subset(SampleNameListTmr, SampleNameListTmr$Old == i)[['New']]
  FCS_rawfile_Tmr_ALL[[i]]@description$FILENAME = newN
  FCS_rawfile_Tmr_ALL[[i]]@description$`$FIL` = newN
  FCS_rawfile_Tmr_ALL[[i]]@description$`TUBE NAME` = newN
  write.FCS(FCS_rawfile_Tmr_ALL[[i]], paste("C:/Users/jhou/Desktop/testing/",newN,sep = ""))
}

**Comment by mikejiang** [comment]
Can you save and attach the example `flowFrame` object as an rds file by `saveRDS` right before your `write.FCS` call?

**Comment by mimisikai** [comment]
Do you need the rds file? As attached.

**Comment by mikejiang** [comment]
Yeah, I'd like to reproduce and trouble shoot your problem.

**Comment by SamGG** [comment]
My two cents is starting by checking the flowCore version.
what's the result of `packageVersion("flowCore")` ?

**Comment by mimisikai** [comment]
latest version 1.46.2

**Comment by SamGG** [comment]
I don't see any openCyto in your code.
Because of the final write.FCS, did you try to update flowCore to 1.47.5?

**Comment by mimisikai** [comment]
Updated all to the latest version but do not help.

**Comment by mimisikai** [comment]
same sample, the plot of FSC vs SSC before and after exporting 

![before](https://user-images.githubusercontent.com/4881411/47039960-f7785680-d139-11e8-9ab2-4f6a6a11a310.png)


![after](https://user-images.githubusercontent.com/4881411/47039962-fa734700-d139-11e8-8e08-8f693b990705.png)

**Comment by mikejiang** [comment]
@mimisikai , I can't reproduce it since your code gives me the error
```r
> map = data.frame(alias = c("FITC-A","PerCP-Cy5-5-A","V450-A","V500-A","BV605-A","BV650-A","Alexa Fluor 647-A","Alexa Fluor 700-A","APC-Cy7-A","PE-A","PE-Cy7-A"),
+                  channels = c("FITC-A, Alexa Fluor 488-A",
+                               "PerCP-Cy5-5-A, PerCP-A, ef710-A",
+                               "BV421-A, V450-A, ef450-A, Pacific Blue-A",
+                               "V500-A, AmCyan-A, BV510-A",
+                               "BV605-A, Qdot 605-A",
+                               "BV650-A, Qdot 655-A",
+                               "Alexa Fluor 647-A, APC-A",
+                               "Alexa Fluor 700-A",
+                               "APC-Cy7-A, APC-H7-A",
+                               "PE-A",
+                               "PE-Cy7-A"))
> mainPath = "/fh/fast/gottardo_r/mike_working/tmp/tt"
> library(ncdfFlow)
> FCS_rawfile_Tmr_ALL = read.ncdfFlowSet(list.files(mainPath, recursive = TRUE,full.names = TRUE), channel_alias = map)
Not all FCS files have the same channels
Only load the following common channels:
FSC-A
FSC-H
FSC-W
SSC-A
FITC-A
PerCP-Cy5-5-A
V450-A
V500-A
BV605-A
BV650-A
Alexa Fluor 647-A
Alexa Fluor 700-A
APC-Cy7-A
PE-A
PE-Cy7-A
Skip the channels that are not found in all samples:
Time
SSC-H
SSC-W
write P1_S003_09032015_V1A_Tetramer_DRB1.0401_Pep3_Enr.fcs to empty cdf slot...
write P1_S059_27022017_V4_Tetramer_DRB5.0101_Pep13_Pre.fcs to empty cdf slot...
done!
> for (i in 1:length(FCS_rawfile_Tmr_ALL))
+ {
+   comp_col = colnames(FCS_rawfile_Tmr_ALL[[i]]@description$SPILL)
+   idx = setdiff(comp_col, as.character(map$alias))
+   
+   if (length(idx) > 0)
+   {
+     print(FCS_rawfile_Tmr_ALL[[i]]@description$`TUBE NAME`)
+     re = match(idx,comp_col)
+     FCS_rawfile_Tmr_ALL[[i]]@description$SPILL = FCS_rawfile_Tmr_ALL[[i]]@description$SPILL[-re,-re]
+     }
+ }
> 
> 
> SampleNameListTmr = read.csv("/fh/fast/gottardo_r/mike_working/tmp/SampleNameListTmr.csv", stringsAsFactors = FALSE)
> for (i in SampleNameListTmr$Old){
+   newN = subset(SampleNameListTmr, SampleNameListTmr$Old == i)[['New']]
+   FCS_rawfile_Tmr_ALL[[i]]@description$FILENAME = newN
+   FCS_rawfile_Tmr_ALL[[i]]@description$$FIL = newN
Error: unexpected '$' in:
"  FCS_rawfile_Tmr_ALL[[i]]@description$FILENAME = newN
  FCS_rawfile_Tmr_ALL[[i]]@description$$"
>   FCS_rawfile_Tmr_ALL[[i]]@description$`TUBE NAME` = newN
Error: object 'newN' not found
>   write.FCS(FCS_rawfile_Tmr_ALL[[i]], paste("/fh/fast/gottardo_r/mike_working/tmp/dd/",i,sep = ""))
> }
Error: unexpected '}' in "}"
```
Can you double check and make sure the data you provided work with the code posted here?

**Comment by SamGG** [comment]
Hi. Thanks for updating. Without going too much in details, your processing looks fine. When reading file for those kind of processing, I usually didn't apply any transformation to the data. So just to exclude that hypothesis, could you modify the `read.ncdfFlowSet()` call by adding those parameters: `transformation=FALSE, min.limit=NULL, truncate_max_range = FALSE`?
@mikejiang I think the backquotes of $FIL have been misinterpreted during copy/paste by @mimisikai .

**Comment by mimisikai** [comment]
I can run it without any error:
> for (i in SampleNameListTmr$Old){
+   newN = subset(SampleNameListTmr, SampleNameListTmr$Old == i)[['New']]
+   FCS_rawfile_Tmr_ALL[[i]]@description$FILENAME = newN
+   FCS_rawfile_Tmr_ALL[[i]]@description$`$FIL` = newN
+   FCS_rawfile_Tmr_ALL[[i]]@description$`TUBE NAME` = newN
+
+   write.FCS(FCS_rawfile_Tmr_ALL[[i]],
paste("C:/Users/jhou/Desktop/testing/",newN,sep = ""))
+ }
updating P1_S003_09032015_V1A_Tetramer_DRB1.0401_Pep3_Enr.fcs...
updating P1_S003_09032015_V1A_Tetramer_DRB1.0401_Pep3_Enr.fcs...
updating P1_S003_09032015_V1A_Tetramer_DRB1.0401_Pep3_Enr.fcs...
updating P1_S059_27022017_V4_Tetramer_DRB5.0101_Pep13_Pre.fcs...
updating P1_S059_27022017_V4_Tetramer_DRB5.0101_Pep13_Pre.fcs...
updating P1_S059_27022017_V4_Tetramer_DRB5.0101_Pep13_Pre.fcs...

**Comment by SamGG** [comment]
@mimisikai when pasting code, please insert a line containing only 3 backquotes before and after your code. This forces github to consider this part of text as code, not markdown. This should help reproducing your question.

**Comment by mikejiang** [comment]
@SamGG , Thanks for pointing it out!

**Comment by mimisikai** [comment]
The same flowjo version. I repeat it again, the same issue. Did you see the
P16 and P17 channels in the fcs file after exporting?
[image: 2018-10-16 14_35_27-testing.png]

[image: 2018-10-16 14_37_12-testing.png]

**Comment by SamGG** [comment]
@mikejiang nice job.

**Comment by mimisikai** [comment]
The issues may from the flowjo or windows system. I autoplot the sample
before and after exporting, nothing's changed. but once I use the flowjo,
the bizarre plot shows again.

[image: image.png]
[image: image.png]

**Comment by mikejiang** [comment]
please modify your post to ensure the pics are visible.

**Comment by mimisikai** [comment]
Update: The same data and same code are running in the Mac, the new FCS
files look beautiful. The problem looks from the Windows system but no
clue.

**Comment by danove1** [comment]
Hi @mimisikai ,
I am running into the same problem. I tried opening the fcs files in using flowjo in a Mac computer. But the problem with SSC still persists. Do you have any idea how can I solve this? 
Thank you,
