### ISSUE TITLE
Accessing estimated parameters of estimateLogicle

### ISSUE THREAD

**Issue by coh-racng** [RGLab/openCyto#189]
I have used the estimateLogicle function on several flowsets so far on the following channels. 
` vars `
> [1] "V1-A" "V2-A" "B1-A" "B2-A" "B3-A" "B4-A" "R1-A" "R2-A"

`estimate <- estimateLogicle(fs[[1]], channels = vars, m=4.5)`

But I was encountering an error for a specific flowset

>  Error in logicle_transform(as.double(x), as.double(t), as.double(w), as.double(m),  : 
>   Logicle Exception: IllegalParameter: W is too large 

I noticed that `estimate` is a transformList of transforms, each transforming having a function (x).
`estimate` 
> An object of class "transformList"
Slot "transforms":
$`V1-A`
transformMap for parameter 'V1-A' mapping to 'V1-A'
$`V2-A`
transformMap for parameter 'V2-A' mapping to 'V2-A'
$`B1-A`
transformMap for parameter 'B1-A' mapping to 'B1-A'
$`B2-A`
transformMap for parameter 'B2-A' mapping to 'B2-A'
$`B3-A`
transformMap for parameter 'B3-A' mapping to 'B3-A'
$`B4-A`
transformMap for parameter 'B4-A' mapping to 'B4-A'
$`R1-A`
transformMap for parameter 'R1-A' mapping to 'R1-A'
$`R2-A`
transformMap for parameter 'R2-A' mapping to 'R2-A'
Slot "transformationId":
[1] "defaultTransformation"

Is there a way to look into each of the transform's function to get the parameters for x, t, w, m, and a?
I am not sure how to get the local x, t, w, m, a in `estimate@transforms$`V1-A`@f`:
>function (x) 
x <- logicle_transform(as.double(x), as.double(t), as.double(w), 
    as.double(m), as.double(a), FALSE)
<bytecode: 0x12623b180>
<environment: 0x1bc3e1ea8>

**Comment by gfinak** [comment]
You need to examine the function's captured environment, like so :

```
> as.list(environment(estimate@transforms[["FL1-H"]]@f))
$k
transform object 'FL1-H_logicleTransform'

$transformationId
[1] "FL1-H_logicleTransform"

$w
[1] 0

$t
[1] 10000

$m
[1] 4.5

$a
[1] 0
```

**Comment by mikejiang** [comment]
Also, based on my experience, this error typically can be fixed by switching to another sample for `estimateLogicle` call (i.e. `fs[[2]]` or `fs[[3]]`)

**Comment by DillonHammill** [comment]
An alternative is to coerce the flowSet to a flowFrame for estimateLogicle which can also help to prevent these types of errors.

**Comment by coh-racng** [comment]
Thank you for all your suggestions.
All the flow frames within this particular problematic flowset failed with estimateLogicle, so I fixed it for now by hardcoding the Logicle transform while I try @DillonHammill 's suggestion. 

```
  fs.trans <- try({
    estimate <- estimateLogicle(fs[[1]], channels = vars, m=4.5)
    transform(fs, estimate)
    })
  if (class(fs.trans) == "try-error") {
    lgcl <- logicleTransform(w = 0.5, t= 262143, m=4.5, a=0)
    trans <- transformList(vars, lgcl)
    fs.trans <- transform(fs, trans)
  }

```

**Comment by coh-racng** [comment]
Just tried combining the flowFrames within the flowSet before estimating the parameters. I still get the same error of IllegalParameter: W is too large. 

```
  fr.combined <- fs[[1]]
  for(i in 2:length(fs)){
    fr.combined@exprs <- rbind(exprs(fr.combined), exprs(fs[[i]]))
  }
  fs.trans <- try({
    estimate <- estimateLogicle(fr.combined, channels = vars, m=m)
    transform(fs, estimate)
    })
  if (class(fs.trans) == "try-error") {
    lgcl <- logicleTransform(w = 0.5, t= 262143, m=m, a=0)
    trans <- transformList(vars, lgcl)
    fs.trans <- transform(fs, trans)
  }
```

**Comment by SamGG** [comment]
`fs[[1]]` returns the first flowframe of the flowset.
`fr.combined <- as(fs, "flowframe")` should do the job IIRC
