### ISSUE TITLE
add_pop() not adding gates to "root" node

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/openCyto#190]
Hi guys,

For some reason I am unable to add gates to the "root" node following your recent commits @jacobpwagner.

I have tried to use flowClust as well and still no luck:

```{r}
> add_pop(gs, 
+                 alias = "TestA", 
+                 pop = "+", 
+                 parent = "root", 
+                 dims = "Alexa Fluor 700-A,Alexa Fluor 488-A", 
+                 gating_method = "flowClust",
+                 gating_args = "K=1,quantile=0.95,target=c(3,1)")
...
done
Error in strsplit(row[, parent], split = ",") : non-character argument
```

Are you still able to gate the "root" node? 

This will greatly help me in tracking down where the problem may be. 

I have tried gating other nodes and this seems to work fine.

```{r}
> add_pop(gs, 
+                         alias = "Test", 
+                         pop = "+", 
+                         parent = "T Cells", 
+                         dims = "Alexa Fluor 700-A,Alexa Fluor 488-A", 
+                         gating_method = "flowClust",
+                         gating_args = "K=1,quantile=0.95")
...
done
```

This was working fine yesterday prior to new commits.

Thanks for your help!
Dillon

**Comment by jacobpwagner** [comment]
I'm looking in to it. I'll get a fix up ASAP.

**Comment by jacobpwagner** [comment]
Hi @DillonHammill. I think I figured it out. I quickly decided to take a different approach to 70c0d2349abbc0e0cc6ed1d5a85ddc9c6c969015 and I amended it. But I wasn't quick enough and you probably pulled before I amended it. My apologies and I'll try to never do it again. But I do see your error before the amend and it's gone after. So a hard reset and rebuild should fix it:
`git reset --hard origin/trunk`

**Comment by DillonHammill** [comment]
No Problem. I picked it up while trying to install one of my packages on Travis. I will try the build again now to see if it is working. As for the hard reset I haven't had to do this before. I can just pull down `trunk` with `force=TRUE` in `install_github`? I will try this now...

**Comment by jacobpwagner** [comment]
That should be fine. I also feel I should remind you to preserve your local commits in a branch and stash uncommited changes for your local copy of the repo if you go the hard reset route.

**Comment by DillonHammill** [comment]
The `force=TRUE` approach does not seem to work. For the hard reset I can do this any project? Or must it be in a forked openCyto project?

**Comment by jacobpwagner** [comment]
Ah. Nevermind. It's because the amended commit has the same SHA. The easiest way is probably to delete the package's installation directory and re-install with `install_github`

**Comment by DillonHammill** [comment]
I will give that a try. Looks like the builds are working on Travis now. I must have been unlucky and just pulled it down at the wrong time.

**Comment by jacobpwagner** [comment]
No worries. It's totally my fault. This is exactly why you never amend a public commit.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DillonHammill** [comment]
Thanks @jacobpwagner this is working now.
