### ISSUE TITLE
Dummy gate T/F Issue

### ISSUE THREAD

**Issue by nmonhait** [RGLab/openCyto#192]
Hi Mike and Greg,
I am getting an error with my .csv created using `templateGen()` -

`gt <- gatingTemplate("/Users/monhait/Desktop/flow_cyto/automated_gating/data/gating_template/auto_template_1.csv",
                     strict = FALSE, strip_extra_quotes = TRUE)` returns

Error in if (gm == "dummy") return(this_row) : 
  missing value where TRUE/FALSE needed

I'm hoping there is some direction you can point me in to get me on the right track with this.

Thank you!

**Comment by gfinak** [comment]
could you upload your gating template here?

**Comment by nmonhait** [comment]
Hi Greg, 

Here is the current version of the gating template. I attempted to create a template using templateGen but also ran into errors. 

[BCG_survival_gating_full.xlsx](https://github.com/RGLab/openCyto/files/3122232/BCG_survival_gating_full.xlsx)

**Comment by mikejiang** [comment]
with the latest commits, you will get more useful information regarding several problems your template has
1. referring to the invalid parent (i.e. the original value in `alias`) that was replaced by the auto-generated population names during `+/-` expansion (e.g. `CD44(CD8)+`)
2. parent contains comma and is interpreted as multiple parents and thus split (e.g. `CD62L(CD8,CD44-)`)
 here is the output
```r
> gt <- gatingTemplate("~/Downloads/BCG_survival_gating_full.csv", skip = 1)
splitting the row that has multiple parents: 'CD62L(CD8,CD44-)'
splitting the row that has multiple parents: 'CD62L(CD8,CD44-)'
splitting the row that has multiple parents: 'CD62L(CD8,CD44-)'
splitting the row that has multiple parents: 'CD44(CD4)-,CD62L(CD4)+'
splitting the row that has multiple parents: 'CD44(CD4)-,CD62L(CD4)+'
splitting the row that has multiple parents: 'CD44(CD4)-,CD62L(CD4)+'
alias 'CD44(CD8)' is ignored since pop names are auto-generated from 'dims' when pop = '+/-' 
expanding pop: +/- to APC-Fire 750-A+/APC-Fire 750-A-

alias 'CCR7(CD8)' is ignored since pop names are auto-generated from 'dims' when pop = '+/-' 
expanding pop: +/- to BV421-A+/BV421-A-

 Show Traceback
 
 Rerun with Debug
 Error in .getFullPath(this_row[, parent], new_dt) : 
  Not able to to find reference to: CD44(CD8)+ 
```

**Comment by nmonhait** [comment]
Hi Greg, 

I was running into this error which led me to try and create the template with templateGen(). What I attached was the original template created by the lab. Do you mind if I attach the one I created here, too. They are the same but I am getting the error about the dummy gates with this one. I'm not sure which of these two I should attempt to 'fix.'

[gt_v1.xlsx](https://github.com/RGLab/openCyto/files/3124340/gt_v1.xlsx)

**Comment by mikejiang** [comment]
The original one created by the lab is closer to the final working template that is compatible with the latest `openCyto`. Tried to upgrade your package by `devtools::install_github("RGLab/openCyto", ref = "trunk")` and making corrections to csv by following the guide I posted above

**Comment by nmonhait** [comment]
Hi Mike,
First, thank you so much for helping me out with this. I've upgraded my package and have started making changes to the .csv created by the lab. I understand the issue with the commas, but could benefit from some clarification on the pop names autogenerated by dims.

**Comment by mikejiang** [comment]
It has to do with #156 , pull the latest trunk and rerun `templateGen` should fix pop names issue

**Comment by nmonhait** [comment]
With the latest, all of my pop names are now + with templateGen. Since you indicated that the original (first posted template) is closer to one that will work, do you suggest transferring these pop names over or now working from the templateGen and adding in the gating methods/collapsing the quadgates?

templateGen- 
[edit_pop_gt.xlsx](https://github.com/RGLab/openCyto/files/3132886/edit_pop_gt.xlsx)
original- 
[BCG_survival_gating_full.xlsx](https://github.com/RGLab/openCyto/files/3132887/BCG_survival_gating_full.xlsx)
