### ISSUE TITLE
gating vs gt_gating

### ISSUE THREAD

**Issue by bjreisman** [RGLab/openCyto#204]
Hi openCyto team, I recently installed R on a new computer and ran into issues running older code as follows.

```{r}
> exp_info$gates
--- Gating hieararchy parsed from GatingML: 
	with  5  populations defined
> myflowset <- read.flowSet(file = fcsunzip.paths)
> mygatingset <- GatingSet(myflowset)
................................................................................................................................................................................................done!
> mygatingset_compesated <- compensate(mygatingset, exp_info$compensations$JB)
> mygatingset_scaled <- transform(mygatingset_compesated, exp_info$transforms)
> markernames(mygatingset_scaled) <- exp_info$panels$`Panel 1`
> gating(exp_info$gates, mygatingset_scaled)
Debris
Intact
Singles
Viable
Barcoded
................................................................................................................................................................................................done!
> mygatingset_scaled
A GatingSet with 192 samples
> 
```

This code worked just fine on my older computer running openCyto 1.21.4, but when I tried it on a newer computer running the newest version of openCyto from bioconductor I ran into the follow error:

```{r}
>openCyto::gating(exp_info$gates, mygatingset_scaled)
Error in UseMethod("gt_gating") :
  no applicable method for 'gt_gating' applied to an object of class "c('graphGML', 'graphNEL', 'graph', 'graphBase')"
In addition: Warning message:
'openCyto::gating' is deprecated.
Use 'gt_gating' instead.
See help("Deprecated")
```

Inspecting that object, I see that it's a graphGML object from CytoML
```{r}
> class(exp_info$gates)
[1] "graphGML"
attr(,"package")
[1] "CytoML"
```
...and the gt_gating function seems to expect a gating template. 

I might have missed it, but has something changed about how gates are represented and handed in the openCyto ecosystem? If so, how do I go about getting this code working? Would you consider adding back the old `gating()` function to keep the old method working?

**Comment by jacobpwagner** [comment]
That particular `gating` method lives in `CytoML`. Try removing the `openCyto` namespace specification on your `openCyto::gating` call and either `library(CytoML)` first or explicitly specify `CytoML::gating`.

**Comment by jacobpwagner** [comment]
This was working before because the `gating` generic in `openCyto` was dispatching to the `graphGML`-specific method in `CytoML`. That changed with the API changeover. @mikejiang , do you think we should rename `CytoML::gating` at all to avoid the confusion?

**Comment by bjreisman** [comment]
Ah, I should have mentioned that. When I dropped the `openCyto::` it couldn’t find the function in cytoML, and it appears that the latest version of cytoML doesn’t export a `gating()` function. Is there a post or vignette describing the new API?


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mikejiang** [comment]
I don't think `CytoML::gating` is public API

**Comment by jacobpwagner** [comment]
@bjreisman, a number of methods were recently renamed across our core packages (`flowWorkspace`, `openCyto`, `CytoML`) and the old names were deprecated. However, those methods are still available and should simply produce a deprecation warning like the one you encountered rather than an error. For each package there is also a help doc summarizing the changes line by line that you can access by `help("<package name>-deprecated")`, but we still have to finish this up for `CytoML`.

The problem you ran in to is a little bit different because it was relying on the deprecated `gating` generic from `flowWorkspace`. I'll add a deprecation note specifying the rename from `CytoML::gating` (for a `graphGML` object) to `CytoML::gating_graphGML`. I'll close this once I complete those necessary doc updates.

**Comment by jacobpwagner** [comment]
Done in https://github.com/RGLab/CytoML/commit/ec688d8d5d60be6aa094f29dd94e768dee68b00e. `help("CytoML-deprecated")` should now work as expected.

**Comment by bjreisman** [comment]
Awesome! Thanks for your work on this, looking forward to exploring the new API.
