### ISSUE TITLE
boolGates not appearing as nodes in plot(gs) gating tree

### ISSUE THREAD

**Issue by alexheubeck** [RGLab/openCyto#206]
My gating template uses a few not boolGates (!gate) that are parents to other downstream gates. When I use getNodes(gs), they show up appropriately. However, when I plot the gating tree using plot(gs), those not boolGates do not show up, and the child gates are added at the top next to the root node. Is there a way to have these boolGates show up in the gating tree plot?

Example: All of the gates on starting on the left come off of a !gate
![Rplot](https://user-images.githubusercontent.com/57542158/73888240-20869400-4822-11ea-8053-445d331eb658.png)

**Comment by jacobpwagner** [comment]
Have you already checked out the `boolean=TRUE` arg to `plot`? It's FALSE by default.

**Comment by alexheubeck** [comment]
Must have missed that, that fixed my problem. Thanks!
