### ISSUE TITLE
gt_gating function not found

### ISSUE THREAD

**Issue by drpreeti3628** [RGLab/openCyto#222]
I am using Opencyto version 1.22.2 and I am using gt_gating function to gate.

I am getting error could not find function "gt_gating"

Can you please help

**Comment by gfinak** [comment]
Have a look here: you'll notice that the current release is 2.2.0 https://www.bioconductor.org/packages/release/bioc/html/openCyto.html
You should upgrade, make sure all dependencies are up to date and see if you still get an error.
If so, make a minimal reproducible example using the `reprex` package, paste that here so we can debug.

**Comment by drpreeti3628** [comment]
Hi,

I installed the correct Bioconductor version and 1.24.0 openCyto version and it worked.

Thanks for the help.
