### ISSUE TITLE
Gating using a specific quadrant 

### ISSUE THREAD

**Issue by drpreeti3628** [RGLab/openCyto#223]
Hi,

I have created a quadrant gate for CD4 and CD8 populations using the following logic
"7","*","+/-+/-","CD3+","CD4,CD8","gate_mindensity","gate_range = c(8,8)",NA,NA,"",NA

This created 4 quadrants. Now I wanted to create a further child quadrant gate say from Q1 of the above quadrant gate. What should be parent . Because the above parent was *.

Can you please help

**Comment by mikejiang** [comment]
See the doc here http://bioconductor.org/packages/release/bioc/vignettes/openCyto/inst/doc/HowToWriteCSVTemplate.html#13_pop_=_%E2%80%9C+-+-%E2%80%9D
which explains how `*` is expanded into 4 separate population rows

**Comment by mikejiang** [comment]
i.e. you will have `CD3+/CD4-CD8+`, `CD3+/CD4+CD8+`,`CD3+/CD4+CD8-`,`CD3+/CD4-CD8-` generated and to be referred as parents for subsequent gating

**Comment by drpreeti3628** [comment]
Thanks it worked.
