### ISSUE TITLE
Error in openCyto:::.read.FCS.csv()

### ISSUE THREAD

**Issue by prubbens** [RGLab/openCyto#224]
When trying to open a CSV-file using the `openCyto:::.read.FCS.csv()` function, I get the following error: 

    Error in parameters(fr) <- `*vtmp*` : 
     could not find function "parameters<-"

I've updated to openCyto v2.2.0. The error also emerged when using v2.0.0. Used to work for previous versions of openCyto. Could this be due to updates of the package? 

Many thanks, 

Peter

**Comment by gfinak** [comment]
This is not an exposed API. Can you tell me what you are trying to do?

**Comment by mikejiang** [comment]
I've pushed the quick fix. But as @gfinak said, it is still an internal function (as the by-product of analyzing some csv-based cyto data) and has not been used by other parts of the tool chain) So it is not safeguarded against future bugs.

**Comment by mikejiang** [comment]
resolved with the latest fix. e.g.
```r
library(openCyto)
# library(flowCore)
# data("GvHD")
# fr <- GvHD[[1]]
tmp <- "/tmp/t.csv"
# write.csv(exprs(fr), tmp)
openCyto:::.read.FCS.csv(tmp)
flowFrame object 'anonymous'
with 3420 cells and 9 observables:
             name      desc     range  minRange  maxRange
                         NA   3420.00         1   3420.00
FSC-H       FSC-H        NA   1023.00        59   1023.00
SSC-H       SSC-H        NA   1023.00         6   1023.00
FL1-H       FL1-H        NA  10000.00         1  10000.00
FL2-H       FL2-H        NA   9221.67         1   9221.67
FL3-H       FL3-H        NA   1131.78         1   1131.78
FL2-A       FL2-A        NA   1023.00         0   1023.00
FL4-H       FL4-H        NA   1162.77         1   1162.77
Time         Time        NA    755.00         1    755.00
```

**Comment by prubbens** [comment]
Great, thanks!
