### ISSUE TITLE
How to add correct gate_range 

### ISSUE THREAD

**Issue by drpreeti3628** [RGLab/openCyto#225]
Hi,

I created a quadrant gate and then picked on the quadrant as parent to further gate using gate_mindensity as gatign method and setting a range using gate_range arguments.

I want to leverage the mindensity at x axis at 8 and and at y axis at 2.5. But whatever option I try it leverages only one value at both X and Y axis. Can you please suggest a better option

"6","CD45RACD62L","+/-+/-","PE-A-CAR-BUV396-A-CD5+","PerCP-Cy5-5-A-CD45RA,BV605-A-CD62L","gate_mindensity","gate_range = c(8,2.5)",NA,NA,"",NA

**Comment by mikejiang** [comment]
You will have to do one axis at a time/row, e.g.


\* | +/- | PE-A-CAR-BUV396-A-CD5+ | cd45 | gate_mindensity | gate_range = 8
-- | -- | -- | -- | -- | --
\* | +/- | PE-A-CAR-BUV396-A-CD5+ | cd62 | gate_mindensity | gate_range = 2.5

**Comment by gfinak** [comment]
Thanks, Mike.
@drpreeti3628,
The gate_range argument (and all gating arguments) passed straight through to each gating method.  We aren't doing anything clever with the gating arguments in the expansion.

**Comment by mikejiang** [comment]
Actually this will be closer to your goal if quadGate on cd45 & cd62 are what you wanted


cd45_gate | + | PE-A-CAR-BUV396-A-CD5+ | cd45 | gate_mindensity | gate_range = 8
-- | -- | -- | -- | -- | --
cd45_gate | + | PE-A-CAR-BUV396-A-CD5+ | cd62 | gate_mindensity | gate_range = 2.5
\* | +/-+/- | PE-A-CAR-BUV396-A-CD5+ | cd45,cd62 | refGate | cd45_gate:cd62_gate

**Comment by drpreeti3628** [comment]
Thanks @mikejiang and @gfinak it worked.

I leveraged 2 single gates followed by refGate and it gave me accurate results.

Thank you so much
