### ISSUE TITLE
duplicated preprocessing plugin prior_flowClust

### ISSUE THREAD

**Issue by kforner** [RGLab/openCyto#230]
see https://github.com/RGLab/openCyto/blob/f3ffd896a155add7fb70800366f3cbf39df664a6/R/pluginFramework.R#L13:

```
.DEFAULT_PP <- c("prior_flowClust", "prior_flowClust", "warpSet", "standardize_flowset")
```

**Comment by djhammill** [comment]
Thanks for reporting, this change will be made via https://github.com/RGLab/openCyto/pull/264.
