### ISSUE TITLE
thisCall statement never used in .gating_adaptor()

### ISSUE THREAD

**Issue by kforner** [RGLab/openCyto#233]
cf https://github.com/RGLab/openCyto/blob/0919202643f47b998901628e9afe8e79ba305aa3/R/wrapper-functions.R#L88
in function `.gating_adaptor`, this code seems to never be used:

```
      thisCall <- substitute(f(fr = fr
                                , pp_res = pp_res
                                , channels = channels
                              )
                              ,list(f = as.symbol(gFunc))
```

**Comment by djhammill** [comment]
Thanks for reporting, I have removed the extra code here: https://github.com/RGLab/openCyto/pull/265
