### ISSUE TITLE
Get error message while using openCyto:::.flowClust.2d

### ISSUE THREAD

**Issue by hsiuhong1** [RGLab/openCyto#237]
I am able to use the followings:

openCyto:::.mindensity
rectangleGate
openCyto:::.singletGate
openCyto:::.boundary

When I tried to use openCyto:::.flowClust.2d, I got the following error message:
Error in as.character.default(x) : 
  no method for coercing this S4 class to a vector

**Comment by mikejiang** [comment]
These are internal private APIs not meant to be used directly by the end user. Try to always stick with public exported version of these functions, that is gate _*

**Comment by hsiuhong1** [comment]
Hi Mike,

I still got the same error message.

Below is the code:
chn5 <- c("APC-H7-A", "SSC-A")
gmonocyte <- gate_flowclust_2d(fs_Offaxis, channels = chn5, K = 1, target = c(2.5e5,5e4), quantile = 0.95)

Error message:
Error in as.character.default(x) :
  no method for coercing this S4 class to a vector

I can provide the full script if it is needed.

Many thanks for your help.

Siu-hong

**Comment by mikejiang** [comment]
Please take a look at the documentation of this API `?openCyto::gate_flowclust_2d`, it takes a flowframe and xChannel, yChannel as input

**Comment by hsiuhong1** [comment]
Hi Mike,

Thanks.

I am able to apply the gate_flowclust_2d to a flowframe.  However, if I apply it to the flowset, I got the same error message.

For the flowset I used, it is originally a cytoset.  I use the function cytoset_to_flowSet to convert the cytoset to flowset.

Any insight is appreciated.

Thanks.

Siu-hong

**Comment by mikejiang** [comment]
Again, these gating functions only work with a single flowframe, if you want to work with flowset, you have to write a loop through the flowset, within the loop, extract flowframe from the flowset, then you can apply the function there, for example
```
gates=lapply(sampleNames(cs), function(sn){
	cf = cs[[sn]]
	fr = cytoframe_to_flowFrame(cf)
	gate_flowclust_2d(fr,"APC-H7-A", "SSC-A",  K = 1, target = c(2.5e5,5e4), quantile = 0.95)
	})
```

**Comment by hsiuhong1** [comment]
Thanks, I am able to get through it.
