### ISSUE TITLE
Problem with start/stop.at argument in gt_gating function

### ISSUE THREAD

**Issue by htanaka1234** [RGLab/openCyto#239]
I ran into a problem while working on bypassing Issue #238.
When I specify start/stop.at in the gt_gating function, I get a "Can't find [node]" error.
When using a complex gating template and specifying start/stop.at in the gt_gating function, I sometimes get a "reference node not found" error.
I am guessing that this error is caused by using different node list variables, the order of the nodes often differs between the two variables, when getting the index of the "start" node from "nodePaths" variable and when using this index to specify the node list to be gated from "gt_nodes" variable in the .gating_gatingTemplate function.

```
.gating_gatingTemplate <- function(x, y, env_fct = NULL, start = "root", stop.at = NULL, keep.helperGates = TRUE, ...) {
  gt <- x
  if (!is.null(env_fct)) {
    # use the fcTree if already exists
    if (exists("fct", env_fct)) {
      fct <- get("fct", env_fct)
    } else {
      # create one from gt if not
      fct <- fcTree(gt)
      assign("fct", fct, env_fct)
    }
    
  }
  
  nodePaths <- names(sapply(gt_get_nodes(gt),alias))
    #validity check for stop.at argument
  if(!is.null(stop.at)){
    #escape meta character
    stop.pat <- gsub("\\+", "\\\\+", stop.at)
    stop.pat <- paste0(stop.pat, "$")
    if(substr(stop.at, 1,1) != "/")
      stop.pat <- paste0("/", stop.pat) #prepend path delimiter to avoid partial node name matching
    
    matchInd <- grep(stop.pat, nodePaths)
    if(length(matchInd) == 0)
      stop("Can't find stop point: ", stop.at)
    else if(length(matchInd) > 1)
      stop("ambiguous stop point: ", stop.at)
  }
  # gate each node 
  **gt_nodes <- tsort(gt)[-1]#by the topological order**

  #try to skip some nodes to save time
  if(start != "root"){
    #escape meta character
    start.pat <- gsub("\\+", "\\\\+", start)
    start.pat <- paste0(start.pat, "$") #treat it as terminal node
    if(substr(start, 1,1) != "/")
      start.pat <- paste0("/", start.pat) #prepend path delimiter to avoid partial node name matching
    matchInd <- grep(start.pat, nodePaths)
    
    if(length(matchInd) == 0)
      stop("Can't find start point: ", start)
    else if(length(matchInd) > 1)
      stop("ambiguous start point: ", start)
    
    **gt_nodes <- gt_nodes[matchInd:length(gt_nodes)]**
  }  
 ```

**Comment by mikejiang** [comment]
Can you provide a reproducibe example?

**Comment by htanaka1234** [comment]
Below is a minimal code that reproduces the problem.

[testGatingTemplate.csv](https://github.com/RGLab/openCyto/files/9044792/testGatingTemplate.csv)

>library(dplyr)
>library(data.table)
>library(flowCore)
>library(flowWorkspace)
>library(openCyto)
>dataDir <- system.file("extdata",package="flowWorkspaceData")
>files <- list.files(dataDir, pattern = ".fcs$",full = TRUE)
>fs <- read.flowSet(files[1])
>compMat <- spillover(fs[[1]]) %>% compensation
>fs_comp <- compensate(fs, compMat)
>chnls <- parameters(compMat)
>transFuncts <- estimateLogicle(fs[[1]], channels = chnls)
>fs_trans <- transform(fs_comp, transFuncts)
>gs <- GatingSet(fs_trans)
>gt <- gatingTemplate("path.to.gating.template")
>names(sapply(gt_get_nodes(gt), openCyto:::alias)) #nodePaths
 [1] "root"                                                
 [2] "/boundary"                                           
 [3] "/boundary/singlet"                                   
 [4] "/boundary/singletRefGate"                            
 [5] "/boundary/singlet/Lymph"                             
 [6] "/boundary/singletRefGate/singletRefGate_LymphRefGate"
 [7] "/boundary/singlet/Alexa700_gate"                     
 [8] "/boundary/singlet/AmCyan_gate"                       
 [9] "/boundary/singlet/APC_gate"                          
[10] "/boundary/singlet/PerCPCY5_5_gate"                   
[11] "/boundary/singlet/Lymph/Alexa700pPerCPCY5_5p" 

>RBGL::tsort(gt) #gt_nodes
 [1] "root"                                                
 [2] "/boundary"                                           
 [3] "/boundary/singlet"                                   
 [4] "/boundary/singlet/PerCPCY5_5_gate"                   
 [5] "/boundary/singlet/APC_gate"                          
 [6] "/boundary/singlet/AmCyan_gate"                       
 [7] "/boundary/singlet/Alexa700_gate"                     
 [8] "/boundary/singlet/Lymph"                             
 [9] "/boundary/singlet/Lymph/Alexa700pPerCPCY5_5p"        
[10] "/boundary/singletRefGate"                            
[11] "/boundary/singletRefGate/singletRefGate_LymphRefGate"

>gs_pop_remove(gs, "/boundary")
>gt_gating(gt, gs, stop.at = "/boundary/singlet/PerCPCY5_5_gate")
Gating for 'boundary'
done!
done.
Gating for 'singlet'
done!
done.
stop at: /boundary/singlet/PerCPCY5_5_gate
finished.

>gt_gating(gt, gs, start = "/boundary/singlet/APC_gate")
Population 'singletRefGate'
done!
done.
Population 'singletRefGate_LymphRefGate'
Error in .cpp_getParent(obj@pointer, sampleNames(obj)[1], y) : 
  Lymph not found!
In addition: Warning message:
In grepl(pname, pd$name, ignore.case = T) :
  argument 'pattern' has length > 1 and only the first element will be used

I assume the "Lymph not found!" error occurs because gt_gating stops at the 4th node in the gt_nodes variable due to the argument `stop.at = "/boundary/singlet/PerCPCY5_5_gate"`, and then starts at the 9th node in the gt_nodes variable using the index matched in the nodePaths variable due to the argument `start = "/boundary/singlet/APC_gate"`.

**Comment by mikejiang** [comment]
fixed by https://github.com/RGLab/openCyto/pull/240,
however csv based gating is the legacy interface, (including start/stop arguments), I would highly recommend you switch to `gs_add_gating_method` to incrementally and interactively build/test/trouble shoot each gating step.

**Comment by htanaka1234** [comment]
Thanks for the fix, I have confirmed that `start` argument works fine with openCyto 2.8.3.
Thanks for the information as well. I will work on using `gs_add_gating_method`.
