### ISSUE TITLE
Graphics is the vignette are uggly.

### ISSUE THREAD

**Issue by SamGG** [RGLab/openCyto#244]
Hi Mike.
When you have time, coudl you check what could be wrong?
Best
https://bioconductor.org/packages/release/bioc/vignettes/openCyto/inst/doc/openCytoVignette.html

**Comment by mikejiang** [comment]
this is a bug introduced by the latest ggplot 3.4
See the ticket https://github.com/tidyverse/ggplot2/issues/5076

**Comment by SamGG** [comment]
Yep, already seen the discussion, but I thought it applies only to the dev branch.
Thanks.
