### ISSUE TITLE
openCyto not exporting gate_singlet()?

### ISSUE THREAD

**Issue by mikejiang** [RGLab/openCyto#252]
>On Mon, Mar 11, 2024 at 10:22 PM Wright, Clay <wrightrc@vt.edu> wrote:
>Hi Mike, 
>
>I'm working on updating some code that is a couple of years old for a publication and ran into an issue with openCyto not exporting the gate_singlet function. Is there a reason for this? I'm developing some automated, data-driven workflows for transient expression analysis with positive fluorescence selection and your packages have been critical to this! 
>
>Thanks, 
>Clay 

it has been moved to flowStats package, i.e. `flowStats::gate_singlet`

**Comment by wrightrc** [comment]
Thanks so much!
