### ISSUE TITLE
flowDensity gating plugin

### ISSUE THREAD

**Issue by gfinak** [RGLab/openCyto#62]
For some reason I cannot edit issue #46 
I'd like to close #46 
and reopen it here, if possible. 

I've got flowDensity gating working as a plugin with a few more use cases to test.

An example:
![image](https://f.cloud.github.com/assets/1385593/1618967/5d031030-5642-11e3-8ac8-c872d7b9453e.png)

This is a 1-D boundary gate, but flowDensity always returns a 2-D gate. 
It requires two channels be specified, so the plugin throws an error if that's not specified correctly in the template.
It also requires a position argument to determine which part of the quadrant to keep. 
I check the gating_args for that, but it is can be specified by the population argument (with the +/- definition). 
I'm not sure which should take precedence. Probably the population argument, since we rely on that for downstream gating..
I'm open to suggestions.

**Comment by anaraserikbek** [comment]
In the template table from Jan 8, 2014 Mike Jiang specified the gating_args using & and ! sign, what does this mean and is it still viable for usage?

**Comment by mikejiang** [comment]
That is the `boolean operator` for `boolGate`. Similar to `AndNode` and `NotNode` in `flowJo`.
The screenshot of the complete `gating template` was already shown above.  I don't have csv version, [Here](https://github.com/RGLab/openCyto/blob/trunk/inst/extdata/gating_template/bcell.csv) is the closest version that can be used by you as the draft.
