### ISSUE TITLE
gating method naming convention

### ISSUE THREAD

**Issue by mikejiang** [RGLab/openCyto#69]
`mindensity` and `tailgate` currently don''t follow the same convention (i.e. capitalize the first letter of the second word e.g. `flowClust`,`singletGate`), which easily confuse users.
We may want to deprecate them with `minDensity` and `tailGate`

**Comment by zhanxw** [comment]
As a novice OpenCyto user, I feel either `mindensityGate` or `gate_mindensity` is more understandable than `mindensity`. 

Between `mindensityGate` and `gate_mindensity`, I feel `mindensityGate` may be better, as it looks similar to other gating methods (e.g. `flowStats:: singletGate`, `flowStats: flowStats`).

**Comment by mikejiang** [comment]
Here is what's asked for (in the latest devel), 
![image](https://cloud.githubusercontent.com/assets/1385649/21530782/14de7648-ccf8-11e6-8df2-88bc51bbb752.png)
As shown, this is at `R level`, the name of wrapper function used in `csv gating template` remains as the original one at this point.
