### ISSUE TITLE
special characters in marker names

### ISSUE THREAD

**Issue by mikejiang** [RGLab/openCyto#86]
As Phu reported, `openCyto` is having trouble with the `-` character in `marker name`.

``` r
$P7               <PE-A> BDCA-2   4064.358   57.194542   4121.552
$P8              <ECD-A>    CD2   3850.712  266.930006   4117.642
$P9           <PE-Cy5-A>   CD40   3582.687  523.474713   4106.162
$P10          <PE-Cy7-A>   CD1c   3607.673  497.447446   4105.121
$P11             <APC-A> BDCA-3   3688.781  411.506845   4100.288
$P12 <Alexa Fluor 700-A> HLA-DR   3966.580  150.134612   4116.715
$P13          <APC-H7-A>  CD11c   3580.218  530.579454   4110.798
```

In this scenario, we can't use `partial` marker or channel name  (e.g. `BDCA` or `APC`) because either won't uniquely identify them. Can't use `full` name either, because `-` sign will confuse the `csv template` parser . e.g. `BDCA-3-BDCA-2-` won't be clear to the parser whether each `-` is part of `marker` or the `population pattern`.

~~One way to resolve this is not to use `pop name` to derive any `quadrant` info at all. 
simply encourage user to fill out `+-` pattern in `pop` column without actual `marker/channel` name whenever there is special character, because we have `x,y` channel info from `dims` already.~~

**Comment by mikejiang** [comment]
@ptvan , feel free to add some more working examples since you have more hands-on experiences with `CyTOF` gating.

**Comment by anaraserikbek** [comment]
Do you mean that only by specifying +- sign in the pop column, we can get the 4 gates (+/- for each population)?

**Comment by mikejiang** [comment]
You will still have to put a dummy channel name ,e.g. `A+/-B+/-`

**Comment by ccasar** [comment]
Were there any changes to this or was this never implemented?

I have a channel with Alexa Fluor 488-A HLA-DR and want a line like this in my gating template:

`pDCs,CD123+HLA-DR+,CD3-CD20-,"CD123,HLA-DR",mindensity,,,,,` 

to capture the top right quadrant. Using HLA-DR+ or Alexa Fluor 488-A+ obviously does not work. If I replace the population with ++ I get:

`Error in .preprocess_row(this_row, strict = strict) : 
  invalid population pattern '++'`

Trying out 'dummy channels' like A+B+ I errors:

`Error in getChannelMarker(frm, channel) : can't find XY`

or

`Error in getChannelMarker(frm, channel) : multiple markers matched: B`

**Comment by mikejiang** [comment]
The better solution is to have the template to support `escaped` special character, I will try to push a fix for that. Meanwhile, If `HLA` is uniquely identifiable in your data, then `CD123+HLA+` should work.

**Comment by ccasar** [comment]
Using HLA+ works, I guess previously I forget to change the `dims` names accordingly. But trying `HLA\-DR+` to escape the `-` was also my first intuition to circumvent this problem.

**Comment by mikejiang** [comment]
I plan to deprecate the `dummy channel` idea because user is allowed to put the `quadrant pattern` as `cd4+cd8-` or `cd8-cd4+` and thus the dimension information in `pop` must be consistent with `dims` column in order to derive the correct `quadrant gate`.  The generic `A+B-` simply won't work.

**Comment by anaraserikbek** [comment]
but then, if we're processing a huge flowSet where the same channel named differently in different FCS files (ex. TRCVa24 or TCRV a24 or TCR Va24) due to different users, how can those flowSet .FCS files `pop `match the `dim`, if we use the same template for gating?

**Comment by ccasar** [comment]
In that case you probably couldn't use the same template for all .fcs files because the template parser would not be able to find the string TCRV if it's called TRCV in some of your files.

You probably should rename the channels after loading the files. If the channels are always in the same order, it shouldn't be a problem to set up a list of channels names and apply them to all .fcs files before gating via openCyto.

**Comment by mikejiang** [comment]
If these `TRCV`s are `channel` names (i.e.  `colnames(fs)`), @ccasar was right, you can't put them in a valid `flowSet` in the first place. If they are `marker` names (i.e. `markernames(fs)`) and all have the same common `channel` (e.g. `APC-A`), then you can just use `channel` in `dims`.

Regarding to the special character problem, as discussed with @gfinak , we decide to support pure quadrant pattern, i.e. only `+/-` signs in `pop` column.  (as mentioned by @anaraserikbek in https://github.com/RGLab/openCyto/issues/86#issuecomment-223972822). 
So in the example above, this will do

|    alias   | pop | parent | dims      | gating_method |
|:----------:|-----|--------|-----------|---------------|
| pDCs | ++  | CD3-CD20-   | CD123,HLA-DR | mindensity   |
