### ISSUE TITLE
Example file has a issue with 'register plugins'

### ISSUE THREAD

**Issue by rohunak** [RGLab/openCyto#87]
The script from the example SDY207_OpenCyto from the opencyto.org page has an issue - when I tried running the command: registerPlugins(fun=.dnaGate,methodName='dnaGate', dep='mvtnorm','gating')

> registerPlugins(fun=.dnaGate,methodName='dnaGate', dep='mvtnorm','gating')
Formals of function don't match expected template: 
function(fr, pp_res, channels, ...)
[1] FALSE
Warning message:
In registerPlugins(fun = .dnaGate, methodName = "dnaGate", dep = "mvtnorm",  :
  Can't register function

Any ideas?

**Comment by gfinak** [comment]
Yes, our API for registering plugins has changed in the recent release. The expected formals are now a bit different. The function can be modified to:
```
.dnaGate <- function(fr, pp_res, channels = NA, filterId="", ...){
   xs <- exprs(fr[,channels])
  pnts <- boundry(xs)
  return(polygonGate(boundaries=pnts, filterId=filterId))
}

registerPlugins(fun=.dnaGate,methodName='dnaGate', dep='mvtnorm','gating')

Registered dnaGate
[1] TRUE
```

The `xChannel` and `yChannel` have been replaced with `channels`.

@mikejiang  anything I missed? I don't recall the details.

**Comment by gfinak** [comment]
I need to update the openCyto docs page to reflect this change. I'll leave the example as is, since that's what was published, but there should be a note on the example page pointing to the relevant information.

**Comment by brocneggs** [comment]
thanks, that solution worked.
