### ISSUE TITLE
tmixFilter with flowset

### ISSUE THREAD

**Issue by jpabbuehl** [RGLab/openCyto#89]
Hi,

sorry if I dont ask this question at the right place but I cannot find anywhere else to ask my question. When I perform flowClust (tmixFilter) on a flowSet, I get similar, but slightly different filtering boundaries for each sample. Is there a way to 1) set filtering bondaries on all samples or 2) do it on one sample, extract gating object and apply it on others with Subset(flowset,gating)
thanks in advance
JP

**Comment by mikejiang** [comment]
If you are talking about `2d` gating, `openCyto::flowClust.2d` will give you an `ellipsoidGate` that can be `Subset` with.

```r
library(openCyto)
fr <- fs[[1]] 
gate <- flowClust.2d(fr, xChannel="FSC-H", yChannel="SSC-H")
```

**Comment by mikejiang** [comment]
If you want to go with your approach 1), you can simply collapse the `flowSet` into single `flowFrame`
```r
 fr <- as(fs, "flowFrame")
```

**Comment by jpabbuehl** [comment]
perfect thanks it works fine for K=1. If K>1, how can we select a specific gate for Subset?

**Comment by mikejiang** [comment]
Here is the [doc](https://github.com/RGLab/openCyto/blob/master/man/flowClust2d.Rd#L77-L80) regarding to how the `subset` is selected, basically you need to set `target` (centroid point of the population of interest)
```r
library(openCyto)
library(ggcyto)
#load gated data
gs <- load_gslist("gslist_no_bool/")
#get CD3+ population
fr <- getData(gs[[1]], "3+")
# do the flowclust gating
gate <- flowClust.2d(fr, xChannel="<APC Cy7-A>", yChannel="<PerCP Cy55 Blue-A>", K = 4)
#plot the gate using 'ggcyto' package
autoplot(fr, x = "CD4", y = "CD8", bins = 64) + geom_gate(gate) 
```
So default is the largest `subset`
![image](https://cloud.githubusercontent.com/assets/1385649/8657482/b99353a2-2952-11e5-8ed9-a1f9492e996c.png)

set the `target`
```r
gate <- flowClust.2d(fr, xChannel="<APC Cy7-A>", yChannel="<PerCP Cy55 Blue-A>", K = 4, target = c(1e3,1e3))
autoplot(fr, x = "CD4", y = "CD8", bins = 64) + geom_gate(gate)
```
![image](https://cloud.githubusercontent.com/assets/1385649/8657545/2304291a-2953-11e5-8a8e-0644f3807a28.png)

**Comment by mikejiang** [comment]
This should be posted at https://support.bioconductor.org/
