### ISSUE TITLE
inappropriate error handling in flowClust.2d

### ISSUE THREAD

**Issue by mikejiang** [RGLab/openCyto#93]
The following error was actually caused by passing inaccurate `channel` names and has nothing to do with `prior` setting 

``` r
> gate <- flowClust.2d(fr, xChannel="CD4", yChannel="CD8")
Error in validObject(.Object) : 
  invalid class “flowClust” object: 1: invalid object for slot "w" in class "flowClust": got class "NULL", should be or extend class "vector"
invalid class “flowClust” object: 2: invalid object for slot "mu" in class "flowClust": got class "NULL", should be or extend class "matrix"
invalid class “flowClust” object: 3: invalid object for slot "sigma" in class "flowClust": got class "NULL", should be or extend class "array"
```

The confusing error message is due to the inappropriate error handling [here](https://github.com/RGLab/openCyto/blob/master/R/gating-functions.R#L408-L412).

Basically it needs to properly handle the default `prior` argument before constructing `flowClust` object.

**Comment by mikejiang** [comment]
Actually I don't think we should catch this `flowClust` error at all, because the current behavior of hiding the real error and silently constructing the gate from the prior distributions could generate the misleading gating results. @gfinak ?

**Comment by gfinak** [comment]
I agree with @mikejiang. We can't expect to catch and interpret every error generated by every gating method. I think it's reasonable to pass through the underlying error message. We could perhaps catch it and notify the user that the error is from the gating method and not openCyto itself though.

**Comment by mikejiang** [comment]
This remaining issue once again confused users (and me as well before stepping into code.  see details [here](https://support.bioconductor.org/p/81247/)
