### ISSUE TITLE
Could not load some .fcs files

### ISSUE THREAD

**Issue by XuanTungNCEC** [RGLab/openCyto#94]
Greeting,

I loaded some of my.fcs data using  "read.ncdfFlowSet()" but it returned some error. May you know is it error from data files or error from commands? If the error is from data files, may you give me some suggestion?
![error_yonsei_data](https://cloud.githubusercontent.com/assets/13990725/9513863/badde894-4ccf-11e5-836f-d017a71b4967.PNG)

I loaded this data to FlowJo, it was able to show scatter plot but could not change the option of axises (range, linear scale, log scale...):
![yonsei_data1](https://cloud.githubusercontent.com/assets/13990725/9513900/03a6057a-4cd0-11e5-8ae0-7b941770dadb.png)

I also tried to load some data from the OpenCyto article (http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003806) and the data was loaded normally.
![f_data](https://cloud.githubusercontent.com/assets/13990725/9513924/4c1c1362-4cd0-11e5-9ead-b8d468b394f0.PNG)

Thank you very much for your time,

Best regards

**Comment by gfinak** [comment]
It's hard to say without inspecting the file throwing the error, but it
seems as if the BYTEORD keyword is invalid. It should have four numerical
values, either:
1,2,3,4
or
4,3,2,1
The printed message suggests that the keyword value is simply 1, which is
not valid according to the FCS file specification.
You may want to inspect the FCS file header using read.FCSheader (I think
that's the function name, I'm on mobile and can't confirm), and see what
the BYTEORD keyword looks like.
You could edit the file to make it valid, but I'd suggest tracking down
what software is outputting the invalid fcs and see if it can be resolved
there.

Greg Finak

**Comment by XuanTungNCEC** [comment]
Thank you very much for your help, I really appreciate it.

So my fcs files had some problems. I am trying to study how the fcs files were generated. If I discover something new, I will update it in this post.

Again, thanks for your help.
