### ISSUE TITLE
improving tailgate performance

### ISSUE THREAD

**Issue by ptvan** [RGLab/openCyto#95]
opening this issue at @gfinak's request. Currently, cytokine gating performance (using `tailgate`) is rather poor, cutting widely differently between similar samples, often on the wrong side of peak(?!)
- I have tried adjusting `tol`erance argument (from default 0.01 to 0.001, 0.0001) with no improvement 
- @gfinak has implemented `auto_tol`, but testing on a large data set (ragon Sep2015, 40ptids x 4 stims) doesn't show any improvements
- We've sidestepped the issue by using `quantileGate`, but it would be nice to have a robust `tailgate`

**Comment by gfinak** [comment]
@ptvan 
Could you paste your code that generates the poor results?

**Comment by ptvan** [comment]
```
library(openCyto)
path <- '/shared/silo_researcher/Gottardo_R/pvan_working/ragon/2015Sep'
setwd(path)
gs <- load_gs("output/gs_auto")

# NOTE: template also specifies `min=1` to exclude peak at zero since this is cyTOF data
gtFile <- "Filippos_2015Sep_cyTOF_gt_autotol.csv"
gt <- gatingTemplate(gtFile)

Rm("CD4+/IL2",gs)

gating(gt, gs
       , mc.cores = 4
       , parallel_type = "multicore"
       , start = "CD4+"
)

png("output/ragon_2015Sep_IL2_tailgate_autotol.png", width=1000, height=1200)
latticeExtra::useOuterStrips(plotGate(gs, "CD4+/IL2", cond = "stim+ptid", type="density", main="ragonCyTOF_2015Sep CD4+/IL2 tailgate auto_tol=TRUE"))
dev.off()

```
![ragon_2015sep_il2_tailgate_autotol](https://cloud.githubusercontent.com/assets/8515847/10146648/dd305cc4-65de-11e5-9701-2611ea9850b8.png)

**Comment by gfinak** [comment]
@ptvan What's the relevant line in the template?

**Comment by ptvan** [comment]
IL2,Er166Di,CD4+,Er166Di,tailgate,"min=1,auto_tol=TRUE",,,

**Comment by gfinak** [comment]
The following comes closer:

```
 gs <- load_gs("output/gs_auto")
Rm("CD4+/IL2",gs)
add_pop(gs,alias="IL2",pop="Er166Di",parent =  "CD4+",dims = "Er166Di",gating_method="tailgate",gating_args="min=1,auto_tol=TRUE,adjust=4",groupBy='ptid',collapseDataForGating="TRUE")
latticeExtra::useOuterStrips(plotGate(gs, "CD4+/IL2", cond = "stim+ptid", type="density", main="ragonCyTOF_2015Sep CD4+/IL2 tailgate auto_tol=TRUE"))
```
It seems that CyTOF data is really "bumpy" or maybe there's some discreteness. The usual smoothing factor of 1 just gives a terrible derivative that approaches the 0 on the y axis over and over. By collapsing data per ptid, and applying more smoothing, we get reasonable results. 

![image](https://cloud.githubusercontent.com/assets/1385593/10148638/759ad1e2-65e9-11e5-8a21-a2627999eec9.png)

![image](https://cloud.githubusercontent.com/assets/1385593/10148726/0015defc-65ea-11e5-823f-e9fcc87a773c.png)

**Comment by ptvan** [comment]
Cool, I'll give the higher `adjust` value a try on the remaining `cytokine` markers
