### ISSUE TITLE
consistent argument names for gating functions: `channel` vs. `stain` ?

### ISSUE THREAD

**Issue by ptvan** [RGLab/openCyto#96]
Not a big deal, but maybe consistency would be nice for our various gating functions (unless there is a reason not to...) ? `quantileGate` expect "stain" while `mindensity` and `tailgate` expect "channel" 

```> openCyto:::quantileGate
function (fr, probs = 0.999, stain, plot = FALSE, positive = TRUE, 
    filterId = "", ...) 

> openCyto:::mindensity
function (fr, channel, filter_id = "", positive = TRUE, pivot = FALSE, 
    gate_range = NULL, min = NULL, max = NULL, peaks = NULL, 
    ...) 

> openCyto:::tailgate
function (fr, channel, filter_id = "", num_peaks = 1, ref_peak = 1, 
    strict = TRUE, tol = 0.01, positive = TRUE, side = "right", 
    min = NULL, max = NULL, ...) 
```

**Comment by gfinak** [comment]
quantileGate is not wrapped for use with openCyto.

**Comment by mikejiang** [comment]
Actually `openCyto::.quantileGate` does exist

**Comment by gfinak** [comment]
How is that possible if it doesn't match the expected arguments?

**Comment by mikejiang** [comment]
Maybe @ptvan was referring to the private version of that function `quantileGate` to be used outside of the context of `openCtyo` framework?
