### ISSUE TITLE
mindensity gating problem

### ISSUE THREAD

**Issue by chethanjjj** [RGLab/openCyto#97]
hi, i'm having a problem with mindensity through opencyto. The attached file shows flow cytometry plot. I want the population on the left, but mindensity always choose the population on the right, even when I set positive to FALSE.

![screen shot 2015-10-07 at 4 46 15 pm](https://cloud.githubusercontent.com/assets/13612172/10354291/a07e272a-6d13-11e5-8321-9d68ed66ec59.png)

**Comment by gfinak** [comment]
What does the line in your gating template look like?

**Comment by chethanjjj** [comment]
alias pop parent dims gating_method gating_args collapseDataForGating
groupBy preprocessing_method preprocessing_args
 nonDebris nonDebris root SSC-A mindensity positive = FALSE


From:  Greg Finak <notifications@github.com>
Reply-To:  RGLab/openCyto
<reply+00cfb48c8418ce5c779a34c170bb958e6c80e4918f69196492cf00000001122d722d9
2a169ce0693b35c@reply.github.com>
Date:  Wednesday, October 7, 2015 4:52 PM
To:  RGLab/openCyto <openCyto@noreply.github.com>
Cc:  Chethan Jujjavarapu <jujuchethan@gmail.com>
Subject:  Re: [openCyto] mindensity gating problem (#97)


What does the line in your gating template look like?


Reply to this email directly or view it on GitHub
<https://github.com/RGLab/openCyto/issues/97#issuecomment-146369560> .

**Comment by gfinak** [comment]
I believe you need to specify `nonDebris-`
OpenCyto parses the `+/-` in the population name to determine which cell subset to keep.

**Comment by chethanjjj** [comment]
Hi Greg,

Followed your advice:

  
 alias pop parent dims gating_method gating_args collapseDataForGating
groupBy preprocessing_method preprocessing_args
 nonDebris nonDebris- root SSC-A mindensity positive = FALSE
However, mindensity is still choosing the population on the right.

- Chethan Jujjavarapu


From:  Greg Finak <notifications@github.com>
Reply-To:  RGLab/openCyto
<reply+00cfb48c8996a893b6abbbe13031aa04aa00b6c36112b9e892cf00000001122d72e09
2a169ce0693b35c@reply.github.com>
Date:  Wednesday, October 7, 2015 4:55 PM
To:  RGLab/openCyto <openCyto@noreply.github.com>
Cc:  Chethan Jujjavarapu <jujuchethan@gmail.com>
Subject:  Re: [openCyto] mindensity gating problem (#97)


I believe you need to specify nonDebris-
OpenCyto parses the +/- in the population name to determine which cell
subset to keep.


Reply to this email directly or view it on GitHub
<https://github.com/RGLab/openCyto/issues/97#issuecomment-146370093> .

**Comment by gfinak** [comment]
Here's a reproducible example:
```

**Comment by chethanjjj** [comment]
Thanks, got It working. Had to remove the positive argument

- Chethan Jujjavarapu


From:  Greg Finak <notifications@github.com>
Reply-To:  RGLab/openCyto
<reply+00cfb48c07b7242b613156e6d64346184e8bdbc76bf5e73892cf00000001122e59e39
2a169ce0693b35c@reply.github.com>
Date:  Thursday, October 8, 2015 9:20 AM
To:  RGLab/openCyto <openCyto@noreply.github.com>
Cc:  Chethan Jujjavarapu <jujuchethan@gmail.com>
Subject:  Re: [openCyto] mindensity gating problem (#97)


Here's a reproducible example:


Reply to this email directly or view it on GitHub
<https://github.com/RGLab/openCyto/issues/97#issuecomment-146600402> .

**Comment by gfinak** [comment]
Excellent, thanks. I suspect we need to clarify the documentation a bit.

**Comment by chethanjjj** [comment]
Yea, it would be really helpful if you guys had more documentation on how to
use the different gating methods supported by opencyto. at least from my
experience, its more trial and error with the arguments right now.

- Chethan Jujjavarapu


From:  Greg Finak <notifications@github.com>
Reply-To:  RGLab/openCyto
<reply+00cfb48c4309c15dd4181afb50509b9fd5d509b8e2748feb92cf00000001122e607a9
2a169ce0693b35c@reply.github.com>
Date:  Thursday, October 8, 2015 9:48 AM
To:  RGLab/openCyto <openCyto@noreply.github.com>
Cc:  Chethan Jujjavarapu <jujuchethan@gmail.com>
Subject:  Re: [openCyto] mindensity gating problem (#97)


Excellent, thanks. I suspect we need to clarify the documentation a bit.


Reply to this email directly or view it on GitHub
<https://github.com/RGLab/openCyto/issues/97#issuecomment-146618843> .
